### ISSUE TITLE
Supported Apache httpd versions

### ISSUE THREAD

**Issue by corradofiore** [icing/mod_h2#10]
Hi,

I may have missed something, but I couldn't find anywhere in the docs which versions of Apache this module can be used with.  Specifically, I'm looking at compiling it against http 2.2.x on CentOS 6.x x86_64.  Could you help me?

Thanks,
Corrado

**Comment by icing** [comment]
You are right. I'll add something in the README. 

I develop and test against httpd 2.4.12+. Since I am alone on this so far, I do not plan to verify this against earlier apache versions. If someone wants to do this and has some changes in a pull request, she is welcome!

**Comment by nemobis** [comment]
@corradofiore, if you have updates about 2.2.x on CentOS please share! :)

**Comment by corradofiore** [comment]
Hi,

I'm sorry I haven't got any updates yet.

Best,
Corrado

**Comment by icing** [comment]
I'm sorry. This module works only against a patched 2.4.16 server (patch included). There are no plans to make it work with a 2.2. (which does not mean it is forbidden to do it, but it's a bit of work...)
