### ISSUE TITLE
Compiling mod_proxy_http2 (on Windows)

### ISSUE THREAD

**Issue by Jan-E** [icing/mod_h2#102]
@icing I gave a shot at compiling mod_proxy_http2 on Windows and ran into some issues.

First of all, in h2_proxy_session.c you do a call to ap_sock_disable_nagle().
https://github.com/icing/mod_h2/blob/master/mod_http2/h2_proxy_session.c#L555

However, in mpm_common.h ap_sock_disable_nagle() is not defined for every OS. I surrounded the call in h2_proxy_session.c by the same conditions

```
    s = ap_get_conn_socket(session->c);
#if (!defined(WIN32) && !defined(NETWARE)) || defined(DOXYGEN)
    if (s) {
        ap_sock_disable_nagle(s);
    }
#endif
```
I am not sure what ap_sock_disable_nagle() is supposed to do and if leaving it out on Windows and Netware is disrupting anything.

The second issue was that both h2_util.c and h2_request.c include h2_private.h. h2_private.h contains the following lines

```
extern module AP_MODULE_DECLARE_DATA http2_module;

APLOG_USE_MODULE(http2);
```

These lines caused an unresolved error for 'http2_module' when compiling mod_proxy_http2. I applied a nasty fix by adding a preprocessor definition in the mod_proxy_http2 projects and change the lines as follows:

```
#ifdef IS_PROXY_HTTP2_MODULE
extern module AP_MODULE_DECLARE_DATA proxy_http2_module;

APLOG_USE_MODULE(proxy_http2);
#else
extern module AP_MODULE_DECLARE_DATA http2_module;

APLOG_USE_MODULE(http2);
#endif
```

The fix is nasty, because then mod_http2.so and mod_proxy_http2.so need to be linked to different vesions of h2_util.obj and h2_request.obj. Preferably, these lines should be moved to header-files that are used by only one of the 2 modules. mod_http2.h and mod_proxy_http2.h come to mind, but I will leave that for you to decide.

**Comment by diovoemor** [comment]
Would it not be better just to put the AP_MODULE_DECLARE_DATA and the APLOG_USE_MODULE in the mod_*.c files themselves (like every other module in the source tree)?

**Comment by Jan-E** [comment]
I guess so. Gregg Smith was suggesting the same thing here:
https://www.apachelounge.com/viewtopic.php?p=33334#33334

**Comment by icing** [comment]
Please check out revision r1741596 in Apache svn trunk. I moved the needed request functions to h2_util.c so that h2_request is no longer linked in mod_proxy_http2. Also remove the logging in h2_util.c so that should no be reusable between modules.

Added the nagle #ifdef fix. Please give this a try.

**Comment by Jan-E** [comment]
Failed for both mod_http2 and mod_proxy_http2

```
     Creating library .\Release/mod_http2.lib and object .\Release/mod_http2.exp
h2_request.obj : error LNK2019: unresolved external symbol _ap_create_request referenced in function _h2_request_create_rec
.\Release\mod_http2.so : fatal error LNK1120: 1 unresolved externals
```

```
     Creating library .\Release/mod_proxy_http2.lib and object .\Release/mod_proxy_http2.exp
h2_proxy_session.obj : error LNK2019: unresolved external symbol _ap_casecmpstr referenced in function _process_proxy_header
h2_request.obj : error LNK2019: unresolved external symbol _ap_create_request referenced in function _h2_request_create_rec
h2_request.obj : error LNK2001: unresolved external symbol _http2_module
mod_proxy_http2.obj : error LNK2019: unresolved external symbol _ap_casecmpstrn referenced in function _proxy_http2_canon
mod_proxy_http2.obj : error LNK2019: unresolved external symbol _ap_proxy_connection_create_ex referenced in function _proxy_http2_handler
mod_proxy_http2.obj : error LNK2019: unresolved external symbol _proxy_run_detach_backend referenced in function _proxy_http2_handler
.\Release\mod_proxy_http2.so : fatal error LNK1120: 6 unresolved externals
```
The ap_casecmpstrn backport once again, but also other issues.

**Comment by icing** [comment]
Yes, those are all trunk features of httpd core...

**Comment by Jan-E** [comment]
Maybe. But this one is no core vs 2.4.x issue, while compiling mod_proxy_http2:
`
h2_request.obj : error LNK2001: unresolved external symbol _http2_module`

**Comment by icing** [comment]
;-) The change was that h2_request.c now longer should be linked into mod_proxy_http2. I tried to update this in all the different makefiles we have. What do you use? A new .dsp?

**Comment by Jan-E** [comment]
OK, I backported some things from trunk to 2.4.x and it compiled fine. Mixing git and svn is no pleasure, so I will leave the honour to you to port the changes you made in svn-trunk to git here.

**Comment by Jan-E** [comment]
v1.5.3 compiles out of the box (if you've got the VCx project files). Thanks.
