### ISSUE TITLE
Request header limits are not checked

### ISSUE THREAD

**Issue by mkauf** [icing/mod_h2#104]
mod_http2 does not check these request limits:
* [LimitRequestLine](https://httpd.apache.org/docs/2.4/en/mod/core.html#limitrequestline)
* [LimitRequestFields](https://httpd.apache.org/docs/2.4/en/mod/core.html#limitrequestfields)
* [LimitRequestFieldSize](https://httpd.apache.org/docs/2.4/en/mod/core.html#limitrequestfieldsize)

As there is no request line in HTTP/2, I propose to check the request's pseudo-headers (:method, :scheme, :authority, :path) with both LimitRequestLine and LimitRequestFieldSize.

Some of these limits can be checked in the "HTTP 1.1 code" with "[H2SerializeHeaders](https://httpd.apache.org/docs/2.4/en/mod/mod_http2.html#h2serializeheaders) on", but probably these checks are done after all HTTP/2 headers have already been received. If possible, these limits should be checked "on the fly".

For HTTP 1.x, these limits are checked in `ap_get_mime_headers_core()` in protocol.c.

**Comment by mkauf** [comment]
I have just seen this commit: http://mail-archives.apache.org/mod_mbox/httpd-cvs/201605.mbox/%3C20160517143316.B8E183A17E9%40svn01-us-west.apache.org%3E - nice!

Possible improvements:

I think it would be better (more compatible) to not count the pseudo-headers for LimitRequestFields. The number of pseudo-headers is limited, and they cannot appear multiple times because nghttp2 checks this in the function check_pseudo_header().

If :path is too long, the status code 414 (HTTP_REQUEST_URI_TOO_LARGE) should be used.

**Comment by icing** [comment]
All implemented in v1.5.5.

**Comment by mkauf** [comment]
Wow, you are fast :-)

Some more suggestions: The log level INFO would fit better because it is used in the corresponding log messages for HTTP 1.x. It would also be great if an error document could be sent with the function `ap_send_error_response()`. But probably that's too much work just for this special case.
