### ISSUE TITLE
Multiple warnings in the apache´s log

### ISSUE THREAD

**Issue by sidney-j-r-m** [icing/mod_h2#108]
Hello, what is the meaning of this warning: "release, waiting for x seconds now for 1 h2_workers to return, have still 1 tasks outstanding"? The server is in danger?
Thanks in advance.

[Thu Jun 02 18:54:26 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 35400 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 02 18:54:31 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 35405 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 02 18:54:36 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 35410 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 02 18:54:41 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 35415 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 02 18:54:46 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 35420 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
...
...
[Thu Jun 02 21:05:01 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 43235 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 02 21:05:06 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 43240 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 02 21:05:11 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 43245 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 02 21:05:16 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 43250 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
...
...
[Fri Jun 03 00:29:47 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 55520 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Fri Jun 03 00:29:52 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 55525 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Fri Jun 03 00:29:57 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 55530 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Fri Jun 03 00:30:02 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 55535 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Fri Jun 03 00:30:07 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 55540 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Fri Jun 03 00:30:12 2016] [warn] [client x.x.73.141:55259] AH03198: h2_mplx(161): release, waiting for 55545 seconds now for 1 h2_workers to return, have still 1 tasks outstanding

**Comment by icing** [comment]
This is a ```should not happen``` warning. The server has started one or more workers for handling the HTTP/2 streams and now wants to shut down the connection, often because the client went away.

This warning means that the HTTP/2 handler thinks there is still an ongoing task that needs to return, but seems to be waiting forever. Probably a bug.

Do you have any things in the log before this happened? That would be interesting.

Otherwise, until you restart the server, one thread is occupied with this and not available for new connections. If this happens more and more, your server will stop responding. If this happens rarely, we have a hard-to-repeat bug to hunt down...

**Comment by sidney-j-r-m** [comment]
In this week, there are 16323 of this warning, among various IP addresses.
In the last week, the warning did occur 32493 times.

Anyway, the server is running without any trouble. Maybe, due the fact that it is restarted every week.

**Comment by sidney-j-r-m** [comment]
Before all these warnings, I have got this message in the log, for client  x.x.73.141 :
[Thu Jun 02 09:04:28 2016] [warn] [client x.x.73.141:55259] ->03198: h2_stream(161-13): GET xx.yy.ww /xx/yy/ww -> http 200[orph=1/started=1/done=0]

**Comment by sidney-j-r-m** [comment]
More info: in this situation, the socket remains in CLOSE_WAIT for a long period. It seems that  sometimes the server does not close the socket on client disconnection.

**Comment by icing** [comment]
Please give 1.5.7 a try. I found a situation where the shutdown of connection was hanging and would produce the log output you observed. Thanks!

**Comment by sidney-j-r-m** [comment]
Thank you for the new release. I will try it.

**Comment by sidney-j-r-m** [comment]
The warnings have not disappeared, but the number of cases decreased significantly.

[Wed Jun 08 19:38:57 2016] [warn] [client x.x.16.135:57756] AH03198: h2_mplx(96): release, waiting for 5 seconds now for 2 h2_workers to return, have still 2 tasks outstanding
[Wed Jun 08 19:38:57 2016] [warn] [client x.x.16.135:57756] ->03198: h2_stream(96-1): GET xx.yy.ww /xxxx -> reset 8[orph=1/started=1/done=0]
[Wed Jun 08 19:38:57 2016] [warn] [client x.x.16.135:57756] ->03198: h2_stream(96-3): GET xx.yy.ww /wwww -> reset 8[orph=1/started=1/done=0]
[Wed Jun 08 19:39:02 2016] [warn] [client x.x.16.135:57756] AH03198: h2_mplx(96): release, waiting for 10 seconds now for 2 h2_workers to return, have still 2 tasks outstanding
[Wed Jun 08 19:39:07 2016] [warn] [client x.x.16.135:57756] AH03198: h2_mplx(96): release, waiting for 15 seconds now for 2 h2_workers to return, have still 2 tasks outstanding
[Wed Jun 08 19:39:12 2016] [warn] [client x.x.16.135:57756] AH03198: h2_mplx(96): release, waiting for 20 seconds now for 2 h2_workers to return, have still 2 tasks outstanding

**Comment by sidney-j-r-m** [comment]
Also, a new warning debuts:
[Wed Jun 08 11:32:40 2016] [warn] (11)Resource temporarily unavailable: [client x.x.84.82:52146] AH03385: h2_task(242-117): input shutdown
[Wed Jun 08 11:32:40 2016] [warn] (11)Resource temporarily unavailable: [client x.x.84.82:52146] AH03385: h2_task(242-119): input shutdown
[Wed Jun 08 11:32:42 2016] [warn] (11)Resource temporarily unavailable: [client x.x.84.82:52146] AH03385: h2_task(242-123): input shutdown
[Wed Jun 08 11:32:45 2016] [warn] (11)Resource temporarily unavailable: [client x.x.84.82:52146] AH03385: h2_task(242-139): input shutdown
[Wed Jun 08 11:32:47 2016] [warn] (11)Resource temporarily unavailable: [client x.x.84.82:52146] AH03385: h2_task(242-151): input shutdown
[Wed Jun 08 11:32:47 2016] [warn] (11)Resource temporarily unavailable: [client x.x.84.82:52146] AH03385: h2_task(242-153): input shutdown

**Comment by icing** [comment]
Thanks for the feedback! Someone else reported crashes with 1.5.7, that's why there is now a 1.5.8 that should also do away with the warning re "input shutdown".

**Comment by sidney-j-r-m** [comment]
Thank you for the response.
With v1.5.8, the warnings still occur: 
...
[Thu Jun 09 10:18:13 2016] [warn] [client x.x.11.2:53785] AH03198: h2_mplx(29): release, waiting for 845 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 09 10:18:14 2016] [warn] [client x.x.220.40:60311] AH03198: h2_mplx(61): release, waiting for 625 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 09 10:18:14 2016] [warn] [client x.x.184.172:49975] AH03198: h2_mplx(53): release, waiting for 700 seconds now for 2 h2_workers to return, have still 2 tasks outstanding
[Thu Jun 09 10:18:15 2016] [warn] [client x.x.11.2:53769] AH03198: h2_mplx(199): release, waiting for 1250 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 09 10:18:15 2016] [warn] [client x.x.11.2:53762] AH03198: h2_mplx(121): release, waiting for 1475 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 09 10:18:15 2016] [warn] [client x.x.173.11:51619] AH03198: h2_mplx(128): release, waiting for 170 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 09 10:18:16 2016] [warn] [client x.x.248.6:52617] AH03198: h2_mplx(119): release, waiting for 75 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 09 10:18:16 2016] [warn] [client x.x.182.7:49236] AH03198: h2_mplx(147): release, waiting for 530 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 09 10:18:18 2016] [warn] [client x.x.78.6:51768] AH03198: h2_mplx(123): release, waiting for 220 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 09 10:18:18 2016] [warn] [client x.x.11.2:53785] AH03198: h2_mplx(29): release, waiting for 850 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 09 10:18:19 2016] [warn] [client x.x.220.40:60311] AH03198: h2_mplx(61): release, waiting for 630 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 09 10:18:19 2016] [warn] [client x.x.184.172:49975] AH03198: h2_mplx(53): release, waiting for 705 seconds now for 2 h2_workers to return, have still 2 tasks outstanding
[Thu Jun 09 10:18:20 2016] [warn] [client x.x.11.2:53769] AH03198: h2_mplx(199): release, waiting for 1255 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Thu Jun 09 10:18:20 2016] [warn] [client x.x.11.2:53762] AH03198: h2_mplx(121): release, waiting for 1480 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
...

**Comment by Sp1l** [comment]
Just ran into this as well... httpd was spinning at 275% CPU (Dual-Core +HT)

[Mon Jul 04 19:42:57.367438 2016] [http2:warn] [pid 62573:tid 34695388160] [client 192.0.2.125:44002] AH03198: h2_mplx(214): release, waiting for 59665 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
[Mon Jul 04 19:42:57.386434 2016] [http2:warn] [pid 62573:tid 34695370752] [client 192.0.2.125:54640] AH03198: h2_mplx(197): release, waiting for 37620 seconds now for 1 h2_workers to return, have still 1 tasks outstanding

Restarting Apache solved it...
```
[Mon Jul 04 19:42:59.147100 2016] [http2:info] [pid 18587:tid 34393318400] AH03090: mod_http2 (v1.5.11, feats=CHPRIO+SHA256, nghttp2 1.12.0), initializing...
[Mon Jul 04 19:42:59.672141 2016] [mpm_event:notice] [pid 18587:tid 34393318400] AH00489: Apache/2.4.22 (FreeBSD) LibreSSL/2.4.1 PHP/7.0.8 configured -- resuming normal operations
[Mon Jul 04 19:42:59.672268 2016] [core:notice] [pid 18587:tid 34393318400] AH00094: Command line: '/usr/local/sbin/httpd -D NOHTTPACCEPT'
```

**Comment by icing** [comment]
Which revision from 2.4.x?

**Comment by Sp1l** [comment]
This is the vanilla mod_http2 from the Apache 2.4.22 dist tarball.

**Comment by icing** [comment]
```
/* SHOULD NOT HAPPEN */ 😡
```

**Comment by icing** [comment]
Why are such things always reported on release days? Hmm? Some conspiracy theory anyone?

**Comment by Sp1l** [comment]
> Why are such things always reported on release days? Hmm? Some conspiracy theory anyone?

I hung on to the problem as long as I could :smile: 

Just upgraded to 2.4.23, let's see if the error returns...

As always, happy to run a version from this repo!

**Comment by chrcoluk** [comment]
see my new bug report on wordpress here, those warnings get logged whilst wordpress is running its upgrade.

https://github.com/icing/mod_h2/issues/116

**Comment by djfordz** [comment]
I have also run into same issue recently. One of my clients runs a php script that had no issues on HTTP/1.1 and this is the only error in the logs and the script now hangs and it looks like mpm+prefork gets a SIGTERM, however haven't concluded this is related to the h2_mplx(11) release, waiting for XX seconds now for 1 h2_workers to return, have still 1 tasks outstanding.

CentOS 6, Apache 2.4.23

**Comment by icing** [comment]
@djfordz thanks for the data. This is definitely a weird one. Would you have the chance to build the v1.7.1 from here against the 2.4.23 apxs? Would love to see if it changes anything, as the connection input handling got some love in the meantime.

**Comment by djfordz** [comment]
@icing I'll ask the company to deploy v1.7.1 I'll let you know. currently we have switched the customer's server back to http/1.1 until we can get this resolved.

**Comment by icing** [comment]
@sidney-j-r-m while working on more tests for v1.7.5, I also stumbled upon a case where ```mod_h2``` generated exactly the warnings you see in your log. Might be worth a revisit, if this still occurs for you. Thanks!

**Comment by sidney-j-r-m** [comment]
Ok, I'll check it out.

**Comment by sidney-j-r-m** [comment]
The warnings still persist.
How to reproduce:
1) Download Tomcat and setup a simple webapp;

2) Create a file 'test-slow.jsp':
<%
        //600000 milliseconds = 10 minutes.
        Thread.sleep(600000);
%>

3) Setup conf in Apache: 
<Location /test>
       ProxyPass http://localhost:8080/test
       ProxyPassReverse  http://localhost:8080/test
       Require all granted
</Location>

4) Enable mod_http2 and SSL in Apache;

5) Using Chrome or Firefox, access https://localhost/test/test-slow.jsp, wait a few seconds(ten seconds), and close the browser completely(all tabs, windows and processes);

6) Look in the log.

**Comment by djfordz** [comment]
@icing I am not able to convince the company to build against latest, sorry I am unable to help.

**Comment by icing** [comment]
@sidney-j-r-m you describe a valid case, where the request processing is just busy and not getting back very quickly. Since this can happen regularly, depending on the application, I have increased the timeouts in the latest release to one minute, which should spam less in the logs.

If we can see that these are the only cases and that proper shutdown happens eventually, I will lower the log level on these.

**Comment by sidney-j-r-m** [comment]
Ok, thanks very much.

**Comment by sidney-j-r-m** [comment]
In genereal, the number of warnings has declined significantly.

A few of this warning appears in the log: (103)Software caused connection abort: [client *.*.231.6:26881] AH02938: h2_stream(30-121): reading data
But its occurrence is rare.

**Comment by vorel** [comment]
Same issue with Apache 2.4 and Piwik analytics on server. From now I'm using apache 2.4 with mod_http2 (v1.7.9-git, feats=CHPRIO+SHA256+INVHD, nghttp2 1.16.0). I will let you know if it still remains.

The problem is not only log filling, but the server answer is very slow during these errors. After apache restart everything is ok.

@icing Did you mean "TImeout" or "KeepAliveTimeout" directive? On what number did you increased it? I'm using Timout 30, which is not many, but I have no problem with this configuration so far. Should I used Timeout 120? Thanks for your answer.

**Comment by icing** [comment]
@vorel keep your configuration. The timeout I am talking about is an internal one for checking of all started requests have been shut down.

**Comment by vorel** [comment]
More than one day in production and without errors and without slowing down. So I hope it will be ok. I could recommend for everyone else ;-) I only check logs once a day from now, if any error occur, I will let you know. Thanks everyone for help!

@icing thanks for your message, I kept my configuration based on it and sorry for misunderstandings.
