### ISSUE TITLE
Mod_http2 does not check ProxyTimeout directive

### ISSUE THREAD

**Issue by sidney-j-r-m** [icing/mod_h2#109]
Mod_http2 does not check ProxyTimeout directive, but it checks Timeout instead.
ProxyTimeout is usefull when we are proxying to PHP(mod_proxy_fcgi) and HTTP(mod_proxy_http).

If Timeout is low(like 5 seconds) and ProxyTimeout is high(like 2 minutes), and backend server takes more than 5 seconds to respond, the mod_http2 closes the request and returns nothing to user. It ignores ProxyTimeout.

However, a high value for Timeout(for instance, 2 minutes) may cause the web server produce a lot of warnings 'h2_mplx(): release, waiting for "x" seconds now for "y" h2_workers to return, have still "w" tasks outstanding'. Also, the server may run out of threads.

A way to verifiy this warning: 
1)  Set up a server with mod_http2, with protocol h2(https), and Timeout directive with 2(or more) minutes;
2) Create a simple page for file upload;
3) Open Chrome browser and Developer Tools;
4) On Network tab, choose Throttling, add a custom speed, "slow";
5) For "slow", change both upload and download to 4(kb/s), and latency to 500ms;
6) Select this speed for throttling;
7) Access the upload page, and send a large file(5 MB, for instance);
8) Wait 10 seconds, and without stop the upload, close the Chrome completely;
9) Wait 5 seconds, and inspect the server error log. Search for "tasks outstanding".
The connection was closed, but the server still waits for the client.

Thanks in advanced.

**Comment by icing** [comment]
I might be wrong here, but my undestanding it the following:
 * the connection to the client (frontend) always respect ```Timeout```and only that
 * the connection to the backend (appserver) that uses the proxy modules, respect ```ProxyTimeout```
If no ```ProxyTimeout``` is specified, the value of ```Timeout``` applies.

So, if the proxytimeout is much larger than the timeout, the frontend connection times out and is closed. The backend connection is still waiting. That is the warning you see in the log, as the frontend close is waiting for the proxy request to complete.

The error here seems to be that the proxy request should abort, when the frontend connection goes away (for whatever reason). That is currently no the case and that is why you see these warnings in the log.

Right?

**Comment by covener** [comment]
On Mon, Jun 13, 2016 at 11:59 AM, Stefan Eissing <notifications@github.com>
wrote:

> So, if the proxytimeout is much larger than the timeout, the frontend
> connection times out and is closed. The backend connection is still
> waiting. That is the warning you see in the log, as the frontend close is
> waiting for the proxy request to complete.
>
> ​In http/1.1, nobody is watching the clock on the frontend connection when
mod_proxy is waiting on the backend connection. Maybe that could be
simulated in h2?​



-- 
Eric Covener
covener@gmail.com

**Comment by covener** [comment]
On Mon, Jun 13, 2016 at 12:29 PM, Eric Covener <covener@gmail.com> wrote:
>
> On Mon, Jun 13, 2016 at 11:59 AM, Stefan Eissing <notifications@github.com>
> wrote:
>>
>> So, if the proxytimeout is much larger than the timeout, the frontend
>> connection times out and is closed. The backend connection is still waiting.
>> That is the warning you see in the log, as the frontend close is waiting for
>> the proxy request to complete.
>
> In http/1.1, nobody is watching the clock on the frontend connection when
> mod_proxy is waiting on the backend connection. Maybe that could be
> simulated in h2?

(I mean this is how the core of the server works for http/1.1 / how
mod_h2 could behave, not something fundamental in the  protocols
themselves)





-- 
Eric Covener
covener@gmail.com

**Comment by sidney-j-r-m** [comment]
Thank you for response.

Without mod_http2, but with ProxyTimeout higher than Timeout, the connection remains, until the backend server returns. The client receives the response. In this case, Timeout is used to check IO "health" of TCP connection(http://httpd.apache.org/docs/2.4/mod/core.html#timeout). May be I am wrong. I'm not a expert.

With mod_http2 it's different. When Timeout "times out",  it closes the connection(or stream, I don't know), and returns nothing to user, regardless value of ProxyTimeout.
When Timeout is set with a high value(5 minutes, for example), and ProxyTimeout is unset, and the connection speed is low, and user closes the browser,  the warning "h2_mplx(): release, waiting for ..." appears in the error log.

**Comment by covener** [comment]
Sorry, meant primarily for @icing as a contrast to why the low Timeout doesn't work in pure http/1.1 in Apache.

And I see on github my mail clients quoting was confused so re-pasting:

In http/1.1, nobody is watching the clock on the frontend connection when
mod_proxy is waiting on the backend connection. Maybe that could be
simulated in h2?​

**Comment by icing** [comment]
See what you mean. Hmm. That would mean changing timeout behaviour when requests have processed possible input and conn waits for response/output. 

Need to think about this some more...

**Comment by icing** [comment]
Sidney, 

please check if v1.5.13 addresses your issues. ```Timeout``` no longer matters while a request is being processed. Then the ```ProxyTimeout``` determines only how long the request will wait.

**Comment by sidney-j-r-m** [comment]
Thank you for the new release. I will test it today.

**Comment by sidney-j-r-m** [comment]
It seems to work well, respecting the ProxyTimeout directive. Thanks!

**Comment by icing** [comment]
Wonderful! Thanks for the quick feedback!
