### ISSUE TITLE
add version report in error log on startup

### ISSUE THREAD

**Issue by chrcoluk** [icing/mod_h2#115]
I have no idea what version is bundled with apache, I checked the source code, and nothing in there.

Please add it so when apache is started, it prints the version of the module in the error log like some other modules do.

Also while I am here which version of mod_h2 is in the latest apache 2.4.x tarball?

**Comment by icing** [comment]
If you add
```
LogLevel http2:info
```
you get exactly that information in the ```error.log```.

The version in Apache 2.4.23 should be v1.5.10 if memory serves me well.
