### ISSUE TITLE
mod_h2 breaks wordpress 

### ISSUE THREAD

**Issue by chrcoluk** [icing/mod_h2#116]
So on protocol 1.1. if I update wordpress by clicking upgrade in the web gui, after the upgrade finishes it will either load a success or failed page depending if the upgrade worked or not.

If I do the same with over http/2 then at the end of the upgrade process I get a "connection has been closed" error in the browser, regardless if the upgrade worked or not, it doesnt kill the upgrade so http/2 waits long enough but then fails to load the page at the end.

I did look to toggle some timeouts but it seems h2timeout etc. no longer exist?

**Comment by chrcoluk** [comment]
note this bug report, whilst wordpress is updating the log fills with those.

https://github.com/icing/mod_h2/issues/108

**Comment by icing** [comment]
@chrcoluk there is a fix in regard to timeout handling in mod_http2 v1.5.13. The normal ```Timeout``` directive was applied to ongoing requests which should not. It should only apply to IO operations. That has been fixed.

Your problem sounds like it matches that. Try either to raise ```Timeout``` to something large enough or deploy a newer module from here.

**Comment by icing** [comment]
@chrcoluk did you have the chance to test a newer version if it behaves as needed?

**Comment by icing** [comment]
Closing due to lack of feedback on fix.
