### ISSUE TITLE
PUSH does not working with Redirects (301)

### ISSUE THREAD

**Issue by sascha-hendel** [icing/mod_h2#118]
If you send a Redirect (301) with Apache (2.4.23) and the redirect target as PUSH link, Apache won't push this file to the client.

**Comment by icing** [comment]
@sascha-hendel thanks for the report, will try to reproduce soon. Just to be clear:

```
client ---> :path '/abc'
          <--- 302 Location '/xyz'
and you want to immediately
         <--- PUSH_PROMISE GET '/xyz'
```
is that correct?

Currently, 3xx responses are ignored for PUSHes since 304 is a response where PUSH is most likely counter productive...

**Comment by sascha-hendel** [comment]
I create the pages with PHP. In this case following code is used:

header(HTTP/2.0 301 Moved Permanently');
header('Location: '.$newurl);
header('Link: <'.$newurl.'>; rel=preload');

Live example:
https://www.book-info.com/isbn/0241968984.htm 
redirects to
https://www.book-info.com/isbn/0-241-96898-4.htm

**Comment by icing** [comment]
In the Apache httpd 2.4.25, as well as the lastest version here, you should be able to push also on a 3xx status code by using the new directive ```H2PushResource```. Care to give this a try?

**Comment by sascha-hendel** [comment]
Thanks for the info, but how can I use H2PushResource within PHP?
Are ther any example for the use of this new directive?

**Comment by icing** [comment]
```H2PushResource``` is a configuration directive for the server. Look for example at https://www.filamentgroup.com/lab/modernizing-delivery.html for a detailed post about using it.

**Comment by sascha-hendel** [comment]
H2PushResource is a nice new server directive for Apache, but doesn't solve this issue. Therefore the issue should be reopened!
I want to define the push resource in the PHP file, not in a server directive! The following code is expected to work:

header('HTTP/2.0 301 Moved Permanently');
header('Location: '.$newurl);
header('Link: <'.$newurl.'>; rel=preload');

And I don't understand, why this isn't possible. It makes no sense to ignore PUSH for all 3xx responses, only because 304 in combination with PUSH is counter productive.
