### ISSUE TITLE
mod_h2 breaks setup with multiple certificates

### ISSUE THREAD

**Issue by hannob** [icing/mod_h2#12]
Current version (0.4.3) of mod_h2 seems to break a server setup with multiple certificates.

To test:
* Setup a webpage with a valid certificate and a subdomain with a self-signed / not browser accepted certificate
* Include an image in the webpage from the subdomain

It will shown the image, because it will be delivered under the same certificate.

**Comment by icing** [comment]
Could this be the result of wildcard certificates that may cause browsers to reuse open HTTP/2 connections for other virtual hosts?

**Comment by icing** [comment]
Could you check v0.5.1, if the correct site is selected on your server? I, unfortunately, have no access to a wildcard certificate that is accepted by browsers.

**Comment by hannob** [comment]
Still same issue.

As for the wildcard cert: Why can't you just generate a selfsigned one from your own CA and add that to the browser for testing?

**Comment by icing** [comment]
After reading the issue description again carefully, what you're saying is your setup is:
- virtual host https://example.org with valid cert for *.example.org
- virtual host https://invalid.example.org with invalid cert for, well, itself

and https://example.org/index.html includes https://invalid.example.org/image.jpg and the browser shows this to you?

If I understood this correctly, I think there is no fault in browser or server. The connection to https://example.org/ is authoritative for all *.example.org. The browser is free to use it. It does not matter that there is an invalid cert somewhere else, imo.

**Comment by icing** [comment]
Ok, after checking on the httpwg mailing list with the experts, this is a configuration problem. mod_h2 behaves correctly here.
