### ISSUE TITLE
Interaction with HAProxy (mod_proxy_protocol)

### ISSUE THREAD

**Issue by szbalint** [icing/mod_h2#122]
For larger production environments it's fairly common to have HAProxy in front of webservers to provide master-master loadbalancing and TLS termination services.

HAProxy supports handling incoming connections both on the tcp and on the http1.x level, but it does not have h2 support yet, which means that any system that would like to use HAProxy in front of a h2 capable apache needs to rely on tcp-level loadbalancing.

To handle arbitrary tcp connections, HAProxy came up with the so-called [PROXY protocol](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt) to enable forwarding client information (ip addresses, etc.) to servers behind HAProxy. That protocol relies on the cooperation of both HAProxy and the server behind it, because it works by adding a header to those tcp connections forwarded from HAProxy and the destination server has to remove the header before further processing the rest of the connection data.

For Apache, `mod_proxy_protocol` handles the part of removing the header and making Apache aware of the true client connection details - instead of HAProxy's.

Unfortunately, it seems that HTTP/2 broke some assumptions and trying to use `mod_proxy_protocol` in combination with `mod_h2` (`v1.8.2-git, feats=CHPRIO+SHA256+INVHD, nghttp2 1.17.0`) seems to result in errors, specifically: `[proxy_protocol:error] [pid 8565] [client 127.0.0.1:38181] ProxyProtocol: no valid header found`, regardless of whether `H2SerializeHeaders` is on or off.

I've also [opened a version of this issue](https://github.com/roadrunner2/mod-proxy-protocol/issues/6) over at `mod_proxy_protocol`, as I'm not sure where this issue should be best tackled and whether resolving this would require changes in both codebases, or if even it is possible at all under the current assumptions that both modules make.

**Comment by icing** [comment]
Upon glancing over the code of ```mod_proxy_protocol``` this seems to be an issue of correct input filter ordering. The proxy_protocol input filter must read *before* the h2 input filter.

And subsequently, for request patching, this will happen on a ```slave``` connection with h2, so the module needs to check ```conn_rec->master``` and retrieve its settings there, if available.

**Comment by icing** [comment]
Thanks, @szbalint  for reporting this in detail.

**Comment by icing** [comment]
@szbalint do you require any more changes in ```mod_http2``` to get this working?

**Comment by icing** [comment]
Issue reported as fixed.
