### ISSUE TITLE
The MergeTrailers directive has no effect for HTTP/2

### ISSUE THREAD

**Issue by mkauf** [icing/mod_h2#123]
mod_http2 currently does not support the [MergeTrailers](https://httpd.apache.org/docs/2.4/en/mod/core.html#mergetrailers) directive.

**Comment by icing** [comment]
That is true. It also does not support [Fascism](https://en.wikipedia.org/wiki/Fascism).

**Comment by icing** [comment]
In more seriousness, thanks for the hint. That should be ease enough to add, although I will not do it before the next Apache release.

**Comment by icing** [comment]
Please check v1.8.6 which does implement it. Found no good test case, though.
