### ISSUE TITLE
h2_h2.c:566:5: error: implicit declaration of function ‘ap_hook_pre_close_connection’ [-Werror=implicit-function-declaration]

### ISSUE THREAD

**Issue by deadjdona** [icing/mod_h2#125]
/mod_http2-1.8.3# make
Making all in mod_http2
make[1]: Entering directory '/home/ubuntu/mod_http2-1.8.3/mod_http2'
  CC       mod_http2_la-h2_conn.lo
  CC       mod_http2_la-h2_filter.lo
  CC       mod_http2_la-h2_h2.lo
h2_h2.c: In function ‘h2_h2_register_hooks’:
h2_h2.c:566:5: error: implicit declaration of function ‘ap_hook_pre_close_connection’ [-Werror=implicit-function-declaration]
     ap_hook_pre_close_connection(h2_h2_pre_close_conn, NULL, mod_ssl, APR_HOOK_LAST);
     ^
cc1: all warnings being treated as errors
Makefile:705: recipe for target 'mod_http2_la-h2_h2.lo' failed
make[1]: *** [mod_http2_la-h2_h2.lo] Error 1
make[1]: Leaving directory '/home/ubuntu/mod_http2-1.8.3/mod_http2'
Makefile:458: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by icing** [comment]
Hmm, something is not correct with the general httpd header files you are using. Which version are you compiling against?. Please run
```
apxs -q HTTPD_VERSION
```
The function you are missing should be declared in ```http_connection.h```.

**Comment by icing** [comment]
Anyway I can help? Otherwise I close this issue. You mail also get help on the Apache httpd users mailing list.
