### ISSUE TITLE
mod_http2 1.8.3 issue with Option index +

### ISSUE THREAD

**Issue by nono303** [icing/mod_h2#126]
I've just upgraded my version of apache from 2.4.23 to 2.4.25 (vc14 x64) and I've noticed a bug relating to mod_http2.
According to changelog https://www.apachelounge.com/Changelog-2.4.html nghttp2 had been upgraded to 1.17.0 from 1.12.0

> `=> [http2:info] AH03090: mod_http2 (v1.8.3, feats=, nghttp2 1.17.0), initializing...`

In my case, I've multiple ssl vhost with '`H2Direct on`' & '`Protocols h2 http/1.1`' directives (all working fine with 2.4.23) but since upgrade, all (but only) location with '`Options +Indexes`' directive fail to work (unable to connect from browser or curl)
Downgrading only mod_http2.so with the 2.4.23 one (on a 2.4.25 httpd binary) solve the issue.

>     WORKING : mod_http2.so (nghttp2 1.12.0 from 2.4.23 vc14 x64 distrib) 
>     SHA-1: 296f024c98e95ca3e72d0108ff39e75edf7640fd
> 
>     FAILING : mod_http2.so (nghttp2 1.17.0 from 2.4.25 vc14 x64 distrib) 
>     SHA-1: b48733e6efa8431fab4026370329491607949cce

Please find debug log (curl client and Apache2.4.25 http2:debug) below

[log_ko.txt](https://github.com/icing/mod_h2/files/665870/log_ko.txt)
[log_ok.txt](https://github.com/icing/mod_h2/files/665871/log_ok.txt)

**Comment by icing** [comment]
Do you mean
```
  Options +Indexing
```
? With that I am not able to reproduce. Can you try to make a minimal vhost config where the problem occurs?

**Comment by nono303** [comment]
`<Location />Options +Indexes</Location>` exactly.
Effectively, with from scratch configuration I am not able to reproduce too...
So according to my configuration I (difficultly...) found which directive fails with new mod_http2.

Here is:
- Keep <Location />Options +Indexes</Location> in server conf or in any vhost
- Add directive HeaderName /HEADER.html according to https://httpd.apache.org/docs/2.4/mod/mod_autoindex.html#headername
- Create HEADER.html in the Document root with or without any content 
- The issue appear for me, only with mod_http2 1.8.3

Can you reproduce?

**Comment by icing** [comment]
Thanks! Yes, I can reproduce the error now. Will add that too my tests and see what I can do...

**Comment by nono303** [comment]
Hi,
I've just build mod_h2 1.8.5-git with httpd 2.4.25 (MSVC15 RC x64) and all works fine ;)
Thank's a lot!!

**Comment by icing** [comment]
Thanks for letting me know!
