### ISSUE TITLE
h2 slave connection reuse does not work reliably

### ISSUE THREAD

**Issue by arminabf** [icing/mod_h2#128]
When doing some tests with the mod_http2 module I'd realized that slave connections (the "cloned" connections from the master connection, used by h2_task's) are mostly (not always) closed after a request - although connection re-use (keep-alive) should be called into action.

So far I observe following behaviour:

When the corresponding handler finishes, _ap_check_pipline()_ is called by _ap_process_request_after_handler()_. _ap_check_pipline()_  tries to read "blank lines" in AP_MODE_SPECULATIVE mode. This triggers the _h2_filter_slave_in()_ filter that in the majority of cases returns with APR_EOF.

Based on the return code _ap_check_pipeline()_ assumes that the pipe is dead and closes the connection.

<pre>
else if (rv != APR_SUCCESS || APR_BRIGADE_EMPTY(bb)) {
                if (rv != APR_SUCCESS && !APR_STATUS_IS_EAGAIN(rv)) {
                    /* Pipe is dead */
                    c->keepalive = AP_CONN_CLOSE;
                }   
</pre>

In the end, when the h2_task is destroyed (in _task_destroy()_) the slave connection is not set aside for connection reuse but is destroyed and the underlying socket gets closed.

<pre>
    if (slave) {
      if (reuse_slave && slave->keepalive == AP_CONN_KEEPALIVE) {
        APR_ARRAY_PUSH(m->spare_slaves, conn_rec *) = slave;
      } else {
        slave->sbh = NULL;
        h2_slave_destroy(slave);
      }    
    }
</pre>

As mentioned, sometimes a slave connection is reused...but very infrequently. 

The tests have been made with "mod_http2 (v1.8.3, feats=CHPRIO+SHA256+INVHD, nghttp2 1.18.1)" based on Apache httpd v2.4.25.

**Comment by icing** [comment]
Thanks! Very interesting observation and certainly something that needs fixing.

**Comment by icing** [comment]
Will be fixed in the upcoming v1.9.0.

**Comment by icing** [comment]
@arminabf can you verify that v1.9.0 works on your setup too? Thanks!

**Comment by arminabf** [comment]
yes works, thnx!!!
