### ISSUE TITLE
slave connection closed after MaxKeepAliveRequests

### ISSUE THREAD

**Issue by arminabf** [icing/mod_h2#131]
I've done performance tests with v1.9.0 and observed that slave connections are closed after a while - leading to the creation and destruction of new sockets all the time.

Studying the behavior it turned out that at some point ALL slave connection are marked as closed as the master connection (r->connection) reaches the maximum of allowed keep-alive requests (directive MaxKeepAliveRequests)

see http_protocol.c:ap_set_keepalive(), here https://github.com/apache/httpd/blob/2.4.25/modules/http/http_protocol.c#L220 and here
https://github.com/apache/httpd/blob/2.4.25/modules/http/http_protocol.c#L270

Seems that assigning the "number of keepalive requests" from the master connection
(https://github.com/icing/mod_h2/blob/v1.9.0/mod_http2/h2_mplx.c#L786) to the slave connections (https://github.com/icing/mod_h2/blob/v1.9.0/mod_http2/h2_task.c#L504) leads to that misbehavior.

**Comment by icing** [comment]
Thanks for your analysis. The keepalives are indeed not handled as it should. The settings should guide the amount of re-use a slave connection gets, IMO. That is not how this currently works.

Btw, there are no sockets created/destroyed for slave connections.

**Comment by arminabf** [comment]
> Btw, there are no sockets created/destroyed for slave connections.

Too sloppy, sorry! Right not in mod_http2. But when using a proxy module this leads to a new connection to back-end server whenever a new slave connection is used.

**Comment by arminabf** [comment]
hi! could it be that this one has been fixed? cannot reproduce the behavior with v1.10.0

**Comment by icing** [comment]
Yeah, I think ```MaxKeepAliveRequests```, as it was implemented before, did not work as it should - apart from the bugs.

Admins can set ```MaxKeepAliveRequests``` only once and it needs to work for both HTTP/1.1 and HTTP/2. In that sense, with other use patterns, it makes only sense to apply that to each slave connection uniquely. So, slave connection reuse would be discontinued when ```MaxKeepAliveRequests``` requests have been made over it.

Would you agree?

**Comment by arminabf** [comment]
> Would you agree?

Yes, definitely!

**Comment by icing** [comment]
Implemented in v1.10.2
