### ISSUE TITLE
spare slave connections problem

### ISSUE THREAD

**Issue by arminabf** [icing/mod_h2#132]
I think that the check https://github.com/icing/mod_h2/blob/master/mod_http2/h2_mplx.c#L332 unnecessarily leads to waste of slave connections as APR arrays are able to allocate new space if no more spots are available.

**Comment by icing** [comment]
This is intentional to limit the amount of spare slaves.

**Comment by arminabf** [comment]
By limiting to a fixed number? 

https://github.com/icing/mod_h2/blob/master/mod_http2/h2_mplx.c#L288

When stressing mod_http2 with lots of sessions (and streams) this number gets exhausted very quick.

**Comment by arminabf** [comment]
Seems to have improved with the latest releases.. thanks!

**Comment by icing** [comment]
You're welcome! Please keep on looking at and stressing my code and give me a gentle nudge when you see things that could be improved. ;-)
