### ISSUE TITLE
h2_mplx(16): release, waiting for 5 seconds now for 1 h2_workers to return, still 1 tasks outstanding.

### ISSUE THREAD

**Issue by djfordz** [icing/mod_h2#134]
Related to issue #108

Hello I have an issue on multiple servers running Apache 2.4 with http/2
Apache version: 2.4.23
Linux: 2.6.32-642.11.1.el6.x86_64
CentOS: CentOS release 6.8 (Final)
Magento 2: "version": "2.1.0"

release, waiting for 5 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
->03198: h2_stream(16-1): POST XXXXXXXXXXX /rest/default/V1/XXXXXXXXXXXXX/set-payment-information -> reset 8[orph=1/started=1/done=0]
 h2_mplx(16): release, waiting for 10 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
h2_mplx(16): release, waiting for 15 seconds now for 1 h2_workers to return, have still 1 tasks outstanding
 h2_mplx(16): release, waiting for 20 seconds now for 1 h2_workers to return, have still 1 tasks outstanding

Trying to get version of mod_h2 will post shortly.

We are seeing this with Magento 2 stores.

**Comment by icing** [comment]
@djfordz version would be interesting. There has been a heavy revamp of connection shutdown handling in v1.9.x. So, if you have the chance, take the recent version from here and compile/run it with Apache 2.4.25. It might also work in 2.4.23, but I have never tested that.

**Comment by djfordz** [comment]
@icing the h2 version we are running is 1.5.11 built-in.

So we need to upgrade h2 version?

**Comment by icing** [comment]
Yes. I think the version from here should also work in a 2.4.23 Apache httpd. As I said, have not tested that, but interfaces did not change as far as memory serves me well.

**Comment by djfordz** [comment]
great ty. I will see if we can get this implemented.  We run about 1500-2000+ servers so rolling it out is gonna take some time.

**Comment by djfordz** [comment]
The issue seems intermittent, but when it happens it does affect our customers. We will do some testing with the new version and let you know.

**Comment by djfordz** [comment]
The issue is intermittent but when it does happen it does affect our customers, we will do some testing with the new version, ty.
