### ISSUE TITLE
Missing LICENCE file in dist archive

### ISSUE THREAD

**Issue by uhliarik** [icing/mod_h2#136]
Hi,

I'm trying to create separate module mod_http2 package for Fedora, but I haven't found LICENCE file in your dist archive. Could you please create new dist version and provide it?

I'm downloading dist archive from here:
Version:    1.10.1
https://github.com/icing/mod_h2/releases/download/v1.10.0/mod_http2-%{version}.tar.gz

**Comment by icing** [comment]
Nice catch! I updated the tar ball at
https://github.com/icing/mod_h2/releases/tag/v1.10.1
to include the LICENSE file and it will also be in all future releases.

**Comment by uhliarik** [comment]
Thanks! :)
