### ISSUE TITLE
mod_proxy_http2:  X-Forwarded-For Header is not added

### ISSUE THREAD

**Issue by BenediktS** [icing/mod_h2#137]
The mod_proxy_http module adds 3 X-Headers  to the request.
(http://httpd.apache.org/docs/2.4/en/mod/mod_proxy.html#x-headers )
These headers are not added in the h2 module.

This is only needed if mod_proxy_http2 should be a 1to1 replacement for mod_proxy_http.

workaround:
Add  `RequestHeader append x-forwarded-for %{REMOTE_ADDR}s`   to the config file.

**Comment by icing** [comment]
Please test v1.10.4 - thanks!

**Comment by icing** [comment]
Closing due to lack of feedback on implementation.

**Comment by BenediktS** [comment]
Sorry. I wasn't logged in  in the last 4 weeks. 

I started to deploy v1.10.6 right now. 
Everything is fine.

**Comment by icing** [comment]
Thanks! Good to get confirmation.
