### ISSUE TITLE
AH03467: h2_task: unable to parse status line

### ISSUE THREAD

**Issue by xplode** [icing/mod_h2#138]
Configuration
apache: 2.4.25
openssl: 1.0.2j
nghttp2: 1.21.1
mod_http2: 1.10.1

I have a setup where the apache http2 server is acting as a reverse proxy using mod_proxy

I regularily see these errors in the apache log (one every 5 mins or so).
```
AH03467: h2_task: unable to parse status line: <!DOCTYPE html PUBLIC X XHTML Y Z A <html B xml:lang="en" lang="en" class="loading"> <head> <title>
AH03467: h2_task: unable to parse status line: \xff\xd8\xff\xe1
AH03467: h2_task: unable to parse status line: \x89PNG
AH03467: h2_task: unable to parse status line: \x1f\x8b\b
```
From what I can gather looking at the mod_http2 code, it seems that mod_http2 thinks that is parsing a serialized http/1.1 response but instead has html, gzipped data, a png file, or basically something that is not an http/1.1 response.

Could this be a state error in mod_http2?

It looks like a similar problem was reported in issue #133 however I am not using mod_proxy_http2.

**Comment by icing** [comment]
Interesting. Will have a closer check, but this looks like mod_http2 expects an interim response, like 100, but it there is still some data pending from a previous request. Hmm. 

It must be the same issue as #133. Interesting. Do you know more about the requests that trigger this? Can you give me an example on how mod_proxy is configured (no hostname or addresses, pls.)?

**Comment by icing** [comment]
Also, are these messages all from different task ids? `h2_task(nn-xx)`?

**Comment by icing** [comment]
Hmm, can it be that someone makes HEAD requests against a handler in the backend that sends the data as if it is a GET? That would leave the response body on the proxy connection. When that is re-used, mod_http2's interim response complains about it.

As it looks, the request will fail and mod_proxy will try it on a new connection. If that is true, the ERROR logging is too high level and DEBUG should be enough. 

Can we check if the backend implements HEAD requests correctly?

**Comment by icing** [comment]
Please check v1.10.5 if that works for you.

**Comment by xplode** [comment]
Thanks for the quick response Stefan.  I'll try to respond to the questions you asked above:

_Do you know more about the requests that trigger this?_ 
I don't know the exact requests that trigger this error yet.

_Can you give me an example on how mod_proxy is configured (no hostname or addresses, pls.)?_
Here is an example of the vhost configuration:
```
<VirtualHost *:443>
  ServerName www.example.com

  ####### inbound SSL setup #######
  SSLEngine on
  SSLCertificateFile "vhosts/example/ssl/server.crt"
  SSLCertificateKeyFile "vhosts/example/ssl/server.key"
  SSLCertificateChainFile "vhosts/example/server.int"
  ####### outbound SSL setup #######
  SSLProxyEngine on

  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript text/javascript text/x-js text/x-javascript
 ProxyPreserveHost On

  ####### load balancers ########
  <Proxy balancer://cluster_0_0>
    BalancerMember https://1.1.1.1:443 route=0 timeout=600 retry=0 connectiontimeout=60 loadfactor=1
    ProxySet lbmethod=bybusyness
  </Proxy>

  # ProxyPass configuration for path '/'.
  ProxyPass / balancer://cluster_0_0/
  ProxyPassReverse / balancer://cluster_0_0/

  RequestHeader set X-Forwarded-Proto https
  Protocols h2 http/1.1
</VirtualHost>
```

_Also, are these messages all from different task ids? h2_task(nn-xx)?_
Yes, here is a small block of errors:
```
[Fri May 05 01:08:50.744753 2017] [http2:error] [pid 25280:tid 140526283908864] [client 104.162.58.236:52819] AH03467: h2_task(1411-3): unable to parse status line: \x1f\x8b\b
[Fri May 05 01:13:11.102462 2017] [http2:error] [pid 31212:tid 140526300694272] [client 73.157.101.181:58159] AH03467: h2_task(1619-1): unable to parse status line: \xff\xd8\xff\xe0
[Fri May 05 01:16:12.424502 2017] [http2:error] [pid 31211:tid 140526065698560] [client 68.104.170.53:52162] AH03467: h2_task(1294-1): unable to parse status line: \x89PNG
[Fri May 05 01:16:36.718699 2017] [http2:error] [pid 31210:tid 140526149625600] [client 68.180.103.197:51480] AH03467: h2_task(458-7): unable to parse status line: \x89PNG
[Fri May 05 01:16:46.493899 2017] [http2:error] [pid 25580:tid 140526023735040] [client 172.58.84.242:62802] AH03467: h2_task(1046-13): unable to parse status line: \x1f\x8b\b
```

**Comment by xplode** [comment]
I'm working to identify the requests that cause this error.  I'll also investigate how the backend responds to HEAD requests to see if it is sending GET data for these.  I'll also check out v1.10.5

**Comment by icing** [comment]
@xplode anything came out of that? Otherwise, with the mitigation in place, I'd tend to close this issue.

**Comment by icing** [comment]
Closed due to to interest gone away.
