### ISSUE TITLE
App behind mod_proxy is only partially reachable

### ISSUE THREAD

**Issue by jfmcbrayer** [icing/mod_h2#14]
This is, unfortunately, another vague-ish bug report.

I have ownCloud running in a kvm-qemu VM. The host machine is running my main apache server, to which I've just added mod_h2. The VM's apache is proxied like this:
```
ProxyPass /owncloud http://192.168.122.135:80 max=20 ttl=120 retry=300
```

Most of the resources load, but for a few, I am getting a 502 Bad Gateway error.

The errors in the ssl_errors.log on the host machine look like
```
[Fri Apr 17 10:11:38.935081 2015] [proxy_http:error] [pid 17641:tid 140117117228800] (20014)Internal error: [client 74.254.77.254:9912] AH01102: error reading status line from remote server 192.168.122.135:80, referer: https://www.carcosa.net/owncloud
[Fri Apr 17 10:11:38.935120 2015] [proxy:error] [pid 17641:tid 140117117228800] [client 74.254.77.254:9912] AH00898: Error reading from remote server returned by /owncloud/3rdparty/js/chosen/chosen.jquery.min.js, referer: https://www.carcosa.net/owncloud
[Fri Apr 17 10:11:38.935175 2015] [proxy_http:error] [pid 17641:tid 140116915869440] (20014)Internal error: [client 74.254.77.254:9912] AH01102: error reading status line from remote server 192.168.122.135:80, referer: https://www.carcosa.net/owncloud
[Fri Apr 17 10:11:38.935260 2015] [proxy:error] [pid 17641:tid 140116915869440] [client 74.254.77.254:9912] AH00898: Error reading from remote server returned by /owncloud/apps/contacts/js/loader.js, referer: https://www.carcosa.net/owncloud
[Fri Apr 17 10:11:38.939905 2015] [proxy_http:error] [pid 17641:tid 140116941047552] (20014)Internal error: [client 74.254.77.254:9912] AH01102: error reading status line from remote server 192.168.122.135:80, referer: https://www.carcosa.net/owncloud
[Fri Apr 17 10:11:38.939933 2015] [proxy:error] [pid 17641:tid 140116941047552] [client 74.254.77.254:9912] AH00898: Error reading from remote server returned by /owncloud/apps/search_lucene/js/checker.js, referer: https://www.carcosa.net/owncloud
[Fri Apr 17 10:11:38.939982 2015] [proxy_http:error] [pid 17641:tid 140116974618368] (20014)Internal error: [client 74.254.77.254:9912] AH01102: error reading status line from remote server 192.168.122.135:80, referer: https://www.carcosa.net/owncloud
[Fri Apr 17 10:11:38.939993 2015] [proxy:error] [pid 17641:tid 140116974618368] [client 74.254.77.254:9912] AH00898: Error reading from remote server returned by /owncloud/apps/gallery/js/public.js, referer: https://www.carcosa.net/owncloud
[Fri Apr 17 10:17:32.131763 2015] [proxy_http:error] [pid 17641:tid 140118182512384] (20014)Internal error: [client 192.168.1.3:46120] AH01102: error reading status line from remote server 192.168.122.135:80
[Fri Apr 17 10:17:32.131808 2015] [proxy:error] [pid 17641:tid 140118182512384] [client 192.168.1.3:46120] AH00898: Error reading from remote server returned by /owncloud/remote.php/caldav/calendars/donathl/defaultcalendar_shared_by_jmcbray/

```

There are no errors in the error_log on the guest machine (the one behind the proxy), and the access_log on the guest machine is showing either 200 or 304 results for all of those requests.

After disabling mod_h2, things work normally.

Again, I'm sorry if this bug report is not very helpful. I think mod_h2 is a great thing and I'm really looking forward to being able to use it.

**Comment by jfmcbrayer** [comment]
This appears to be fixed as of 6b44c55b1001b567d2c05a430a769d515c8845af, probably thanks to the Host header fixes. It's still not possible to log in to this ownCloud site, but that's probably the same issue as #13.

**Comment by icing** [comment]
Thanks for the update. Yes, that would make sense.

In the meantime I installed rainloop and did some rework of the header conversions and input handling. The initial login problems appear for me now sometimes, most of the times the admin login works. It looks ok from my side, but I do not know what to expect of  rainloop. If you could give the current github master a try and report your experience, that’d be nice.

If you continue to have problems, could reproduce this with 
     LogLevel h2:trace1
and send the the error log? Thanks!

Cheers,

  Stefan


> Am 21.04.2015 um 17:03 schrieb jfmcbrayer <notifications@github.com>:
> 
> This appears to be fixed as of 6b44c55, probably thanks to the Host header fixes. It's still not possible to log in to this ownCloud site, but that's probably the same issue as #13.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

<green/>bytes GmbH
Hafenweg 16, 48155 Münster, Germany
Phone: +49 251 2807760. Amtsgericht Münster: HRB5782

**Comment by jfmcbrayer** [comment]
Unfortunately, I spoke too soon when I posted that update. The problem still exists with 6b44c55, sorry.

**Comment by icing** [comment]
I will not hold it against you…

I close shop for the day and will look at your reports tomorrow morning. (Europe Time)

//Stefan

> Am 21.04.2015 um 17:25 schrieb jfmcbrayer <notifications@github.com>:
> 
> Unfortunately, I spoke too soon when I posted that update. The problem still exists with 6b44c55, sorry.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

<green/>bytes GmbH
Hafenweg 16, 48155 Münster, Germany
Phone: +49 251 2807760. Amtsgericht Münster: HRB5782

**Comment by jfmcbrayer** [comment]
This bug is not affected by beb622311023dcb097c839d2d61e39a1c9de9878. I will try to post logs later.

**Comment by jfmcbrayer** [comment]
>If you continue to have problems, could reproduce this with LogLevel h2:trace1 and send the the error log? Thanks! 

Could you also give me a CustomLog line with the information you need?

**Comment by icing** [comment]
I am not too familiar with CustomLog configs. So far, I've relied on the default log formatting and capabilities. If you have any recommendations or pointers, I'd be interested.

Also, it might be worth testing this again with the current checkin, as the fixes on input handling in v0.5.2 where quite substantial. Thanks.

**Comment by jfmcbrayer** [comment]
I'm just trying to find where the logs from  "LogLevel h2:trace1" are going. Should they be in ssl_error_log?

Unfortunately, there is no change in the page loading behaviour with the latest checkin.

**Comment by icing** [comment]
And another round: v0.5.4 fixes a bug in output handling that showed on mod_proxy setups. It might help your problem as well. Please give it a try.

**Comment by jfmcbrayer** [comment]
OwnCloud behind mod_proxy appears to work now.

**Comment by icing** [comment]
Champagne!

If I hear nothing contrary, I'll close the issue tomorrow. Thanks!

**Comment by jfmcbrayer** [comment]
I'm really impressed with the speed of the progress this project is making. 

On April 29, 2015 10:59:06 AM EDT, Stefan Eissing <notifications@github.com> wrote:
>Champagne!
>
>If I hear nothing contrary, I'll close the issue tomorrow. Thanks!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/icing/mod_h2/issues/14#issuecomment-97456958

-- 
Jason McBrayer 
jmcbray@carcosa.net

**Comment by icing** [comment]
:-) Thanks, nice to hear that.
