### ISSUE TITLE
perf degradation after patch

### ISSUE THREAD

**Issue by tessus** [icing/mod_h2#145]
After applying https://github.com/icing/mod_h2/blob/master/patches/mod_h2-v1.10.10-apache-2.4.x.diff, I have the feeling that loading of pages is slower.

I do not have any numbers, since I would have to go back to the previous code. This is merely a subjective observation. I could easily be wrong.

Anyway, I just wanted to ask, if the patch might influence performance. You can close this issue right away, if you think I'm off.

**Comment by icing** [comment]
I *think* that it should not be the case. If you have data, I am willing to look into it - but otherwise I spend the time on other things... ;-)

**Comment by tessus** [comment]
Fair enough. But you already answered my question. Since you are the dev and know, whether you added additional mutexes or some other logic that could influence perf, I'm more than happy with "I think".

Cheers.
