### ISSUE TITLE
Indexing not working with HTTP2

### ISSUE THREAD

**Issue by doonze** [icing/mod_h2#150]
Debian 9.2
Apache 2.4.25

After enabling mod_http2 all my server indexing stopped working. 

Chrome simply says:

`The Site cannot be reached.`

Firefox is a bit more verbos:
`Secure Connection Failed 

The connection to home.xxxxxxx.net was interrupted while the page was loading. 

The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.`

I've since turned off h2 in just that virtual server that handles those indexes. While that's got it working, I still find this odd that no one else has ran into this. But Google and Apache Lounge doesn't have any other reports of this. 

Logs are 100% clean during these events. Any ideas? Is this a bug or something weird on just my system?

**Comment by doonze** [comment]
Yes, it's reachable. Had to take off the "-" on s_client, but it all came back good. I am having issues with some of my reversed proxy port services too. Maybe because my 2.4.25 doesn't have mod_proxy_http2???

Most of my straight up served pages seem to run h2 fine, it seems hit and miss on my revere proxy setups. For grins I'll list what's working and what's not. Just in case anyone else has issues. 

Working fine http2 (verified using H2 in chrome F12/Network/protocols):

Emby (reverse proxy, login page is kinda slow, but once logged in response is fast)
Plex (reverse proxy, same, login is very slow, but once logged in it's responsive)
My personal php website (aside from indexes)
Extplorer
Server Monitor
Transmission (reverse proxy)
Sabnzbd (reverse proxy)
Jackett (reverse proxy)
glances (reverse proxy)
Nextcloud
phpmyadmin
cryptoglance

NOT WORKING, but works fine with H2 turned off under protocols:

Indexing using apache, fine with http1.1, won't load at all h2
Sonarr (reverse proxy, logs in, but many menus take up to 60 seconds to load. http1.1 is instant)
Couchpotato (reverse proxy, logs in fine, loading of content either hung or very very slow)
Shell in a box (reverse proxy, keystrokes take 60~ to reflect , times out)

So aside from indexing, all other issues I've been having are with reverse proxies. It may be something with the RP's, or my server itself. Not sure. 

Is no one else reporting indexing issues with apache under h2? The only thing "special" I'm doing is I have custom headers and CSS for my indexes. They are embedded in my site. But even accessing the path directly outside the embedding leads to failure to load.

**Comment by icing** [comment]
Please explain your setup in more detail. You reverse proxy using what against a remove server using what? Which Apache modules are in play?

**Comment by doonze** [comment]
After I left my last post, I started thinking about my comment that the only "special" thing I was doing was custom headers and CSS. So I disabled my header, and indexing started working again! 

Interesting thing, I ended up modifying my header to EXACTLY match the default header apache issues. Verified in DEV on Chrome. EXACT SAME HTML showing each way with http1.1. But h2 would never work if I had custom header file enabled. Just says can't connect to server. Seems is something apache itself is doing differently when it issues it's default header vs. a custom header. http1.1 doesn't care, but h2 seems to. 

Nothing ever appeared in the logs. As far as I could tell, with h2 enabled the browser was never able to even connect to the server h2 with customer header enabled. 

As for my reverse proxy setups, I use the RP to mask port services behind regular html paths. And also so I can use my main servers SSL cert for everything. 

The RP allows me to do HTTPS://emby.xxxxxxx.net/emby to reach that port service instead of having to use http://emby.xxxxxx.net:8963 or the like. And I don't have to have any open ports in my router. 

So I RP to mask ports for port driven services, and for me to use one SSL cert for many different services.

My config is close to same for all my services, both the working ones and the non-working ones. It looks like this:

`<VirtualHost *:443>
    SSLEngine On
    SSLProtocol all -SSLv2 -SSLv3
    SSLCertificateFile /etc/letsencrypt/live/sabnzbd.xxxxxxx.net/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/sabnzbd.xxxxxxx.net/privkey.pem

     ServerAdmin admin@xxxxxx.net
     ServerName sabnzbd.xxxxxxx.net
     DocumentRoot /var/www/html/
     Protocols h2 http/1.1
     LogLevel warn
     ServerSignature Off

    ProxyRequests off
    ProxyPreserveHost on
    SSLProxyEngine on

    <Directory /var/www/html/>

        RewriteEngine on
        redirect / /sabnzbd/

   </Directory>

   <Location /sabnzbd>
     order deny,allow
     deny from all
     allow from all
     ProxyPass http://localhost:8086/sabnzbd/
     ProxyPassReverse http://localhost:8086/sabnzbd/
   </Location>
</VirtualHost>`

That one is working, the others that are not are similar. I have yet to find anything special about the ones that are not working. My guess it's something in the way they wrote the code that isn't h2 compliant.

**Comment by bazzadp** [comment]
@doonze

HTTP/2 is a lot stricter about malformed headers. HTTP/1.1 was a lot more forgiving.

This post details how Chrome will give a protocol error if you try to send an invalid header under HTTP/2: https://www.michalspacek.com/chrome-err_spdy_protocol_error-and-an-invalid-http-header.

So check your header does not have spaces or colons in the header name, or doesn’t close quotes when it should. The above blog post also tells you how to debug it in Chrome to find the bad header.

Hopes that helps for your first issue, but can’t really help with your reverse proxy issue though.

**Comment by icing** [comment]
@bazzadp thanks for the explanation!

**Comment by doonze** [comment]
Yes thanks! 

Over on Apache Lounge they linked me to this here:

[https://github.com/icing/mod_h2/issues/126](url)

and that was exactly my issue. Maybe the Debian 9 version is older than the version this was fixed in?

I'm not too worried at this point about my reverse proxies. I'll deal with that later, I just turned on h2 to play with it. My sites aren't complicated enough that there is any speed difference for me. And since I'm the only one using them, meh.... That will be for another day. Thanks for all the help!!!

**Comment by icing** [comment]
If you set

```
LogLevel http2:info
```

the version of the module should be logged at startup.

**Comment by JialuZhang** [comment]
@doonze 
In this configuration,
```
  <Directory /var/www/html/>
      RewriteEngine on
      redirect / /sabnzbd/
 </Directory>
```
the line "RewriteEngine On“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".
That is to say, unless you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then leaving off "RewriteEngine" is a better choice.

More importantly, the default value of “RewriteEngine" is already an "off", so from a security side, deleting “RewriteEngine On” would be ideal.

The related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
