### ISSUE TITLE
Missing cookie data in push pages

### ISSUE THREAD

**Issue by sascha-hendel** [icing/mod_h2#152]
If I push PHP pages (as document) there will be no cookie data in PHP.
I use session cookies and the pushed resources rely on the session cookie of the main originating document. Don't know, if this is a real bug or an intended thing...

**Comment by icing** [comment]
That is correct and intended. Only a small subset of the original resource request header are copied over to the PUSH promise. The common use case is to only offer resources that way that do not ```Vary``` on cookies or other things.

If you need some client identification and PUSH here, my advise would be toI generate unique URLs for those resources. But I do not know your application, so feel free to ignore this. ;-)

**Comment by sascha-hendel** [comment]
Ok, I can attach the session ID as query string to the URL. But I think it would be still useful to offer resources with PUSH, that vary on cookies. I don't understand, why this is not intended.
Of course, it's more complicated for the server to overlook, which files are already pushed to a client with Vary on cookies, but this is a technical problem, that could be solved...

**Comment by icing** [comment]
I think it's a bit more complicated. AFAIK, the server would need to understand if a cookie on the original resource really applies to the resources being pushed, e.g. if the domain and path and all such really match. It would need to do that with the same logic that browsers apply to it and that is not straight-forward.

And that all implies that browser actually can handle a cookie header on PUSH PROMISEs. They have a special cache for pushed resources, so their usual cache handling does not really apply. And you'd need that for the PUSH to really have an effect.

Perhaps you should raise the question on the http working group mailing list to hear people's opinion.

**Comment by sascha-hendel** [comment]
Thought, that the missing cookie-information was an implementation specific issue of the Apache mod. But if I understand You right, this behaviour is intended by the underlying http/2 specifications.
Maybe this should be noted in the Apache http2_mod docs.

**Comment by icing** [comment]
I added explanation of headers and cookies in PUSH on the Apache http2 documentation. Will show up in trunk soon and then backported to the next 2.4.x release.
