### ISSUE TITLE
Weirdness with http2-status and mod_brotli

### ISSUE THREAD

**Issue by bazzadp** [icing/mod_h2#153]
Had some problems tryign to use the http2-status page and eventually figured out it was due to some incompatibility with mod_brotli.

I enabled http-status:

    <Location "/http2-status">
       SetHandler http2-status
    </Location>

I also have mod_brotli enabled with the following config:

        AddOutputFilterByType BROTLI_COMPRESS text/html text/plain text/xml text/css text/javascript application/x-javascript application/javascript application/json application/x-font-ttf

With this set up, the http2-status page will not load in Chrome:

> ERR_CONTENT_DECODING_FAILED error

nor Firefox

> Content Encoding Error
> 
> The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression.
> 
>     Please contact the web site owners to inform them of this problem.

I do see a response in Chrome Developer tools (as long as I use preserve logs), and checking out the HTTP-Headers it looks like the following:

```
conn-flow-in:2147483647
conn-flow-out:15727607
content-encoding:br
content-type:application/json
date:Mon, 28 Jan 2018 23:12:40 GMT
server:Apache
status:200
vary:Accept-Encoding,User-Agent
```

Note the weird conn-flow-in and conn-flow-out headers which I don't normally see, and also that content-encoding is set to br for Brotli compression.

If I save the status to a local file (test.json) and look at that it works fine, and it is delivered as a brotli compressed file (without the conn-flow-in and -out headers) so obviously the output can be compressed fine:

```
accept-ranges:bytes
content-encoding:br
content-length:406
content-type:application/json; charset=utf-8
date:Mon, 28 Jan 2018 23:50:36 GMT
last-modified:Sun, 28 Jan 2018 23:50:03 GMT
server:Apache
status:200
vary:Accept-Encoding,User-Agent
```

However, if I remove application/json from the AddOutputFilterByType config, so it is **not** Brotli compressed, then the http2-status page works fine, and no content-encoding is returned (though those conn-flow-XX headers are still returned):

```
conn-flow-in:2147483647
conn-flow-out:15728640
content-type:application/json
date:Mon, 28 Jan 2018 23:54:04 GMT
server:Apache
status:200
vary:User-Agent
```

Weirdly I also have mod_deflate installed with the exact same setup, but even with mod_brotli turned off completely, the http2-status page is returned fine, but it is **not** returned with gzip content-encoding (like all other resources with the appropriate AddOutputFilterByType are when mod_brotli is not enabled).

Why is http2-status treated differently by mod_brotli (by trying to compress it, and screwing that up somehow) than by mod_deflate (where it doesn't even try to compress it and so doesn't screw it up)?

There isn't much in the debug logs (even up to trace7):

    [Mon Jan 28 23:36:07.327294 2018] [http2:trace3] [pid 1410:tid 140255318566656] h2_h2.c(722): [client 78.16.8.4:57014] h2_task(144-1): adding request filters
    [Mon Jan 28 23:36:07.334034 2018] [http2:trace2] [pid 1410:tid 140255318566656] h2_filter.c(535): [client 78.16.8.4:57014] status_handler(144-1): checking for incoming trailers

But the same appears even with mod_brotli disabled, where the status page works.

Not a massive deal, but it's a bit odd so I thought I'd log it.

Thanks,
Barry

**Comment by icing** [comment]
@bazzadp interesting. I can guess what is going wrong here. The http2-status is a one-of-a-kind beast that has some special output handling. And that needs to remove the ```content-encoding``` header. Will write a test and fix...

**Comment by bazzadp** [comment]
Thanks @icing. Weird that it only affects br and not gzip.

**Comment by icing** [comment]
Please try v1.10.15.

**Comment by bazzadp** [comment]
Looks good. Thanks for the quick response.
