### ISSUE TITLE
No push on mod_proxy_http2?

### ISSUE THREAD

**Issue by bazzadp** [icing/mod_h2#154]
Was experimenting with mod_proxy_http2 and discovered that Push is disabled for this.

This is in both h2 and h2c proxy mode. Running a simple ngttpd server, and then proxying a request to that shows the incoming SETTINGS frame has SETTINGS_ENABLE_PUSH set to 0.

```
$ nghttpd -v --no-tls 8080
IPv4: listen 0.0.0.0:8080
IPv6: listen :::8080
[id=1] [ 54.550] send SETTINGS frame <length=6, flags=0x00, stream_id=0>
          (niv=1)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
[id=1] [ 54.550] recv SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_ENABLE_PUSH(0x02):0]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):32767]
```

Is there a way of changing this? Or is it just that you haven't got round to coding that yet?

I would have thought one of the main use cases for proxying to a back end with HTTP/2 rather than HTTP/1.1 was to enable end to end push (though appreciate it can also be done by the back end setting link headers and mod_http2 reading these and then managing the push itself).

**Comment by icing** [comment]
The preferred way is that the backend server announces such resources via [103 Early Hints](https://datatracker.ietf.org/doc/rfc8297/) intermediate responses or, oldskool, ```Link``` headers.

PUSH is not enabled on the backend connections, because those connections are re-used between different front-end connections. And not all of those have PUSH enabled. Additionally, the Cache Digest that ```mod_http2``` maintains, e.g. "what I have already pushed on this connection", is not visible to the backend.

103 is a much superior way to announce PUSH resources to intermediates (and there is discussion if it is not superior for the browser as well).

Hope this explains things.

Tip: 103 responses are disabled in ```mod_http2``` by default as early versions of some browsers did choke on it. Nowadays, that is no longer a problem. Use ```H2EarlyHints on``` to enable it.

**Comment by bazzadp** [comment]
Fair enough now that 103 is standardised (though support isn't great yet).

Does seem a little weird that the back end application server has to tell the front end web server to push a resource it might own, rather than push it directly itself. However, in other ways (for the reasons you have noted as well as other reasons) it is cleaner to do it this way, so can understand the reasoning.

Anyway, I think it's worth noting this restriction in the `mod_proxy_http2` documentation in case anyone else tries to use this specifically for end-to-end Push.

I'd also question the benefit of `mod_proxy_http2` and speaking HTTP/2 all the way through given this. Can't really see any benefit over HTTP/1.1 for back end connections for now to be honest, and plenty of downsides since support is a bit tricky at the moment. Since latency and bandwidth is typically less of a problems for these types of connections, end-to-end Push was the main thing I thought it would be useful for but even HTTP/1.1 can send 103 responses can't it? Maybe this will change in future as HTTP/2 becomes more widely supported and there is no reason not to use HTTP/2 on the back end but, for now, it seems of limited use. Though I do like that Apache is one of the few implementations that allow this, for anyone that does want to use it :-)

And just to clarify your final tip, I presume you mean 103 responses from back end systems are always processed by mod_http2 (to enable the Push) but, by default are then dropped rather than forwarding on to the client? So no matter what the setting of `H2EarlyHints` 103 can always be used for Push from the back end - is that correct? That's been my observation so far anyway.

**Comment by icing** [comment]
Yes, 103 is always processed, but only send when enabled.

As to h2 on the backend: I agree to your reasoning. Latency and Bandwidth are often not an issue and h1 implementation is still more reliable. Notice that ```mod_proxy_http2``` kept its 'experimental' status in httpd while ```mod_http2``` has left it behind.

**Comment by bazzadp** [comment]
Thanks for clarifying all this.

Happy to close this then - unless you want to consider my point about updating the documentation for `mod_proxy_http2` and close it then?

**Comment by icing** [comment]
Leave this open, pls.

**Comment by icing** [comment]
Added a section to the ```mod_proxy_http2``` documentation in trunk.
