### ISSUE TITLE
H2PushResource lacks "as" parameter for Link

### ISSUE THREAD

**Issue by tlechauve** [icing/mod_h2#162]
Hi,

Is there a way to tell to H2PushResource to add the "as" parameter to the header Link of the request ?

Currently it's more efficient to manually add Link header to the response. Using H2PushResource (so without "as") force the browser to download twice the resource.

Bye.

**Comment by icing** [comment]
Currently, there is no way to do that. Seems like a good addition to the config.

**Comment by tlechauve** [comment]
Hi,

@bazzadp you are right, i forgot to remove a duplicated link, my bad.

BUT, pushing with H2PushResource is still less efficient than directly adding a Link Header. I suppose it's due to the lack of "as" parameter.
I've done some performance audits using chrome and it seems that without this "as" parameter, the browser do not render immediately after reading pushed stylesheets. See screenshots for example:

I'm trying to get the best results for critical rendering path

with: Link Header ![](https://framapic.org/rJrHZeoJHzCd/SLC4QApn9Fiv)

with: H2PushResource ![](https://framapic.org/1K4PnQd9jrrg/7TGwyUTp7QFr)

**Comment by bazzadp** [comment]
@tlechauve I don't know if I would be as quick to close the issue. Technically, there should be no need for the as link, as I stated, but if browsers are handling the response differently based on this attribute then perhaps there is a case to add this.

There is no downside to having it (other than the work to implement it) and it could avoid confusion, so I would actually be in favour of your proposal. Apologies if my comment made it sound like I wasn't, I just was clarifying the technical side of this.

Saying that, can you confirm if the resource is definitely being pushed in both instances? Does it show as Pushed in the Network Tab->Initiator column? I've seen many instances were push is ignored, especially in development environments, as a self-signed certificate is used and so the domain is "untrusted" and the cache is therefore not used. In this case the `as` attribute might cause the resource still to be preloaded, whereas without it is not preloaded (another reason to support this change). So perhaps push is not being used in either case? It's kind of difficult to see from your screenshots.

Ultimately H2PushResource should be faster (http://icing.github.io/mod_h2/earlier.html) though it served from local disk the difference will be negligible.

**Comment by icing** [comment]
Re-opening for future implementation of the feature. Seems easy to do.

**Comment by tunetheweb** [comment]
[HTTP/2 push has been turned off in Chrome](https://developer.chrome.com/blog/removing-push/).

However 103 Early Hints is being pushed (pun totally intended!!) as a replacement. This doesn't actually send the resource, but instead sends the preload hint. The browser then makes a request if it wants.

This means that having the right `as` attribute is actually more important - so the browser can [use all these things](https://www.smashingmagazine.com/2016/02/preload-what-is-it-good-for/#how-can-preload-do-better) for the subsequent request, whereas it wasn't as important for the Push case.

**Comment by icing** [comment]
Coming back to this after some time, I made #252 where you can configure headers to be added in a 103 response. What you put in there is totally up to the config writers and they may follow the web innovations as closely as they like.

**Comment by tunetheweb** [comment]
Great news! Thanks @icing !

**Comment by icing** [comment]
Merged #252.
