### ISSUE TITLE
Version httpd/branches 1.10.20 differs from 1.10.20 Git here

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_h2#163]
Noticed today  difference between httpd/branches/2.4  and 1.10.20-git:

Both has a version number 1.10.20, the diff files are :
.\h2_config.c
.\h2_config.h
.\h2_conn.c
.\h2_filter.c
.\h2_h2.c
.\mod_http2.c
.\mod_http2.h
.\mod_proxy_http2.c

Do we miss changes in branches/2.4 ?

**Comment by icing** [comment]
No, some changes have been made in branches/2.4.x that have not arrived here yet.
