### ISSUE TITLE
autopoo/libtool

### ISSUE THREAD

**Issue by odeneriksson** [icing/mod_h2#168]
Hi,

I noticed a small problem with the generated binary modules that stems from not passing "avoid-version" in the Makefile to libtool. This patch corrects the behaviour with preferred unversified soname for apache modules.

--- mod_http2/Makefile.am       2018-08-06 16:29:39.000000000 +0200
+++ mod_http2/Makefile.am.oden  2018-09-11 07:53:49.045404581 +0200
@@ -20,10 +20,10 @@ AUTOMAKE_OPTIONS = foreign
 lib_LTLIBRARIES    = mod_http2.la mod_proxy_http2.la
 
 mod_http2_la_CPPFLAGS = -std=c99 -D_GNU_SOURCE -Werror @WERROR_CFLAGS@
-mod_http2_la_LDFLAGS  =  -module -export-symbols-regex http2_module
+mod_http2_la_LDFLAGS  =  -module -avoid-version -export-symbols-regex http2_module
 
 mod_proxy_http2_la_CPPFLAGS = -std=c99 -D_GNU_SOURCE -Werror @WERROR_CFLAGS@
-mod_proxy_http2_la_LDFLAGS  = -module -export-symbols-regex proxy_http2_module
+mod_proxy_http2_la_LDFLAGS  = -module -avoid-version -export-symbols-regex proxy_http2_module
 
 OBJECTS = \
     h2_alt_svc.c \

**Comment by icing** [comment]
Thanks! Added in the last commit.
