### ISSUE TITLE
mod_h2 breaks downloads over ~10kb

### ISSUE THREAD

**Issue by B00mX0r** [icing/mod_h2#17]
When downloading a file over somewhere around 10KB over mod_h2, the file becomes corrupt. It's not recognized as valid by apps that open it, and in Chrome, it actually adds "-, attachment" to the end of the file name. For example, "data.xlsx" turns into "data.xlsx-, attachment". The file is, again, corrupted after renaming it. I'm not sure if this is a mod_h2 issue or an nghttp2 issue. No errors are reported in any log files.

**Comment by icing** [comment]
I have testcases in my sandbox that make and check downloads of various sizes. So, I am interested to learn what setup you have. Also, could you attach the original and the downloaded file to the ticket? Thanks!

> Am 28.04.2015 um 07:50 schrieb B00mX0r <notifications@github.com>:
> 
> When downloading a file over somewhere around 10KB over mod_h2, the file becomes corrupt. It's not recognized as valid by apps that open it, and in Chrome, it actually adds "-, attachment" to the end of the file name. For example, "data.xlsx" turns into "data.xlsx-, attachment". The file is, again, corrupted after renaming it. I'm not sure if this is a mod_h2 issue or an nghttp2 issue. No errors are reported in any log files.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

<green/>bytes GmbH
Hafenweg 16, 48155 Münster, Germany
Phone: +49 251 2807760. Amtsgericht Münster: HRB5782

**Comment by B00mX0r** [comment]
In that case, it must be related to the fact that I'm sending the download via PHP. 

header("Content-Length: ".strBytes($File));
header('Content-Disposition: attachment; filename="'.$Name.'"');
header('Content-Type: application/octet-stream; charset=UTF-8');
echo($File);

I've tried changing the content-type, charset, file name, disposition, removing the length, etc. to no avail. However, when I make it echo the file binary on to the browser rather than a download, I see that the file isn't corrupted. So it's when it sends it as a download that this issue occurs. I can't send you the specific file, because it's happening for me on every file over ~10kb. Also, if it's helpful, the corruption seems to occur with the beginning of the file. I can see that the end's still intact.

**Comment by icing** [comment]
Thanks for the description. Still, seeing a corrupted file might help me determine the cause of the problem.

**Comment by icing** [comment]
Could you give v0.5.4 a try? I fixed a bug in output handling that might affect your case.

**Comment by B00mX0r** [comment]
I no longer see the issue on v0.5.4. Thanks for fixing this!
