### ISSUE TITLE
Undefined symbol: h2_proxy_fifo_push on custom built Apache

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [icing/mod_h2#171]
After installation Apache threw this error. ```Cannot load modules/mod_proxy_http2.so into server: /www/server/apache/modules/mod_proxy_http2.so: undefined symbol: h2_proxy_fifo_push```. I don't know it happens because my Apache is custom built or something else. 

## System info
OS: CentOS 7.5
Apache's Build command: 
```
./configure \
    --prefix=${Setup_Path} \
    --enable-mods-shared=most \
    --enable-headers \
    --enable-mime-magic \
    --enable-proxy \
    --enable-so \
    --enable-rewrite \
    --with-ssl=/usr/local/openssl \
    --with-nghttp2=/usr/local/nghttp2 \
    --enable-ssl \
    --enable-deflate \
    --with-pcre \
    --with-included-apr \
    --with-apr-util \
    --enable-mpms-shared=all \
    --with-mpm=prefork \
    --enable-remoteip\
    --enable-http2
    --enable-mod_proxy_http2
```

**Comment by icing** [comment]
Can you build the module from here? Otherwise, I'd refer you to your next CentOS representative...

**Comment by Aster-the-Med-Stu** [comment]
@icing Building this module was OK. It was built with nghttp2 1.34. There was some header files missing so I directly downloaded them from this repo and threw at ```/usr/local/include```. I'll try to build it on an Ubuntu machine to see if this is only a Centos-related bug.

**Comment by Aster-the-Med-Stu** [comment]
@icing On a **brand-new** Vultr Ubuntu instance with **custom-built** Apache I can confirm that this error is reproduceable. How could I offer more useful information? I am not a programmer but still hope that I can help.

**Comment by Aster-the-Med-Stu** [comment]
Okay figure it out. If I install nghttp2 under /usr/local/nghttp it would be impossible to successfully compile, so I just installed it under /usr/local and everything is fine.
