### ISSUE TITLE
Will mod_h2 work with Apache 2.4.12 on RHEL 6

### ISSUE THREAD

**Issue by headcracker** [icing/mod_h2#18]

**Comment by icing** [comment]
mod_h2 requires a locally installed nghttp2 library and, if using httpd 2.4.12, a patched mod_ssl. Patch is supplied inside the repository. It is expected that apache 2.4.13 has the patch already included.

As to detailed instructions for specific Linux distros, I am not able to provide those. But am more than willing to include such instructions from pull requests.
