### ISSUE TITLE
[Proposal] Rewrite test suite in Python 3.x

### ISSUE THREAD

**Issue by mnalband** [icing/mod_h2#183]
First of all, thanks for your work on this package and especially on building testing framework in python. 
I want to put it up for discussion. Python 3 was released in December 2008. A lot of time has passed since. Sure, Python 3 has some incompatibilities with Python 2 and some people need to rely on backwards-compatibility. But hasn't Python 3 been around long enough now for most projects to switch with Python 3? As I said, this is just a proposal. If you don't consider a rewrite in python-3.x, simply close this issue :-) Thanks!

**Comment by icing** [comment]
Please have a look at [commit 44996be589a624b1b7a2571833898787cde5393d](https://github.com/icing/mod_h2/commit/44996be589a624b1b7a2571833898787cde5393d) where I switched the test suite. If you feel anything missing, please let me know.
