### ISSUE TITLE
Python test suite uses subprocess.run compatible with 3.7 only

### ISSUE THREAD

**Issue by elukey** [icing/mod_h2#185]
Hi!

I am running some Docker tests and if the OS does not offer Python 3.7, I get the following:

```
E       TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

I think that the issue is related to the subprocess.run's capture_output parameter, that is available only in Python 3.7. As far as I gathered if we switch to `stdout=PIPE, stderr=PIPE` instead we should be able to run it on older versions of Python 3 without any issue.

Would it be possible to change it? :)

**Comment by icing** [comment]
Sure, it just needs someone to write the Pull Request! ;-)

**Comment by elukey** [comment]
Got some interesting failures with the current suite on Debian Buster:

* test_003_get.py

```
self = <test_003_get.TestStore object at 0x7fe3a50bf0b8>

    def test_003_01(self):
        url = TestEnv.mkurl("https", "cgi", "/hello.py")
        r = TestEnv.curl_get(url, 5)
        assert 200 == r["response"]["status"]
        assert "HTTP/2.0" == r["response"]["json"]["protocol"]
        assert "on" == r["response"]["json"]["https"]
>       assert "TLSv1.2" == r["response"]["json"]["ssl_protocol"]
E       AssertionError: assert 'TLSv1.2' == 'TLSv1.3'
E         - TLSv1.2
E         ?       ^
E         + TLSv1.3
E         ?       ^

* test_003_get.py:41: AssertionError

```
    def test_101_11(self):
        url = TestEnv.mkurl("https", "ssl", "/renegotiate/err-doc-cipher")
        r = TestEnv.curl_get( url, options=[ "-vvv" ] )
>       assert 0 != r["rv"]
E       assert 0 != 0

test_101_ssl_reneg.py:141: AssertionError
```

Buster ships with openssl 1.1, is it supported by the current tests?

**Comment by elukey** [comment]
I am also seeing the following:

```
TestEnv.py:34: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
```

**Comment by elukey** [comment]
About the failures in test_003:

https://github.com/icing/mod_h2/blob/master/test/e2e/test_003_get.py#L35-L51

I think that curl, even if running with `--tls1.2`, will try to connect using tls1.3 where available (like on Debian 10, that ships openssl1.1). Would it be ok to test either that either 1.2 or 1.3 is returned? (rather than only 1.2)

**Comment by elukey** [comment]
Anyway, going to close this issue and send other pull requests :)
