### ISSUE TITLE
mod_h2 kills SSL environment variables

### ISSUE THREAD

**Issue by hotaru2k3** [icing/mod_h2#19]
mod_ssl sets a number of useful environment variables.
when an http 2 connection is negotiated with mod_h2, those variables are not set.

**Comment by icing** [comment]
Well, there is nothing killed. Each http2 request gets a pseudo connection which does not have the same env as the main one. But maybe should. 

I'll look into it.

**Comment by icing** [comment]
Can you check if v0.5.6 solves the problem in your case as well? Thanks!

**Comment by hotaru2k3** [comment]
looks like it does! thanks!
