### ISSUE TITLE
update to apache 2.4.43 fails http/2 connections

### ISSUE THREAD

**Issue by mokraemer** [icing/mod_h2#196]
it seems there is a change in connection handling between 2.4.41 and 2.4.43. The connection is closed to early. The browser states connection was closed. Not sure why and when this happens. It is reproduceable but does not happen on all requests. Here is some log:

`Access-Log for request:

192.168.178.45 - - [16/Apr/2020:17:08:57 +0200] "POST /path/index.php HTTP/2.0" 401 - "https://server.de/path/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"

Debug-Log:

[Thu Apr 16 17:08:57.649445 2020] [ssl:info] [pid 6530:tid 139865408665344] [client 192.168.178.45:33462] AH01964: Connection to child 64 established (server server.de:443)
[Thu Apr 16 17:08:57.650108 2020] [ssl:debug] [pid 6530:tid 139865408665344] ssl_engine_kernel.c(2351): [client 192.168.178.45:33462] AH02043: SSL virtual host for servername server.de found
[Thu Apr 16 17:08:57.650446 2020] [core:debug] [pid 6530:tid 139865408665344] protocol.c(2313): [client 192.168.178.45:33462] AH03155: select protocol from h2,http/1.1, choices=h2,http/1.1 for server server.de
[Thu Apr 16 17:08:57.650813 2020] [core:debug] [pid 6530:tid 139865408665344] protocol.c(2357): [client 192.168.178.45:33462] AH03156: select protocol, proposals=h2,http/1.1 preferences=h2,http/1.1 configured=h2,http/1.1
[Thu Apr 16 17:08:57.650861 2020] [core:debug] [pid 6530:tid 139865408665344] protocol.c(2377): [client 192.168.178.45:33462] AH03157: selected protocol=h2
[Thu Apr 16 17:08:57.653750 2020] [ssl:debug] [pid 6530:tid 139865408665344] ssl_engine_kernel.c(2231): [client 192.168.178.45:33462] AH02041: Protocol: TLSv1.3, Cipher: TLS_AES_128_GCM_SHA256 (128/128 bits)
[Thu Apr 16 17:08:57.654083 2020] [socache_shmcb:debug] [pid 6530:tid 139865408665344] mod_socache_shmcb.c(493): AH00831: socache_shmcb_store (0xd2 -> subcache 18)
[Thu Apr 16 17:08:57.654144 2020] [socache_shmcb:debug] [pid 6530:tid 139865408665344] mod_socache_shmcb.c(847): AH00847: insert happened at idx=0, data=(0:32)
[Thu Apr 16 17:08:57.654159 2020] [socache_shmcb:debug] [pid 6530:tid 139865408665344] mod_socache_shmcb.c(850): AH00848: finished insert, subcache: idx_pos/idx_used=0/1, data_pos/data_used=0/200
[Thu Apr 16 17:08:57.654198 2020] [socache_shmcb:debug] [pid 6530:tid 139865408665344] mod_socache_shmcb.c(515): AH00834: leaving socache_shmcb_store successfully
[Thu Apr 16 17:08:57.654356 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(948): [client 192.168.178.45:33462] AH03200: h2_session(64,INIT,0): created, max_streams=100, stream_mem=32768, workers_limit=6, workers_max=37, push_diary(type=1,N=256)
[Thu Apr 16 17:08:57.654452 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(1037): [client 192.168.178.45:33462] AH03201: h2_session(64,INIT,0): start, INITIAL_WINDOW_SIZE=65535, MAX_CONCURRENT_STREAMS=100
[Thu Apr 16 17:08:57.654474 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(2130): [client 192.168.178.45:33462] AH03079: h2_session(64,INIT,0): started on server.de:443
[Thu Apr 16 17:08:57.654487 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(1694): [client 192.168.178.45:33462] AH03078: h2_session(64,BUSY,0): transit [INIT] -- init --> [BUSY]
[Thu Apr 16 17:08:57.654568 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(589): [client 192.168.178.45:33462] AH03068: h2_session(64,BUSY,0): sent FRAME[SETTINGS[length=6, stream=0]], frames=0/1 (r/s)
[Thu Apr 16 17:08:57.654670 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(589): [client 192.168.178.45:33462] AH03068: h2_session(64,BUSY,0): sent FRAME[WINDOW_UPDATE[stream=0, incr=2147418112]], frames=0/2 (r/s)
[Thu Apr 16 17:08:57.654764 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(1694): [client 192.168.178.45:33462] AH03078: h2_session(64,IDLE,0): transit [BUSY] -- no io (keepalive) --> [IDLE]
[Thu Apr 16 17:08:57.661056 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(337): [client 192.168.178.45:33462] AH03066: h2_session(64,IDLE,0): recv FRAME[SETTINGS[length=18, stream=0]], frames=0/2 (r/s)
[Thu Apr 16 17:08:57.661139 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(337): [client 192.168.178.45:33462] AH03066: h2_session(64,IDLE,0): recv FRAME[WINDOW_UPDATE[stream=0, incr=12517377]], frames=1/2 (r/s)
[Thu Apr 16 17:08:57.661160 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(1694): [client 192.168.178.45:33462] AH03078: h2_session(64,BUSY,0): transit [IDLE] -- frame received --> [BUSY]
[Thu Apr 16 17:08:57.661181 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(337): [client 192.168.178.45:33462] AH03066: h2_session(64,BUSY,0): recv FRAME[PRIORITY[length=5, flags=0, stream=3]], frames=2/2 (r/s)
[Thu Apr 16 17:08:57.661194 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(337): [client 192.168.178.45:33462] AH03066: h2_session(64,BUSY,0): recv FRAME[PRIORITY[length=5, flags=0, stream=5]], frames=3/2 (r/s)
[Thu Apr 16 17:08:57.661208 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(337): [client 192.168.178.45:33462] AH03066: h2_session(64,BUSY,0): recv FRAME[PRIORITY[length=5, flags=0, stream=7]], frames=4/2 (r/s)
[Thu Apr 16 17:08:57.661221 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(337): [client 192.168.178.45:33462] AH03066: h2_session(64,BUSY,0): recv FRAME[PRIORITY[length=5, flags=0, stream=9]], frames=5/2 (r/s)
[Thu Apr 16 17:08:57.661234 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(337): [client 192.168.178.45:33462] AH03066: h2_session(64,BUSY,0): recv FRAME[PRIORITY[length=5, flags=0, stream=11]], frames=6/2 (r/s)
[Thu Apr 16 17:08:57.661248 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(337): [client 192.168.178.45:33462] AH03066: h2_session(64,BUSY,0): recv FRAME[PRIORITY[length=5, flags=0, stream=13]], frames=7/2 (r/s)
[Thu Apr 16 17:08:57.661361 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_stream.c(542): [client 192.168.178.45:33462] AH03082: h2_stream(64-15,IDLE): created
[Thu Apr 16 17:08:57.661437 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(337): [client 192.168.178.45:33462] AH03066: h2_session(64,BUSY,1): recv FRAME[HEADERS[length=312, hend=1, stream=15, eos=0]], frames=8/2 (r/s)
[Thu Apr 16 17:08:57.661462 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(337): [client 192.168.178.45:33462] AH03066: h2_session(64,BUSY,1): recv FRAME[WINDOW_UPDATE[stream=15, incr=12451840]], frames=9/2 (r/s)
[Thu Apr 16 17:08:57.661500 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(337): [client 192.168.178.45:33462] AH03066: h2_session(64,BUSY,1): recv FRAME[DATA[length=152, flags=1, stream=15, padlen=0]], frames=10/2 (r/s)
[Thu Apr 16 17:08:57.661517 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(359): [client 192.168.178.45:33462] AH02923: h2_stream(64-15,OPEN): DATA, len=152, flags=1
[Thu Apr 16 17:08:57.661630 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(589): [client 192.168.178.45:33462] AH03068: h2_session(64,BUSY,1): sent FRAME[SETTINGS[ack=1, stream=0]], frames=11/3 (r/s)
[Thu Apr 16 17:08:57.662211 2020] [ssl:debug] [pid 6530:tid 139865497175808] ssl_engine_kernel.c(376): [client 192.168.178.45:33462] AH02034: Subsequent (No.2) HTTPS request received for child 16384 (server server.de:443), referer: https://server.de/path/
[Thu Apr 16 17:08:57.662386 2020] [authz_core:debug] [pid 6530:tid 139865497175808] mod_authz_core.c(843): [client 192.168.178.45:33462] AH01628: authorization result: granted (no directives), referer: https://server.de/path/
[Thu Apr 16 17:08:57.662479 2020] [proxy_fcgi:debug] [pid 6530:tid 139865497175808] mod_proxy_fcgi.c(108): [client 192.168.178.45:33462] AH01060: set r->filename to proxy:fcgi://127.0.0.1:9000/home/demo/www//path/index.php, referer: https://server.de/path/
[Thu Apr 16 17:08:57.662599 2020] [proxy:debug] [pid 6530:tid 139865497175808] mod_proxy.c(1253): [client 192.168.178.45:33462] AH01143: Running scheme fcgi handler (attempt 0), referer: https://server.de/path/
[Thu Apr 16 17:08:57.662638 2020] [proxy_ajp:debug] [pid 6530:tid 139865497175808] mod_proxy_ajp.c(743): [client 192.168.178.45:33462] AH00894: declining URL fcgi://127.0.0.1:9000/home/demo/www//path/index.php, referer: https://server.de/path/
[Thu Apr 16 17:08:57.662655 2020] [proxy_fcgi:debug] [pid 6530:tid 139865497175808] mod_proxy_fcgi.c(1019): [client 192.168.178.45:33462] AH01076: url: fcgi://127.0.0.1:9000/home/demo/www//path/index.php proxyname: (null) proxyport: 0, referer: https://server.de/path/
[Thu Apr 16 17:08:57.662667 2020] [proxy_fcgi:debug] [pid 6530:tid 139865497175808] mod_proxy_fcgi.c(1028): [client 192.168.178.45:33462] AH01078: serving URL fcgi://127.0.0.1:9000/home/demo/www//path/index.php, referer: https://server.de/path/
[Thu Apr 16 17:08:57.662698 2020] [proxy:debug] [pid 6530:tid 139865497175808] proxy_util.c(2336): AH00942: FCGI: has acquired connection for (127.0.0.1)
[Thu Apr 16 17:08:57.662734 2020] [proxy:debug] [pid 6530:tid 139865497175808] proxy_util.c(2392): [client 192.168.178.45:33462] AH00944: connecting fcgi://127.0.0.1:9000/home/demo/www//path/index.php to 127.0.0.1:9000, referer: https://server.de/path/
[Thu Apr 16 17:08:57.662886 2020] [proxy:debug] [pid 6530:tid 139865497175808] proxy_util.c(2615): [client 192.168.178.45:33462] AH00947: connected /home/demo/www//path/index.php to 127.0.0.1:9000, referer: https://server.de/path/
[Thu Apr 16 17:08:57.663081 2020] [proxy:debug] [pid 6530:tid 139865497175808] proxy_util.c(3081): AH02824: FCGI: connection established with 127.0.0.1:9000 (127.0.0.1)
[Thu Apr 16 17:08:57.668713 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(337): [client 192.168.178.45:33462] AH03066: h2_session(64,BUSY,1): recv FRAME[SETTINGS[ack=1, stream=0]], frames=11/3 (r/s)
[Thu Apr 16 17:08:59.819002 2020] [reqtimeout:info] [pid 6530:tid 139865408665344] [client 192.168.178.45:33462] AH01382: Request handshake read timeout
[Thu Apr 16 17:08:59.819091 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(1694): [client 192.168.178.45:33462] AH03078: h2_session(64,DONE,1): transit [BUSY] -- (null) --> [DONE]
[Thu Apr 16 17:08:59.819135 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(589): [client 192.168.178.45:33462] AH03068: h2_session(64,DONE,1): sent FRAME[GOAWAY[error=0, reason='', last_stream=15]], frames=12/4 (r/s)
[Thu Apr 16 17:08:59.819292 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(751): [client 192.168.178.45:33462] AH03069: h2_session(64,DONE,1): sent GOAWAY, err=0, msg=
[Thu Apr 16 17:08:59.819324 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_conn.c(211): (70014)End of file found: [client 192.168.178.45:33462] AH03045: h2_session(64,DONE,1): process, closing conn
[Thu Apr 16 17:08:59.819339 2020] [http2:debug] [pid 6530:tid 139865408665344] h2_session.c(1694): [client 192.168.178.45:33462] AH03078: h2_session(64,CLEANUP,1): transit [DONE] -- pre_close --> [CLEANUP]
[Thu Apr 16 17:09:00.409666 2020] [http2:debug] [pid 6530:tid 139865497175808] h2_from_h1.c(371): [client 192.168.178.45:33462] h2_task(000): read response, incomplete line: %HTML_CODE%
[Thu Apr 16 17:09:00.409825 2020] [proxy:debug] [pid 6530:tid 139865497175808] proxy_util.c(2351): AH00943: FCGI: has released connection for (127.0.0.1)
[Thu Apr 16 17:09:00.409966 2020] [http2:debug] [pid 6530:tid 139865497175808] h2_from_h1.c(371): [client 192.168.178.45:33462] h2_task(000): read response, incomplete line: <!DOCTYPE html><html><head><script src="/we
[Thu Apr 16 17:09:00.410005 2020] [http2:debug] [pid 6530:tid 139865497175808] h2_from_h1.c(371): [client 192.168.178.45:33462] h2_task(000): read response, incomplete line: \xb4\x99>OCTYPE html><html><head><script src="/we
[Thu Apr 16 17:09:00.410022 2020] [http2:debug] [pid 6530:tid 139865497175808] h2_from_h1.c(371): [client 192.168.178.45:33462] h2_task(000): read response, incomplete line: \xb4\x99>OCTYPE html><html><head><script src="/we
[Thu Apr 16 17:09:00.410033 2020] [http2:debug] [pid 6530:tid 139865497175808] h2_task.c(83): [client 192.168.178.45:33462] AH03348: h2_task(000): open output to POST server.de /path/index.php
[Thu Apr 16 17:09:00.410322 2020] [ssl:debug] [pid 6530:tid 139865408665344] ssl_engine_io.c(1102): [client 192.168.178.45:33462] AH02001: Connection closed to child 64 with standard shutdown (server server.de:443)
`

**Comment by icing** [comment]
Could you check the v1.15.8 released yesterday? There was a bug introduced in the version before that cause CGI scripts accessing the environment to fail.

**Comment by SteffenAL** [comment]
Trunk  is tested, and voted already.

**Comment by mokraemer** [comment]
tested 1.15.8, bug still persists!

**Comment by mokraemer** [comment]
if you need more info, just tell me what you need.

**Comment by mokraemer** [comment]
Is there any news on this?

**Comment by icing** [comment]
No, I did not find the time to look into this.

**Comment by icing** [comment]
This is causing the connection to close:

```
[Thu Apr 16 17:08:59.819002 2020] [reqtimeout:info] [pid 6530:tid 139865408665344] [client 192.168.178.45:33462] AH01382: Request handshake read timeout
```

The change is:

```
  *) mod_http2: Fixed interaction with mod_reqtimeout. A loaded mod_http2 was disabling the
     ssl handshake timeouts. Also, fixed a mistake of the last version that made `H2Direct` 
     always `on`, regardless of configuration. Found and reported by
     <Armin.Abfalterer@united-security-providers.ch> and
     <Marcial.Rion@united-security-providers.ch>. [Stefan Eissing] 
```

What is your reqtimeout configuration?

**Comment by mokraemer** [comment]
it was not obvious to mee this line is causing an the abort even though I've read the changelog.
My current settings are:
RequestReadTimeout handshake=2 header=20-180,MinRate=300 body=20-180,MinRate=200

A timeout of 2 seconds should be fair enough for the handshake. Since this happens on subsequent requests I assume the timer is not reseted after each request. If this is on purpose, it will be hard to configure as you don't know how many requests will be served in one http2 connection.

**Comment by icing** [comment]
No mistake of yours, just wanted to nail the most likely culprit. Looking to reproduce this in my test suite now...

**Comment by icing** [comment]
The release v1.15.9 fixes the problem I could reproduce in my test suite. Hope it works for you too.

**Comment by mokraemer** [comment]
Great!
Thanks for your work and time!
Have a nice weekend!
