### ISSUE TITLE
Version 1.15.8 on Release page and Trunk,  is already in Httpd 2.4.43 GA

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_h2#197]
See subject

**Comment by Jan-E** [comment]
Did you mean 1.15.8?

**Comment by SteffenAL** [comment]
Yes, sorry

**Comment by Jan-E** [comment]
The mod_http2 version in 2.4.42 GA might already be 1.15.8, but the change in h2_task.c is not there:
```
diff --git a/mod_http2/h2_task.c b/mod_http2/h2_task.c
index c3bf6a6..a0b22a3 100644
--- a/mod_http2/h2_task.c
+++ b/mod_http2/h2_task.c
@@ -586,6 +586,8 @@ apr_status_t h2_task_do(h2_task *task, apr_thread_t *thread, int worker_id)
          * configurations by mod_h2 alone. 
          */
         task->c->id = (c->master->id << 8)^worker_id;
+        task->id = apr_psprintf(task->pool, "%ld-%d", c->master->id, 
+                                task->stream_id);
     }
         
     h2_beam_create(&task->output.beam, c->pool, task->stream_id, "output", 
```
That seems to be the only real change in the code for compiling on Windows.

**Comment by SteffenAL** [comment]
I know, Stefan had to update to 1.15.9




On Thursday 16/04/2020 at 19:40, Jan Ehrhardt  wrote:
>
> The mod_http2 version in 2.4.42 GA might already be 1.15.8, but the 
> change in h2_task.c is not there:
>
> diff --git a/mod_http2/h2_task.c b/mod_http2/h2_task.c
index c3bf6a6..a0b22a3 100644
--- a/mod_http2/h2_task.c
+++ b/mod_http2/h2_task.c
@@ -586,6 +586,8 @@ apr_status_t h2_task_do(h2_task *task, 
apr_thread_t *thread, int worker_id)
 * configurations by mod_h2 alone.
 */
 task->c->id = (c->master->id << 8)^worker_id;
+        task->id = apr_psprintf(task->pool, "%ld-%d", c->master->id,
+                                task->stream_id);
 }

 h2_beam_create(&task->output.beam, c->pool, task->stream_id, 
"output",
That seems to be the only real change in the code for compiling on 
Windows.

**Comment by Jan-E** [comment]
https://github.com/icing/mod_h2/commit/52b8e94da3fda3411cca3962925f5e61c87a5487

**Comment by Jan-E** [comment]
BTW: In https://www.apachelounge.com/viewtopic.php?p=39062#39062 you talk about a "regression in mod_http2 since 2.4.1". That is a little bit overdone.

**Comment by SteffenAL** [comment]
Here is not the place to discuss AL wording.

At the release page here :  Fixed an unfortunate regression introduced....
