### ISSUE TITLE
The check on LimitRequestFields on headers of HTTP/2 fails to recognize LimitRequestFields = "0" condition - infinite number of fields as outlined in the documentation

### ISSUE THREAD

**Issue by DmitryFrolovTri** [icing/mod_h2#200]
Following condition: 
https://github.com/icing/mod_h2/blob/02239fcd930832aef0cfe8fcb45271062ce74757/mod_http2/h2_stream.c#L719
should not be executed at all in case LimitRequestFields == 0. (I suppose it should skip if  "session->s->limit_req_fields == 0", but not 100% sure may be there is another place where LimitRequestFields read from config is stored)
In the documentation:
http://httpd.apache.org/docs/2.4/mod/core.html#LimitRequestFields

So seems that HTTP/2 behaviour is different vs the documentation

**Comment by icing** [comment]
Well, just saw this after the release. Let's see if the changes regarding #201 work for you. Then I can add the fix for this one. ;)

**Comment by DmitryFrolovTri** [comment]
yes the changes are fine, thank you.
