### ISSUE TITLE
mod_http2 HTTP 431 errors and potentially other 4XX are not visible in the access_log and require observing error_log and switching higher log level

### ISSUE THREAD

**Issue by DmitryFrolovTri** [icing/mod_h2#202]
Hi, 
mod_http2 HTTP 431 errors are not visible in the access_log and require observing error_log , switching higher log levels. I am not sure if this is intended behavior or not, but seeing the 431 in the access_log would help in troubleshooting. 
Also if there are some other 4XX errors that don't get there would be great to see them there as well. 

1. Would be great to get 431 and possible other 4XX HTTP statuses logged in the access_log for the requests that got them in the standard access_log format for HTTP/2

Reason for raising this is that without reading the code, switching trace to max on production,  there is no place to see which error message was responded with if 431 happened and on which request and at first this led us into wrong troubleshooting path - issue on the ELB, in the network as we couldn't prove that our server was doing this. 

OR 

2. Alternatively any 4XX error in HTTP2 that is not in access_log could be logged with info level in clear text like 'responded with 4XX error" or something similair in the error_log, but I think the previous proposal is good enough. 

What are your thoughts?

**Comment by icing** [comment]
I agree that these 4xx codes need to be visible somewhere without enabling h2 special logging.

However, I seem to be unable to use the http/1.1 logging hooks in this situation without messing things up. This is more complicated that I thought...

**Comment by DmitryFrolovTri** [comment]
Well overtime I think H2 would replace http/1.1 but still I guess there will never be a good time for this change. :)
It's not a simple one, yes.

**Comment by icing** [comment]
Robert Plüm from the Apache Team is working on a fix for this. Should be available soon.

**Comment by DmitryFrolovTri** [comment]
Thank you! This would be a great help!


*Dmitry Frolov*

**Comment by icing** [comment]
@DmitryFrolovTri going through my issues list, has this been resolved with the latest mod_h2 form here or using the one in Apache httpd 2.4.48?

**Comment by DmitryFrolovTri** [comment]
Yes, last time we have checked this issue was not present any more.

<https://www.aurea.com/>

*Dmitry Frolov*
***@***.*** | M: +79629678725  | O: +15122018287 ext. 2088
Skype: bcad521m

www.aurea.com

**Comment by icing** [comment]
Thanks for confirming!
