### ISSUE TITLE
Support HTTP/3

### ISSUE THREAD

**Issue by techboyg5** [icing/mod_h2#206]
HTTP/3 is coming. mod_h2 should add support for HTTP/3 as well.

**Comment by icing** [comment]
I appreciated your trust in the mod_h2 developer, however HTTP/3 is a totally re-invention of the whole transport protocol and has no overlap with HTTP/2 that would make this meaningful.

But the Apache httpd project is still open to suggestions how to develop HTTP/3 for the server.
