### ISSUE TITLE
h2_request.c:217:22: error: implicit declaration of function ‘ap_create_request’

### ISSUE THREAD

**Issue by candrews** [icing/mod_h2#214]
mod_h2-1.15.20 fails to build with this error:
```
h2_request.c: In function ‘h2_request_create_rec’:
h2_request.c:217:22: error: implicit declaration of function ‘ap_create_request’; did you mean ‘ap_read_request’? [-Werror=implicit-function-declaration]
  217 |     request_rec *r = ap_create_request(c);
      |                      ^~~~~~~~~~~~~~~~~
      |                      ap_read_request
h2_request.c:217:22: error: initialization of ‘request_rec *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
h2_request.c:233:10: error: implicit declaration of function ‘ap_parse_request_line’ [-Werror=implicit-function-declaration]
  233 |     if (!ap_parse_request_line(r) || !ap_check_request_header(r)) {
      |          ^~~~~~~~~~~~~~~~~~~~~
h2_request.c:233:39: error: implicit declaration of function ‘ap_check_request_header’ [-Werror=implicit-function-declaration]
  233 |     if (!ap_parse_request_line(r) || !ap_check_request_header(r)) {
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~
```

[build.log](https://github.com/icing/mod_h2/files/6698227/build.log)

Using Apache 2.2.48.

**Comment by Sp1l** [comment]
Same issue here (FreeBSD 13.0 amd64 clang 11.0.1)

`ap_create_request` does not appear in source of 2.4.48

**Comment by icing** [comment]
Silly me. that will come in the next release.

**Comment by icing** [comment]
Sorry for the noise.

**Comment by icing** [comment]
Updated the release title and added the explanation.

**Comment by candrews** [comment]
> Silly me. that will come in the next release.

Do you mean the next release of mod_h2, or the next release of Apache (aka 2.4.49)?

**Comment by icing** [comment]
> Do you mean the next release of mod_h2, or the next release of Apache (aka 2.4.49)?

The current source relies on a change present int he Apache 2.4.x maintenance branch, but not yet part of a release. So, it will definitely be in the next release, but it is not known when.

Since there are other, small enhancements, I will do a 1.5.21 soon that builds again with the release 2.4.48 Apache. Maybe try to get a solution of #212 in that one.

**Comment by candrews** [comment]
> I will do a 1.5.21 soon that builds again with the release 2.4.48 Apache.

Do you have an ETA on that release? (I maintain the Gentoo package for mod_h2, fwiw)

Thanks again, I greatly appreciate this project :)

**Comment by icing** [comment]
@candrews thanks, always nice to get such feedback!

I will most likely do a release today that works with Apache 2.4.48.

**Comment by icing** [comment]
Just released https://github.com/icing/mod_h2/releases/tag/v1.15.21 which works with Apache httpd 2.4.48 again. Sorry for the wasted cycles.
