### ISSUE TITLE
Suggestion to update Push Diary docs

### ISSUE THREAD

**Issue by tunetheweb** [icing/mod_h2#229]
Noticed the following: https://httpd.apache.org/docs/2.4/mod/mod_http2.html#h2pushdiarysize

> The push diary records a digest (currently using a 64 bit number) of pushed resources (their URL) to avoid duplicate pushes on the same connection. These value are not persisted, so clients opening a new connection will experience known pushes again. There is ongoing work to enable a client to disclose a digest of the resources it already has, so the diary maybe initialized by the client on each connection setup.

Given cache digests has been dropped (and [removed from mod_http2](https://github.com/icing/mod_h2/commit/b8a8c5061eada0ce3339b24ba1d587134552bc0c) should that last sentence be dropped as there now is no "ongoing work" AFAIK?

**Comment by icing** [comment]
Thanks @tunetheweb  for catching this! Removed in r1897753 in Apache trunk and backported to 2.4.x branch.
