### ISSUE TITLE
mismatching :scheme header is ignored

### ISSUE THREAD

**Issue by icing** [icing/mod_h2#230]
...but should give a 400.

**Comment by royfielding** [comment]
I don't think this is correct, or at least I don't understand the comment.
In HTTP/2:

> The :scheme pseudo-header field includes the scheme portion of the request target. The scheme is taken from the target URI ([Section 3.1](https://rfc-editor.org/rfc/rfc3986#section-3.1) of [[RFC3986](https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#RFC3986)]) when generating a request directly, or from the scheme of a translated request (for example, see [Section 3.3](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-messaging-18#section-3.3) of [[HTTP11](https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#HTTP11)]). Scheme is omitted for [CONNECT requests](https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#CONNECT) ([Section 8.5](https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#CONNECT)).
> 
> :scheme is not restricted to http and https schemed URIs. A proxy or gateway can translate requests for non-HTTP schemes, enabling the use of HTTP to interact with non-HTTP services.

I understand it rejecting an https request if the connection is not secured, but I don't think this applies in general to any other schemes (or even http requested using a secured connection).

**Comment by icing** [comment]
Yeah, I was having thoughts on letting http: in on a https: connection. But then decided to take the safe route. I appreciate your input on this one.

I think the really proper way in our server is to make sure the scheme, if present, is properly present in `request_rec` and then have a protocol version independent check in our general request header validation.

Which then raises the question if we handle scheme from absolute urls correctly when coming via http/1.1. right now. But an added test case should verify that.

**Comment by bowlofeggs** [comment]
I filed https://bz.apache.org/bugzilla/show_bug.cgi?id=66499 about an issue I experience after the change made for this issue.

Is Bugzilla a better place to file, or is GitHub preferred?

**Comment by mentalstring** [comment]
Also note sure if this is the best place to report this, so apologies in advance if that's the case.

In our case, we have a load balancer terminating TLS and passing the request to apache. After upgrading to 2.4.55, the absolute URI is being logged instead of relative for all http2 requests. Not sure if this is intended, but sure is different from all previous versions and http1.1 requests continue to be logged as relative.

**Comment by tabacco** [comment]
Yeah this caused an unexpected change of behavior, as it changes the value of REQUEST_URI sent by mod_proxy_fcgi when TLS termination is handled by a proxy in front of Apache.

**Comment by icing** [comment]
Made #250 to revert the change for `http` and `https` schemes. `:scheme` headers sent by a client with other values continue to be forwarded as absolute URI to request processing.

This should fix the problem of absolute URI appearing in access logs and cgi processing.

**Comment by icing** [comment]
Merged #250 into master.
