### ISSUE TITLE
grpc client receives "rpc error: code = Internal desc = server closed the stream without sending trailers"

### ISSUE THREAD

**Issue by ajain621** [icing/mod_h2#233]
Hi,

I am introducing a new backend server (a grpc server, say v3 api) alongside our existing backend servers (serving v2 version of our apis). The existing backend servers (python) along with this new server are proxied via apache. Apache is also used to terminate the tls connection. In order to make grpc client work with this grpc server which is proxied via apache, I needed to add the http2 modules to apache. This is done successfully. Here are the details:

ubuntu@:~$ sudo apache2 -v
Server version: Apache/2.4.53 (Ubuntu)
Server built:   2022-04-28T11:49:35

ubuntu@:~$ sudo apache2ctl -M
[Fri Jun 24 20:05:56.107750 2022] [core:trace3] [pid 31567:tid 140409546701760] core.c(3472): Setting LogLevel for all modules to trace8
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cgi_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 headers_module (shared)
 http2_module (shared)
 mime_module (shared)
 mpm_event_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_fcgi_module (shared)
 proxy_http_module (shared)
 proxy_http2_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
 unique_id_module (shared)

in file: /etc/apache2/sites-enabled/default-ssl.conf

ProxyPass "/v2" "unix://var/run/wsgi_api.sock|http://127.0.0.1/v2/"
ProxyPass "/v3" "h2c://127.0.0.1:9080"

grpc-client is able to successfully communicate with the backend grpc-server (via apache proxy). The only problem is when there is an error generated in grpc-server the same error status, and message isn't sent to the grpc-client via apache. Somehow the client gets only generic error which is **rpc error: code = Internal desc = server closed the stream without sending trailers**. I have attached a successful and an erroneous case here https://stackoverflow.com/questions/72610431/grpc-client-internal-desc-server-closed-the-stream-without-sending-trailers

If we don't use apache and make gprc-client communicate with the server directly, we don't see any problems and error messages are properly sent to the client.

**Comment by icing** [comment]
HI @ajain621, thanks for the report.

What I did not find in the logs are the 'http2:' traces from mod_http2 when it supposedly closes/resets the steam. The behaviour about which your client complained. Could you produce those?

**Comment by ajain621** [comment]
Sure @icing I will reproduce . Is there any specific trace level I need to enable. Currently I am at "LogLevel trace8".

**Comment by ajain621** [comment]
[grpc_client_success_trace6.txt](https://github.com/icing/mod_h2/files/8995491/grpc_client_success_trace6.txt)
[grpc_client_gets_no_proper_err_msg_trace6.txt](https://github.com/icing/mod_h2/files/8995492/grpc_client_gets_no_proper_err_msg_trace6.txt)
![arch_server_v3_v2](https://user-images.githubusercontent.com/98777861/176033155-2df46d74-8adb-46ef-b9fd-2d45a91de8d0.png)

Added the architecture diagram, and supported logs. For the log "grpc_client_gets_no_proper_err_msg_trace6.txt"  the grpc client sees "rpc error: code = Internal desc = server closed the stream without sending trailers:". The actual error generated by grpc-server which is "Invalid or missing credentials when calling v1 api: CID required." doesn reach the grpc-client. Before the "grpc-status" and "grpc-message" headers could reach the client, I think apache is closing the stream.

**Comment by ajain621** [comment]
Thanks @icing . I will retest with your patch. I have not build it mod_http2 from source, but can give it a try. Any document would help.

**Comment by ajain621** [comment]
@icing let me know when the patch is ready. Thks.

**Comment by icing** [comment]
Reopening it for confirmation.

**Comment by icing** [comment]
For interest: what version of mod_http2 are you running where the error happens? Should be logged at INFO level on startup. Thanks!

**Comment by ajain621** [comment]
[Sat Jul 02 16:38:46.294477 2022] [ssl:info] [pid 15449:tid 140169775844288] AH01876: mod_ssl/2.4.53 compiled against Server: Apache/2.4.53, Library: OpenSSL/1.1.1
[Sat Jul 02 16:38:46.294509 2022] [http2:info] [pid 15449:tid 140169775844288] AH03090: mod_http2 (v1.15.26, feats=CHPRIO+SHA256+INVHD+DWINS, nghttp2 1.30.0), initializing...
[Sat Jul 02 16:38:46.294533 2022] [http2:trace1] [pid 15449:tid 140169775844288] h2_h2.c(439): h2_h2, child_init
[Sat Jul 02 16:38:46.294572 2022] [http2:trace1] [pid 15449:tid 140169775844288] h2_switch.c(45): h2_switch init
[Sat Jul 02 16:38:46.294911 2022] [proxy_http2:info] [pid 15449:tid 140169775844288] AH03349: mod_proxy_http2 (**v1.15.26, nghttp2 1.30.0**), initializing...

**Comment by ajain621** [comment]
@icing I am unable to resolve the following error

checking for nghttp2_session_server_new2 in -lnghttp2... no
configure: error: "library nghttp2 not found"

**Comment by icing** [comment]
You need the packages apache2-dev and libnghttp2-dev installed.

**Comment by ajain621** [comment]
@icing the patch works as expected. I am able to see the correct response and I don't see stream termination without sending trailers error in my grpc client. Thanks a lot for a quick patch. Do you want logs?

**Comment by icing** [comment]
Thanks for verifying! No logs needed. I added a test case for exactly this behaviour to make sure it does not break again.

To determine the affected versions, it would be good to know the version you had trouble with.

**Comment by ajain621** [comment]
I had trouble with Apache/**2.4.53**, mod_http2 (**v1.15.26**)
after your patch
mod_proxy_http2 (**v2.0.3-git**, nghttp2 1.30.0), initializing...
Apache/**2.4.53** (Ubuntu) OpenSSL/**1.1.1** configured

**Comment by icing** [comment]
Hmm, unable to reproduce the problem on a mod_http2 v1.15.x. I have clear test cases for v2.x that reproduces and where I did the fix. However these tests run fine on an unmodified v1.15.x (as shipped in Apache httpd 2.4.53/54).

Something does not match.

**Comment by ajain621** [comment]
@icing so you mean the erstwhile version (without this fix) is able to sent trailers?

**Comment by icing** [comment]
@ajain621 at least, I cannot reproduce the problem there with my test cases. If you could possible test this in your setup and confirm/deny, I either am happy or need to dig deeper.

**Comment by ajain621** [comment]
Thanks for verifying @mholasek. @icing when is next release of apache 2.4.55? I hope it would bundle the latest mod_h2 in it.
