### ISSUE TITLE
huge h2 mode delays with candy-chat, an xmpp web chat client

### ISSUE THREAD

**Issue by lkraav** [icing/mod_h2#24]
![screenshot from 2015-06-01 00-35-48](https://cloud.githubusercontent.com/assets/147228/7904032/58a5fb58-07f6-11e5-8a44-eec477d47cf8.png)

this is what's happening. each POST request takes a long time to complete, and messages don't become visible until (pending) status completes. thoughts?

**Comment by icing** [comment]
Hmm, I need more detail about the request/response. Can you attache a screenshot of the individual request in dev tools. Alternatively, a wireshark session could also work.

**Comment by lkraav** [comment]
Can I give you access to the webchat? I think we would arrive at the solution faster if you see it first hand.

**Comment by icing** [comment]
Sure, I have only limited time this week. But I certainly would like to have a look.

Is this server under load or would it be feasible to increase the log level on h2 for testing?


> Am 01.06.2015 um 11:08 schrieb Leho Kraav <notifications@github.com>:
> 
> Can I give you access to the webchat? I think we would arrive at the solution faster if you see it first hand.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

<green/>bytes GmbH
Hafenweg 16, 48155 Münster, Germany
Phone: +49 251 2807760. Amtsgericht Münster: HRB5782

**Comment by lkraav** [comment]
Load is very light, not a problem to increase verbosity.

**Comment by icing** [comment]
Can you give me access? Then I have a look.

**Comment by lkraav** [comment]
Yes, I got delayed with some additional server work. 0.6.3 the delay is still there, so I'll get you access in a few hours now.

**Comment by icing** [comment]
I added "prefork" to the "known problems" in the README. Happy, that the threaded mpms work for your site!
