### ISSUE TITLE
http2-status removed ?

### ISSUE THREAD

**Issue by SteffenAL** [icing/mod_h2#242]
http2-status does not work anymore on v2.0.11 windows.

Is the function removed ?

<Location /xxxx>
    SetHandler http2-status
    Require all granted
 </Location>

**Comment by icing** [comment]
Yes, it is gone.

The reason for this is that it is based on a abandoned IETF draft which did not gain traction. The implementation of the feature complicated response processing in mod_http2 and as a cost-benefit thing, I'd rather removed the code.
