### ISSUE TITLE
sporadic blocking POST requests with mod_http2 v2.0

### ISSUE THREAD

**Issue by meierfra-ergon** [icing/mod_h2#262]
Hi,
after update from httpd-2.4.54 to httpd-2.4.55 we experience sporadic blocking POST requests in our performance-test environment (about 1 in 20000). It seems only requests with body are affected. 
There is no issue with mod_http2 v1.15.28 of apache httpd-2.4.54. But with all following httpd releases. I also tested with the newest git branch (httpd 2.4.x) with mod_http2 v2.0.19-git, where the Issue is still visible.

We use our own httpd (reverse proxy) module, which reads the body input stream with ```ap_get_brigade(r->input_filters, bb, AP_MODE_READBYTES, APR_BLOCK_READ, bufsiz)```. I could deduce, that this call blocks sometimes indefinitely (?), until the client times out (after 20s). The headers of the request are read without issue.

I`m afraid I do not have anything better to show, since debugging with performance-tests is not that simple. I may not enable debug-logs, since this would probably flood the log-system.

Do you have any idea where the Problem could be originating? So I may be could add debug-code in a specific location

**Comment by meierfra-ergon** [comment]
Further tests with another load-generator did not reproduce the described behavior. 
Therefore I updated the libraries used by the first load-generator [1] (which was using very old version of curl/nghttp2). Then the issue did not occur anymore.
I think I will not investigate this Issue any further, feel free to close it.

**Comment by icing** [comment]
Thanks for the update.
