### ISSUE TITLE
HTTP/2 and SNI oddities

### ISSUE THREAD

**Issue by VFrontDe** [icing/mod_h2#27]
I noticed an oddity when using the latest Chrome browser against a mod_h2 patched apache server: I use SNI to have multiple SSL-sites on the same IP address, and it looks like Chrome gets confused over this.
I believe that this is a Chrome bug, so I filed this bug report:
   https://code.google.com/p/chromium/issues/detail?id=498765
There you will also find details and steps to reproduce.

Just want to give you a heads-up here, because there is a small chance that the issue is really triggered by mod_h2 incorrectly handling SNI virtual hosts.

**Comment by lkraav** [comment]
I am seeing the same thing on Firefox. This is some more generic thing. Perhaps about re-using connections etc.

See https://bz.apache.org/bugzilla/show_bug.cgi?id=58007

**Comment by VFrontDe** [comment]
But before I enabled mod_h2 in apache all browsers behaved fine?! And browsers that do not support http/2 still behave fine with the test sites.

**Comment by icing** [comment]
Unfortunately, this is a bug in httpd, where no patch exists yet. This happens with wildcard certificate when the browser re-uses the connection from one host to send requests for another.

**Comment by VFrontDe** [comment]
Yes, I use a wildcard cert here. But why is it only triggered with http/2 ?

**Comment by icing** [comment]
Because browsers reuse connections in this way only when HTTP/2 is used. The Apache core is not prepared for this and, unnecessary checks, that all requests from an SNI connection carry the same Host: header.

**Comment by VFrontDe** [comment]
Ahh, I see ... I will check for related apache bug reports. Maybe it's time to migrate to nginx, sigh!

**Comment by icing** [comment]
If you build your httpd with the new sni_misdirect.patch from v0.6.6, the problem will disappear.
