### ISSUE TITLE
Can't open the web using http/2

### ISSUE THREAD

**Issue by haohetao** [icing/mod_h2#28]
nghttp 1.0.2,mod_h2 0.7.0,openssl 1.0.2c,apache 2.4.12
I install openssl package openssl_1.0.2c-1ubuntu1_amd64.deb,libssl1.0.0_1.0.2c-1ubuntu1_amd64.deb,libssl-dev_1.0.2c-1ubuntu1_amd64.deb on ubuntu 14.04.
root@ubuntu:~/mod_h2-0.7.0# nghttp -v https://www.test.com/test.html
[  0.162] Connected
[  0.340][NPN] server offers:
[ERROR] HTTP/2 protocol was not selected. (nghttp2 expects h2)
Some requests were not processed. total=1, processed=0
root@ubuntu:~/mod_h2-0.7.0# tail /var/log/apache2/error.log            
[Thu Jun 18 12:29:46.639110 2015] [core:notice] [pid 10028] AH00051: child pid 10246 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Thu Jun 18 12:31:40.776004 2015] [core:notice] [pid 10028] AH00051: child pid 10260 exit signal Segmentation fault (11), possible coredump in /etc/apache2

**Comment by icing** [comment]
Thanks for the report. Some questions:

Did you have mod_h2 working before or is this a new effect with v0.7.0? 
Which patch did you apply to mod_ssl (if any)?

**Comment by Sal0g** [comment]
I also get segfaults with apache using every version 0.6.5 to 0.7.0. Last working version for me was  version 0.6.4.

[Thu Jun 18 11:23:43.177668 2015] [core:notice] [pid 25896:tid 139887405557532] AH00052: child pid 26223 exit signal Segmentation fault (11)
[Thu Jun 18 11:23:43.177869 2015] [core:notice] [pid 25896:tid 139887405557532] AH00052: child pid 26365 exit signal Segmentation fault (11)

**Comment by icing** [comment]
Which mpm module have you configured?

**Comment by Sal0g** [comment]
Oh yes, sry: using mpm-worker. apache 2.4.12,  mod_ssl with alpine patch.

**Comment by icing** [comment]
Ok, this seems to be two issues: 1. that the h2 connection no longer works and 2. that you have segfaults. Let's clarify 1 for now. Since when can you no longer connect via h2?

**Comment by Sal0g** [comment]
Both issues started when I upgraded to 0.6.5 and each version since.

**Comment by bronzeblood** [comment]
Im getting the same here. Segfaults , last version that i tried and worked was 0.6.2. 
Using mpm-worker , apache 2.4.10 , nghttp 1.0.2 , mod_h2 0.7.0

[Fri Jun 19 11:51:35.555286 2015] [mpm_worker:notice] [pid 29974:tid 139936866502528] AH00292: Apache/2.4.10 (Debian) OpenSSL/1.0.2c configured -- resuming normal operations
[Fri Jun 19 11:51:35.555399 2015] [core:notice] [pid 29974:tid 139936866502528] AH00094: Command line: '/usr/sbin/apache2'
[Fri Jun 19 11:51:46.565077 2015] [core:notice] [pid 29974:tid 139936866502528] AH00052: child pid 29981 exit signal Segmentation fault (11)
[Fri Jun 19 11:51:47.566130 2015] [core:notice] [pid 29974:tid 139936866502528] AH00052: child pid 29982 exit signal Segmentation fault (11)
[Fri Jun 19 11:51:49.567205 2015] [core:notice] [pid 29974:tid 139936866502528] AH00052: child pid 31400 exit signal Segmentation fault (11)
[Fri Jun 19 11:52:15.592479 2015] [core:notice] [pid 29974:tid 139936866502528] AH00052: child pid 31690 exit signal Segmentation fault (11)

**Comment by haohetao** [comment]
I test with firefox 38.0.5
when security.ssl.enable_alpn;true
It is not work and error.log found Segmentation fault
![qq 20150619103359](https://cloud.githubusercontent.com/assets/4592571/8246295/d10db244-166e-11e5-90cd-aa57edebcc02.jpg)

when security.ssl.enable_alpn;false
It is work fine
![qq 20150619103223](https://cloud.githubusercontent.com/assets/4592571/8246318/3e72ac36-166f-11e5-81a8-985d958e6c91.jpg)

**Comment by icing** [comment]
Thanks for the info. Can you just for an attempt add

LogLevel h2:trance2

to your config and make a firefox request with alpn enabled. That should fail as you said. Please send my the log at stefan.eissing at greenbytes.de. Thanks!

**Comment by icing** [comment]
*trace2, not trance2 ;-)

**Comment by haohetao** [comment]
root@ubuntu:~# tail -f /var/log/apache2/error.log
[Fri Jun 19 23:49:12.951813 2015] [h2:trace2] [pid 16249:tid 140680563164928] h2_conn_io.c(92): [client 123.149.14.221:51909] h2_conn_io(0): read 293 bytes:  0  1  f  1 25  0  0  0  d 
[Fri Jun 19 23:49:12.951868 2015] [h2:debug] [pid 16249:tid 140680563164928] h2_stream.c(68): [client 123.149.14.221:51909] h2_stream(0-13): created
[Fri Jun 19 23:49:12.951872 2015] [h2:debug] [pid 16249:tid 140680563164928] h2_session.c(83): [client 123.149.14.221:51909] h2_session: stream(0-13): opened
[Fri Jun 19 23:49:12.951896 2015] [h2:trace1] [pid 16249:tid 140680563164928] h2_session.c(354): [client 123.149.14.221:51909] h2_session(0): on_frame_rcv #9, type=1
[Fri Jun 19 23:49:12.951904 2015] [h2:trace1] [pid 16249:tid 140680563164928] h2_to_h1.c(154): [client 123.149.14.221:51909] h2_to_h1(0-13): end headers
[Fri Jun 19 23:49:12.951907 2015] [h2:trace1] [pid 16249:tid 140680563164928] h2_to_h1.c(288): [client 123.149.14.221:51909] h2_to_h1(13): close
[Fri Jun 19 23:49:12.951910 2015] [h2:debug] [pid 16249:tid 140680563164928] h2_workers.c(257): h2_workers: register mplx(0)
[Fri Jun 19 23:49:12.951917 2015] [h2:debug] [pid 16249:tid 140680563164928] h2_stream.c(188): [client 123.149.14.221:51909] h2_stream(0-13): closing input
[Fri Jun 19 23:49:12.951919 2015] [h2:debug] [pid 16249:tid 140680563164928] h2_stream.c(178): [client 123.149.14.221:51909] h2_stream(0-13): end header, task GET /images/bg2.jpg (www.nmgjhjy.com)
[Fri Jun 19 23:49:12.951921 2015] [h2:debug] [pid 16249:tid 140680563164928] h2_stream.c(188): [client 123.149.14.221:51909] h2_stream(0-13): closing input
[Fri Jun 19 23:49:12.951923 2015] [h2:debug] [pid 16249:tid 140680563164928] h2_session.c(429): [client 123.149.14.221:51909] h2_stream(0-13): input closed
[Fri Jun 19 23:49:12.951926 2015] [h2:trace1] [pid 16249:tid 140680563164928] h2_session.c(354): [client 123.149.14.221:51909] h2_session(0): on_frame_rcv #10, type=8
[Fri Jun 19 23:49:12.951929 2015] [h2:trace2] [pid 16249:tid 140680563164928] h2_session.c(413): [client 123.149.14.221:51909] h2_session: on_frame_rcv WINDOW_UPDATE[length=4, stream=13]
[Fri Jun 19 23:49:12.951934 2015] [h2:trace2] [pid 16249:tid 140680563164928] h2_conn_io.c(123): [client 123.149.14.221:51909] h2_conn_io: try read, block=1
[Fri Jun 19 23:49:12.951975 2015] [h2:debug] [pid 16249:tid 140680798652160] h2_workers.c(78): h2_worker(0): start mplx(0)
[Fri Jun 19 23:49:12.951985 2015] [h2:debug] [pid 16249:tid 140680798652160] h2_task_input.c(75): [client 123.149.14.221:51909] h2_task_input(0-13): request is: 
[Fri Jun 19 23:49:12.951990 2015] [h2:trace2] [pid 16249:tid 140680798652160] h2_task.c(131): [client 123.149.14.221:51909] h2_h2, pre_connection, found stream task
[Fri Jun 19 23:49:12.951994 2015] [h2:trace1] [pid 16249:tid 140680798652160] h2_task.c(140): [client 123.149.14.221:51909] h2_stream(0-13): task_pre_conn, taking over
[Fri Jun 19 23:49:12.951996 2015] [h2:trace2] [pid 16249:tid 140680798652160] h2_task.c(153): [client 123.149.14.221:51909] h2_h2, processing request directly
[Fri Jun 19 23:49:12.952010 2015] [h2:debug] [pid 16249:tid 140680798652160] h2_h2.c(208): [client 123.149.14.221:51909] adding h1_to_h2_resp output filter
[Fri Jun 19 23:49:12.952255 2015] [h2:trace1] [pid 16249:tid 140680798652160] h2_from_h1.c(544): [client 123.149.14.221:51909] h2_from_h1(13): output_filter called
[Fri Jun 19 23:49:12.952267 2015] [h2:warn] [pid 16249:tid 140680798652160] (22)Invalid argument: [client 123.149.14.221:51909] h2_response(13) header -> Date: Fri, 19 Jun 2015 15:49:12 GMT
[Fri Jun 19 23:49:12.952275 2015] [h2:warn] [pid 16249:tid 140680798652160] (22)Invalid argument: [client 123.149.14.221:51909] h2_response(13) header -> Server: Apache/2.4.12 (Ubuntu)
[Fri Jun 19 23:49:12.952277 2015] [h2:warn] [pid 16249:tid 140680798652160] (22)Invalid argument: [client 123.149.14.221:51909] h2_response(13) header -> ETag: "3389-50867a310e380"
[Fri Jun 19 23:49:12.952280 2015] [h2:warn] [pid 16249:tid 140680798652160] (22)Invalid argument: [client 123.149.14.221:51909] h2_response(13) header -> Expires: Sat, 20 Jun 2015 15:49:12 GMT
[Fri Jun 19 23:49:12.952286 2015] [h2:warn] [pid 16249:tid 140680798652160] (22)Invalid argument: [client 123.149.14.221:51909] h2_response(13) header -> Cache-Control: max-age=86400
[Fri Jun 19 23:49:12.952289 2015] [h2:trace1] [pid 16249:tid 140680798652160] h2_from_h1.c(607): [client 123.149.14.221:51909] h2_from_h1(13): removed header filter, passing brigade len=0
[Fri Jun 19 23:49:12.952292 2015] [h2:debug] [pid 16249:tid 140680798652160] h2_mplx.c(448): [client 123.149.14.221:51909] h2_mplx(0-13): open response: 304
[Fri Jun 19 23:49:12.952296 2015] [h2:trace1] [pid 16249:tid 140680798652160] h2_task_output.c(127): [client 123.149.14.221:51909] h2_task_output(0-13): opened and passed brigade
[Fri Jun 19 23:49:12.952300 2015] [h2:trace1] [pid 16249:tid 140680798652160] h2_task_output.c(131): [client 123.149.14.221:51909] h2_task_output(0-13): write brigade
[Fri Jun 19 23:49:13.778663 2015] [core:notice] [pid 15396:tid 140680914806656] AH00051: child pid 16249 exit signal Segmentation fault (11), possible coredump in /etc/apache2

**Comment by covener** [comment]
Can you obtain backtraces from the coredump?  http://httpd.apache.org/dev/debugging.html

**Comment by haohetao** [comment]
The apache package is on https://launchpad.net/~ondrej/+archive/ubuntu/apache2
root@ubuntu:/etc/apache2# gdb apache2     
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from apache2...(no debugging symbols found)...done.
(gdb) run -X -d /etc/apache2
Starting program: /usr/sbin/apache2 -X -d /etc/apache2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[New Thread 0x7ffff1127700 (LWP 18002)]
[New Thread 0x7ffff0926700 (LWP 18003)]
[New Thread 0x7ffff0125700 (LWP 18004)]
[New Thread 0x7fffef924700 (LWP 18005)]
[New Thread 0x7fffef11f700 (LWP 18006)]
[New Thread 0x7fffee918700 (LWP 18007)]
[New Thread 0x7fffee111700 (LWP 18008)]
[New Thread 0x7fffed90a700 (LWP 18009)]
[New Thread 0x7fffed103700 (LWP 18010)]
[New Thread 0x7fffec8fc700 (LWP 18011)]
[New Thread 0x7fffec0f5700 (LWP 18012)]
[New Thread 0x7fffeb8ee700 (LWP 18013)]
[New Thread 0x7fffeb0e7700 (LWP 18014)]
[New Thread 0x7fffea8e0700 (LWP 18015)]
[New Thread 0x7fffea0d9700 (LWP 18016)]
[New Thread 0x7fffe98d2700 (LWP 18017)]
[New Thread 0x7fffe90cb700 (LWP 18018)]
[New Thread 0x7fffe88c4700 (LWP 18019)]
[New Thread 0x7fffe80bd700 (LWP 18020)]
[New Thread 0x7fffe78b6700 (LWP 18021)]
[New Thread 0x7fffe70af700 (LWP 18022)]
[New Thread 0x7fffe68a8700 (LWP 18023)]
[New Thread 0x7fffe60a1700 (LWP 18024)]
[New Thread 0x7fffe589a700 (LWP 18025)]
[New Thread 0x7fffe5093700 (LWP 18026)]
[New Thread 0x7fffe4892700 (LWP 18027)]
[New Thread 0x7fffe4091700 (LWP 18028)]
[New Thread 0x7fffe3890700 (LWP 18029)]
[New Thread 0x7fffe308f700 (LWP 18030)]
[New Thread 0x7fffe288e700 (LWP 18031)]
[New Thread 0x7fffe208d700 (LWP 18032)]
[New Thread 0x7fffe188a700 (LWP 18033)]
[New Thread 0x7fffe1087700 (LWP 18034)]
[New Thread 0x7fffe0884700 (LWP 18035)]
[New Thread 0x7fffdbfff700 (LWP 18036)]
[New Thread 0x7fffdb7fe700 (LWP 18037)]
[New Thread 0x7fffdaffd700 (LWP 18038)]
[New Thread 0x7fffda7fc700 (LWP 18039)]
[New Thread 0x7fffd9ffb700 (LWP 18040)]
[New Thread 0x7fffd97fa700 (LWP 18041)]
[New Thread 0x7fffd8ff9700 (LWP 18042)]
[New Thread 0x7fffd87f8700 (LWP 18043)]
[New Thread 0x7fffd7ff7700 (LWP 18044)]
[New Thread 0x7fffd77f6700 (LWP 18045)]
[New Thread 0x7fffd6ff5700 (LWP 18046)]
[New Thread 0x7fffd67f4700 (LWP 18047)]
[New Thread 0x7fffd5ff3700 (LWP 18048)]
[New Thread 0x7fffd57f2700 (LWP 18049)]
[New Thread 0x7fffd4ff1700 (LWP 18050)]
[New Thread 0x7fffd47f0700 (LWP 18051)]
[New Thread 0x7fffd3fef700 (LWP 18052)]
[New Thread 0x7fffd37ee700 (LWP 18053)]
[New Thread 0x7fffd2fed700 (LWP 18054)]
[New Thread 0x7fffd27ec700 (LWP 18055)]
[Thread 0x7fffe3890700 (LWP 18029) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe5093700 (LWP 18026)]
0x00005555555ca7a6 in ?? ()
![qq 20150620020056](https://cloud.githubusercontent.com/assets/4592571/8259603/55c042aa-16f0-11e5-9bc1-d79c98a5f162.jpg)

**Comment by haohetao** [comment]
The core dump file.
https://www.dropbox.com/s/2q55r5a150m98gt/core?dl=0

**Comment by haohetao** [comment]
root@ubuntu:/root/mod_h2-0.7.0/sandbox/install/modules# gdb apache2
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from apache2...Reading symbols from /usr/lib/debug//usr/sbin/apache2...done.
done.
(gdb) run -X -d /etc/apache2
Starting program: /usr/sbin/apache2 -X -d /etc/apache2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[New Thread 0x7ffff1127700 (LWP 5301)]
[New Thread 0x7ffff0926700 (LWP 5302)]
[New Thread 0x7ffff0125700 (LWP 5303)]
[New Thread 0x7fffef924700 (LWP 5304)]
[New Thread 0x7fffef11f700 (LWP 5305)]
[New Thread 0x7fffee918700 (LWP 5306)]
[New Thread 0x7fffee111700 (LWP 5307)]
[New Thread 0x7fffed90a700 (LWP 5308)]
[New Thread 0x7fffed103700 (LWP 5309)]
[New Thread 0x7fffec8fc700 (LWP 5310)]
[New Thread 0x7fffec0f5700 (LWP 5311)]
[New Thread 0x7fffeb8ee700 (LWP 5312)]
[New Thread 0x7fffeb0e7700 (LWP 5313)]
[New Thread 0x7fffea8e0700 (LWP 5314)]
[New Thread 0x7fffea0d9700 (LWP 5315)]
[New Thread 0x7fffe98d2700 (LWP 5316)]
[New Thread 0x7fffe90cb700 (LWP 5317)]
[New Thread 0x7fffe88c4700 (LWP 5318)]
[New Thread 0x7fffe80bd700 (LWP 5319)]
[New Thread 0x7fffe78b6700 (LWP 5320)]
[New Thread 0x7fffe70af700 (LWP 5321)]
[New Thread 0x7fffe68a8700 (LWP 5322)]
[New Thread 0x7fffe60a1700 (LWP 5323)]
[New Thread 0x7fffe589a700 (LWP 5324)]
[New Thread 0x7fffe5093700 (LWP 5325)]
[New Thread 0x7fffe4892700 (LWP 5326)]
[New Thread 0x7fffe4091700 (LWP 5327)]
[New Thread 0x7fffe3890700 (LWP 5328)]
[New Thread 0x7fffe308f700 (LWP 5329)]
[New Thread 0x7fffe288e700 (LWP 5330)]
[New Thread 0x7fffe208d700 (LWP 5331)]
[New Thread 0x7fffe188a700 (LWP 5332)]
[New Thread 0x7fffe1087700 (LWP 5333)]
[New Thread 0x7fffe0884700 (LWP 5334)]
[New Thread 0x7fffdbfff700 (LWP 5335)]
[New Thread 0x7fffdb7fe700 (LWP 5336)]
[New Thread 0x7fffdaffd700 (LWP 5337)]
[New Thread 0x7fffda7fc700 (LWP 5338)]
[New Thread 0x7fffd9ffb700 (LWP 5339)]
[New Thread 0x7fffd97fa700 (LWP 5340)]
[New Thread 0x7fffd8ff9700 (LWP 5341)]
[New Thread 0x7fffd87f8700 (LWP 5342)]
[New Thread 0x7fffd7ff7700 (LWP 5343)]
[New Thread 0x7fffd77f6700 (LWP 5344)]
[New Thread 0x7fffd6ff5700 (LWP 5345)]
[New Thread 0x7fffd67f4700 (LWP 5346)]
[New Thread 0x7fffd5ff3700 (LWP 5347)]
[New Thread 0x7fffd57f2700 (LWP 5348)]
[New Thread 0x7fffd4ff1700 (LWP 5349)]
[New Thread 0x7fffd47f0700 (LWP 5350)]
[New Thread 0x7fffd3fef700 (LWP 5351)]
[New Thread 0x7fffd37ee700 (LWP 5352)]
[New Thread 0x7fffd2fed700 (LWP 5353)]
[New Thread 0x7fffd27ec700 (LWP 5354)]
[Thread 0x7fffe3890700 (LWP 5328) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe5093700 (LWP 5325)]
0x00005555555ca7a6 in log_bytes_out (r=<optimized out>, a=0x5555555d8ccc "") at mod_logio.c:102
102     mod_logio.c: 没有那个文件或目录.
(gdb)

**Comment by vapier** [comment]
if that's a coredump of your apache process and it was running mod_ssl, your private keys might be resident in the memory.  you should regenerate them if you care about them.

**Comment by icing** [comment]
Thanks for the information. I have identified one crash issue here locally for which I made a fix. Could you please give release v0.7.1 a test on your system? Thanks!

**Comment by icing** [comment]
OK, forget v0.7.1. I can reproduce the crash simply by enabling "mod_logio" which I had not before. Working on a fix...

**Comment by icing** [comment]
Please verfiy the fix with v0.7.2. Thanks!

**Comment by haohetao** [comment]
I tested the 0.7.2 version, it works very well.

**Comment by icing** [comment]
Thanks!
