### ISSUE TITLE
configure sets wrong CPPFLAGS (missing "-I")

### ISSUE THREAD

**Issue by rainerjung** [icing/mod_h2#3]
configure.ac line 95 missing "-I" in one place.

old:    CPPFLAGS="$CPPFLAGS $($APXS -q includedir) -I$($APXS -q APR_INCLUDEDIR)"
new:    CPPFLAGS="$CPPFLAGS -I$($APXS -q includedir) -I$($APXS -q APR_INCLUDEDIR)"

Thanks!

Rainer

**Comment by icing** [comment]
Thanks for the catch, change now in master.
