### ISSUE TITLE
mod_h2 and MPM

### ISSUE THREAD

**Issue by LPardue** [icing/mod_h2#30]
Hello,

I have spent the last few days tracking down an issue with mod_h2 0.5.6 running with Apache 2.4.12 and nghttp2 0.7.14 on CentOS 6. I think I have found the cause of the issue (use of `mpm_prefork_module`, explained further below) but I would like to improve my understanding of the area.

To start with a little background, we are building httpd, mod_ssl, libnghttp2 and mod_h2 using a customised build process parameters and. We diverge somewhat from the documented source builds or sandbox builds.

In deployment, the issue manifests when making a HTTP/2 request for both cleartext or encrypted. 

In cleartext, the client makes a request with HTTP/1.1 upgrade, we see the server respond with a 101 switching protocols, some SETTINGS frame but no data is ever sent and the response never completes. The server logs at debug level with some sanitisation are:

```
[h2:debug] h2_h2c.c: seeing h2c-14 upgrade invitation
[h2:debug] h2_conn.c h2_conn_process start
[h2:debug] h2_session.c: upgrading h2c session with HTTP2-Settings: AAMAABkAAQAAP__ -> (0)
[h2:debug] h2_stream.c: h2_stream(1-1): created
[h2:debug] h2_session.c: h2_session(1-1): opened
[h2:debug] h2_request.c: h2_request(1-1): created
[h2:debug] h2_request.c: h2_request(1): written request GET /index.html, host=[server IP]
[h2:debug] h2_workers.c: h2_workers: scheduling task(1-1)
[h2:debug] h2_stream.c: h2_stream(1-1): closing input
[h2:debug] h2_stream.c: h2_stream(1-1): end header, task GET /index.html
[h2:debug] h2_conn.c: h2_session(1): starting on :80
[h2:debug] h2_mplx.c: h2_mplx(1): trywait on data for 0.010000 ms)
[h2:debug] h2_mplx.c: h2_mplx(1): trywait on data for 0.020000 ms)
[h2:debug] h2_mplx.c: h2_mplx(1): trywait on data for 0.030000 ms)
[h2:debug] h2_mplx.c: h2_mplx(1): trywait on data for 0.040000 ms)
[snip]
[h2:debug] h2_mplx.c: h2_mplx(1): trywait on data for 200.000000 ms)
[repeats until client quits]
```

In encrypted, the client makes a request with h2-14 APLN ID, we see the server respond with h2-14 ALPN ID. Some SETTINGS frame but no data is ever sent and the response never completes. The server logs at debug level with some sanitisation are:

```
[ssl:debug] ssl_engine_io.c: SSL negotiated protocol: 'h2-14'
[h2:debug] h2_h2.c: protocol set va ALPN to h2-14
[ssl:debug] ssl_engine_io.c SSL NPN negotiated protocol '(null)'
[h2:debug] h2_conn.c h2_conn_main start
[h2:debug] h2_conn.c: h2_session(1): starting on :443
[h2:debug] h2_stream.c: h2_stream(1-1): created
[h2:debug] h2_session.c: h2_session: stream(1-1): opened
[h2:debug] h2_stream.c: h2_stream(1-1): closing input
[h2:debug] h2_stream.c: h2_stream(1-1): end header, task GET /index.html
[h2:debug] h2_stream.c: h2_stream(1-1): closing input
[h2:debug] h2_session.c: h2_stream(1-1): input closed
[h2:debug] h2_mplx.c: h2_mplx(1): trywait on data for 0.010000 ms)
[h2:debug] h2_mplx.c: h2_mplx(1): trywait on data for 0.020000 ms)
[h2:debug] h2_mplx.c: h2_mplx(1): trywait on data for 0.030000 ms)
[h2:debug] h2_mplx.c: h2_mplx(1): trywait on data for 0.040000 ms)
[snip]
[h2:debug] h2_mplx.c: h2_mplx(1): trywait on data for 200.000000 ms)
[repeats until client quits]
```
After some investigation, we found that httpd was configured to use `mpm_prefork_module`. Changing to `mpm_worker_module` prevented the issue from reoccurring, allowing both cleartext and encrypted HTTP/2 to work.

Checking the commit logs I can see that there has been some activity around MPM but no mention of `mpm_prefork_module`. Is it unsupported? Or would you have expected it to work? Is there perhaps some other factor that is combining to cause this issue?

Regards
Lucas

**Comment by LPardue** [comment]
As soon as this issue is raised I then find the Known Issues section that talks about prefork, added in eee59bc880e8d91500dfd0d2ccabdb0ab2adb4fa. 

It seems our version pre-dates this, so we were unfortunate not to have received the warning. Can you possibly provide any insight into the background that lead up to this becoming a known issue?

**Comment by icing** [comment]
Hi Lucas,

thanks for the detailed description. I had so far simply not looked deeper into why prefork being such a blocker, but will put this on my todo list now. Any fix will come on the latest version which requires a 1.0.x nghttp2. I hope that is not an issue. 

cheers, Stefan

**Comment by LPardue** [comment]
Hi Stefan,

Thanks for the feedback. There is no issue with a fix coming into a later version, we will keep an eye open for future developments.

In the meantime we will proceed with using mpm_worker so I am going to close this issue.

Regards
Lucas

**Comment by icing** [comment]
I had a rework of the scheduling / thread sync parts due to some concurrency issues. I ran the test suite with mpm_prefork afterwards and all is fine on my OS X and Ubuntu 14.04 LTS image. Perhaps you might want to give this version a test drive. Feedback welcome.

> Am 25.06.2015 um 12:45 schrieb Lucas Pardue <notifications@github.com>:
> 
> Closed #30.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

<green/>bytes GmbH
Hafenweg 16, 48155 Münster, Germany
Phone: +49 251 2807760. Amtsgericht Münster: HRB5782

**Comment by LPardue** [comment]
Hi Stefan,

Thanks for looking into this. I'll try and test your changes in out environment next week.

**Comment by icing** [comment]
Hi,

one thing I found in the meantime: without further config, mod_h2 only has 1 worker thread in prefork per connection. you might want to raise this by H2WorkersMax (look up the spelling :)

**Comment by LPardue** [comment]
Hi Stefan,

I've tested setting `H2MaxWorkers` with our mod_h2 0.5.6 install when using mpm_prefork. I can confirm that setting a value >= 1 results in the server responding correctly. Setting a value of 0causes the stalling behaviour described before.  Should 0 be allowed/supported?)

**Comment by icing** [comment]
Hi Lucas,

thanks for the test. I agree that a value of 0 makes no sense here and should be a config error.

I will add also some advice on how this config value relates to the chosen mpm and make the default more gracious.

> Am 29.06.2015 um 12:13 schrieb Lucas Pardue <notifications@github.com>:
> 
> Hi Stefan,
> 
> I've tested setting H2MaxWorkers with our mod_h2 0.5.6 install when using mpm_prefork. I can confirm that setting a value >= 1 results in the server responding correctly. Setting a value of 0causes the stalling behaviour described before. Should 0 be allowed/supported?)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

<green/>bytes GmbH
Hafenweg 16, 48155 Münster, Germany
Phone: +49 251 2807760. Amtsgericht Münster: HRB5782
