### ISSUE TITLE
Error on apache configuration

### ISSUE THREAD

**Issue by jacopocappelli1989** [icing/mod_h2#32]
I've tried to use module with Apache but i have this error:
With this:
h2.load
LoadModule h2_module /usr/lib/apache2/modules/mod_h2.so

apache2: Syntax error on line 141 of /etc/apache2/apache2.conf: Syntax error on line 3 of /etc/apache2/mods-enabled/h2.load: Cannot load /usr/lib/apache2/modules/mod_h2.so into server: libnghttp2.so.14: cannot open shared object file: No such file or directory
Action 'configtest' failed.

With other configuration:
h2.load
LoadModule nghttp2_module /usr/lib/apache2/modules/libnghttp2.so.14
LoadModule h2_module /usr/lib/apache2/modules/mod_h2.so

I get this:
apache2: Syntax error on line 141 of /etc/apache2/apache2.conf: Syntax error on line 2 of /etc/apache2/mods-enabled/h2.load: Can't locate API module structure `nghttp2_module' in file /usr/lib/apache2/modules/libnghttp2.so.14: /usr/lib/apache2/modules/libnghttp2.so.14: undefined symbol: nghttp2_module
Action 'configtest' failed.

Someone can help me?

Thanks

**Comment by covener** [comment]
You'd use LoadFile on the libnghttp2.so.14 since it is not an Apache module.

**Comment by jacopocappelli1989** [comment]
Fantastic now i'have loaded everything but with H2Engine on on virtualhost an HTTP2 checker say me that i don't have http2 enabled.

Thanks,
J

**Comment by icing** [comment]
Your httpd.conf configuration file or at least the one on the virtualhost needs to specify a

> H2Engine on

somewhere. Otherwise mod_h2 will do nothing.

**Comment by icing** [comment]
With a http2-enabled curl, you can

> curl -kv --http2 https://<server>/

and see how the negotiation went. Otherwise a

> LogLevel h2:trace1

will error_log how, when and with what outcome mod_h2 was involved in a new connection.

**Comment by tngl** [comment]
Hello, another question:

I have compiled using sandbox mode and tried to move mod_ssl.so directly to my own initial apache setup but when I restart apache I get this error:

apache2: Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line 2 of /etc/apache2/mods-enabled/ssl.load: Cannot load /usr/lib/apache2/modules/mod_ssl.so into server: /usr/lib/apache2/modules/mod_ssl.so: undefined symbol: SSL_CONF_CTX_finish

**Comment by tngl** [comment]
Hello, another question:

I have compiled using sandbox mode and tried to move mod_ssl.so directly to my own initial apache setup but when I restart apache I get this error:

apache2: Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line 2 of /etc/apache2/mods-enabled/ssl.load: Cannot load /usr/lib/apache2/modules/mod_ssl.so into server: /usr/lib/apache2/modules/mod_ssl.so: undefined symbol: SSL_CONF_CTX_finish

**Comment by tngl** [comment]
Is my problem libssl related? Can I use the in sandbox complied mod_ssl is it is? Or do I need compile new apache?

**Comment by jfmcbrayer** [comment]
It's probably that you have a different version of Apache from the one in the sandbox.

**Comment by tngl** [comment]
Would it work if I upgrade to 2.4.16. ?

**Comment by tngl** [comment]
How do I compile mod_ssl for Apache 2.4.12?

**Comment by tngl** [comment]
Is it "httpd-2.4.12-alpn-v5.patch" I will use to compile mod_ssl? Do I need comply anything else?

**Comment by tngl** [comment]
Have recompiled with 2.4.12 and lower version os openssl, but it seems I must install 2.4.16 for alpn ?

**Comment by tngl** [comment]
Do I need to patch 2.4.16?

**Comment by tngl** [comment]
complied it again with latest openssl now getting this:

Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line 2 of /etc/apache2/mods-enabled/ssl.load: Cannot load /usr/lib/apache2/modules/mod_ssl.so into server: /usr/lib/apache2/modules/mod_ssl.so: undefined symbol: SSL_CONF_CTX_free

Must I recomplie apache with patch?

**Comment by jacopocappelli1989** [comment]
Please use this issue for real issue and not for problem of ssl compiling.
If you want to recompile apache follow this guide: http://blog.ivanristic.com/2013/08/compiling-apache-with-static-openssl.html

Thanks,
J

**Comment by tngl** [comment]
I will, thanks

**Comment by icing** [comment]
Closing. (Anyway, the mod_ssl.so is a loading error you see when the systems links in an older version of openssl at startup of httpd. Not the one you compiled mod_ssl with.)
