### ISSUE TITLE
Duplicate headers shown when using mod_proxy_fcgi

### ISSUE THREAD

**Issue by cfhay** [icing/mod_h2#35]
When using mod_h2, Chrome receives duplicate headers, from everything served via mod_proxy_fcgi (using event MPM).

Double `cache-control` lines, double `expires` fields, double `strict-transport-security`, double `x-powered-by` etc.

The problem breaks a webpage when `content-encoding` `gzip` is added, as Chrome will think the site is double encoded with gzip (`ERR_CONTENT_DECODING_FAILED`), which is not the case.

Configuration:

```
<FilesMatch "\.php$">
    SetHandler "proxy:unix:/run/php-fpm.sock|fcgi://localhost/"
</FilesMatch>
```

**Comment by icing** [comment]
Ok, I would like you to try two things:
 1. Enable `H2SerializeHeaders on` on your server and see if the problem persists
 1. Enable `LogLevel h2:trace1`on the server and make such a duplicate header request. Please mail me the relevant parts of logs/error_log at icing(at)apache.org (since they might contain sensitive information, better not attache them here...)

Thanks!

**Comment by cfhay** [comment]
`H2SerializeHeaders on` fixed the problem, thanks. Sent you an e-mail, when logging is on, and serialization is off.

**Comment by icing** [comment]
Thanks, I see in the log that a filter of mod_h2 is installed twice where it should only be there once. I setup a php-fpm and tried to reproduce the bug, but no success. Anything else noteworthy in your config? Some other filters configured?

**Comment by cfhay** [comment]
Using Apache 2.4.16. mod_h2 in the config is referenced only once. Using this config:

LoadModule h2_module modules/mod_h2.so

H2Engine on
H2Direct on
H2HackMpmEvent on

Using 0.8.0 of mod_h2, apache and mod_h2 is packed as a Gentoo Linux ebuild. If I will have some time, I'll try with stock apache and stock mod_h2.

**Comment by icing** [comment]
Hmm, checking my code. A apache hook seems to be called twice which I have not understood. Can I ask you to send me a log with

> LogLevel h2:trace2

again (serialize off)? Thanks!

**Comment by cfhay** [comment]
Sent you the e-mail.

**Comment by icing** [comment]
Can you check the v0.8.1 if it fixes the duplicate header problem? Thanks!

**Comment by cfhay** [comment]
Yes, duplicate headers gone with 0.8.1. Thanks!
