### ISSUE TITLE
mod_h2 installed and enabled - connection still http 1.1

### ISSUE THREAD

**Issue by castles** [icing/mod_h2#36]
I've installed spdylay, nghttp2 and mod_h2 and enabled it in apache 2.4.7. Its showing up in my phpinfo() but the server isn't using it. Am I missing an extra step? I have tried adding "H2Engine on" to the vhost file.

**Comment by icing** [comment]
Which clients are you testing with? If you have a http2-enabled curl, you might get more info via

> curl -kvv --http2 https://<server>/

which tells how negotiation worked, what was offered, what was chosen.

**Comment by castles** [comment]
I was testing with chrome and firefox and viewing the protocol in the net panel of dev tools/firebug. I also tested it using this.. "nghttp -nv https://domain.com.au" but I wasn't sure if that would work. I'll see if I can get curl http2 working.

**Comment by icing** [comment]
Ah, a public url! The output from curl is:

* Rebuilt URL to: https://domain.com.au/
*   Trying 54.66.130.84...
* Connected to domain.com.au (54.66.130.84) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol

which looks to me as
- you have an openssl with ALPN support
- you have an unpatched mod_ssl that does nothing with it.

You need a mod_ssl with the patch supplied that is in the sandbox build, unfortunately. 

//Stefan

> Am 20.07.2015 um 15:24 schrieb Marc <notifications@github.com>:
> 
> I was testing with chrome and firefox and viewing the protocol in the net panel of dev tools/firebug. I also tested it using this.. "nghttp -nv https://domain.com.au" but I wasn't sure if that would work. I'll see if I can get curl http2 working.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

<green/>bytes GmbH
Hafenweg 16, 48155 Münster, Germany
Phone: +49 251 2807760. Amtsgericht Münster: HRB5782

**Comment by castles** [comment]
ahh sorry.. that wasn't the real url.. I just made that up. The publc url isn't live yet.. I've been testing the site via editing my hosts file.

**Comment by castles** [comment]
If you would like to try it the IP is 52.64.75.228 and domain: customprintz.com.au

**Comment by icing** [comment]
It looks the same as the other. The server did not select a protocol, so the clients continue with "http/1.1".

I assume that this is an unpatched mod_ssl...

> Am 20.07.2015 um 15:41 schrieb Marc <notifications@github.com>:
> 
> customprintz.com.au

<green/>bytes GmbH
Hafenweg 16, 48155 Münster, Germany
Phone: +49 251 2807760. Amtsgericht Münster: HRB5782

**Comment by castles** [comment]
ahh, my mistake. I overlooked that. I'll try the patch in the morning. Thanks!

**Comment by castles** [comment]
I've had a go at getting this to work but I think I'll give up for now. I might wait till a module is shipped with apache. Is there any estimate on timeframe for this?

**Comment by icing** [comment]
Understood. It can be a bit tricky to get the right mix of modules and libs behaving together. 

A 2.4 release of httpd that includes mod_h2 could happen late summer. But I cannot promise anything, of course. 

Just out of curiosity: what was the thing that proved to be a showstopper for you?

**Comment by castles** [comment]
I managed to get mod_ssl patched and apache built from source. When I started apache and navigated to a basic html page it still wasn't showing up as http2. I think I might of had the wrong version of nghttp2
