### ISSUE TITLE
tls record size and buffering latency on apache 2.4x

### ISSUE THREAD

**Issue by tngl** [icing/mod_h2#37]
Is it any way to setup mod-spdy on apache according to this article?
https://www.igvita.com/2013/10/24/optimizing-tls-record-size-and-buffering-latency/

**Comment by icing** [comment]
You can play around with the following 2 directives:

H2BufferSize <bytes>      maximum bytes buffered before flushing out
H2BufferWriteMax <bytes>  when flushing maximum size of SSL records written

Cheers,

  Stefan

> Am 24.07.2015 um 15:02 schrieb tngl <notifications@github.com>:
> 
> Is it any way to setup mod-spdy according to this article?
> https://www.igvita.com/2013/10/24/optimizing-tls-record-size-and-buffering-latency/
> 
> —
> Reply to this email directly or view it on GitHub.
> 

<green/>bytes GmbH
Hafenweg 16, 48155 Münster, Germany
Phone: +49 251 2807760. Amtsgericht Münster: HRB5782

**Comment by tngl** [comment]
The wait time is still very long.

![h2](https://cloud.githubusercontent.com/assets/13484205/8875616/c906ea3a-321a-11e5-8ff8-f5deba8825a6.png)

**Comment by icing** [comment]
What is your configuration? MPM, SSL Stapling, ...

> Am 24.07.2015 um 15:44 schrieb tngl <notifications@github.com>:
> 
> The wait time is still very long.
> 
> 
> 
> —
> Reply to this email directly or view it on GitHub.
> 

<green/>bytes GmbH
Hafenweg 16, 48155 Münster, Germany
Phone: +49 251 2807760. Amtsgericht Münster: HRB5782

**Comment by tngl** [comment]
Without SSL Stapling

<IfModule mpm_prefork_module>
StartServers       2
MinSpareServers    2
MaxSpareServers    6
        MaxRequestWorkers         150
        MaxConnectionsPerChild   0
</IfModule>

**Comment by tngl** [comment]
A little bit better now with prefetch but now support for it in Safari

![skarmavbild 2015-07-25 kl 19 41 31](https://cloud.githubusercontent.com/assets/13484205/8890544/3e6c3416-3305-11e5-9405-4ae73a14d3c7.png)

**Comment by tngl** [comment]
Firefox Dev Tools show the following for graph.facebook.com (SPDY 3.1), is it making multiple connection instead of one?

![skarmavbild 2015-07-26 kl 18 35 15](https://cloud.githubusercontent.com/assets/13484205/8894861/511eda94-33c5-11e5-85bc-decd41c4e845.png)

**Comment by tngl** [comment]
Another question - is it recommended to use relative links or absolute links for static resources on them same sever/path?

**Comment by igrigorik** [comment]
@icing some info on dynamic sizing in GFE: https://issues.apache.org/jira/browse/TS-2503?focusedCommentId=14174163&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14174163 -- same logic now available in HAProxy + ATS.

**Comment by tngl** [comment]
Will Apache suport "Dynamic TLS record sizing"?

I watched my website (with Facebook Feed and some Google fonts) with Wireshark and I saw Google seems to use a dynamic sizing while Facebook uses static (without OCSP stapling).

How much can this affect the browser loading speed?

**Comment by tngl** [comment]
Also I am using mod_ssl_npn.so from mod_spdy (https://github.com/eousphoros/mod-spdy), is it compatible with this versions of H2? Thanks for any answer or advice.

**Comment by icing** [comment]
The eousphiros repository was very helpful to get mod_spdy working for me.  However NPN is old, was experimental and is now replaced by ALPN. 

It should work with mod_h2, but I have not verified this for some time. But ALPN negotiaton will then not work.

**Comment by tngl** [comment]
I did not compile sandbox (didn't work for me either).

How can I compile your ALPN version?

Many thanks.

**Comment by tngl** [comment]
Terminate TLS sessions early, how important is it?

**Comment by tngl** [comment]
Hello, another question:

I have compiled using sandbox mod and tried to move mod_ssl.so to my initial setup but when I restart apache I get this error:

apache2: Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line 2 of /etc/apache2/mods-enabled/ssl.load: Cannot load /usr/lib/apache2/modules/mod_ssl.so into server: /usr/lib/apache2/modules/mod_ssl.so: undefined symbol: SSL_CONF_CTX_finish

**Comment by tngl** [comment]
Is there any good explanation for this?

Without h2:

![without h2](https://cloud.githubusercontent.com/assets/13484205/9028478/8c42bfb8-397a-11e5-880c-f08e08da4135.png)

With h2:
![with h2](https://cloud.githubusercontent.com/assets/13484205/9028479/8e3fa06a-397a-11e5-9c5f-7bd772be21d2.png)

**Comment by tngl** [comment]
New test with native speed/connection, I should be happy?

Still no ALPN, it is dependent on openssl 1.0.2? Hope to see an upgraded httpd build soon.

![skarmavbild 2015-08-04 kl 00 46 38](https://cloud.githubusercontent.com/assets/13484205/9049500/fb3295f6-3a42-11e5-942f-57d8053fb1be.png)

**Comment by antdes45** [comment]
Got mod_h2 working today on ubuntu 15.04. 

Latest version of mod_ssl_npn from mod-spdy repo will work with mod_h2.
You can use mod_ssl.so from the sandbox, but you'll need to use openssl 1.0.2. 

Note that mod_spdy doesn't work with any new browsers as spdy/3 is obsolete. Chrome and Firefox only have spdy/3.1 support now. If you recompile mod_spdy with the spdy/3.1 flag, requests will work again even though the module is not supposed to support 3.1.
