### ISSUE TITLE
Compiling mod_h2 on FC16.

### ISSUE THREAD

**Issue by cgskumar77** [icing/mod_h2#39]
Hi,
I'm trying to compile mod_h2 and am unable to do that. Admittedly, I'm using FC16 while you have tested it on Ubuntu. Is there a known way I can make it work on FC16? Or maybe, I'm missing something else here. Please find below what I did.

Any help would be appreciated.

Thanks,

$ git clone https://github.com/icing/mod_h2
$  uname -a
Linux pc-dev5 3.6.11-4.fc16.x86_64 #1 SMP Tue Jan 8 20:57:42 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
$ su -
root# yum install autoconf
Loaded plugins: langpacks, presto, refresh-packagekit
Package autoconf-2.68-2.fc15.noarch already installed and latest version
Nothing to do
root# logout
$ autoreconf -i
configure.ac:16: error: Autoconf version 2.69 or higher is required
configure.ac:16: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: /usr/bin/autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63
$

**Comment by jfmcbrayer** [comment]
Fedora 16 is way old. I'm building it on Fedora 21, and it's straightforward as long as you install all of the dependencies.

**Comment by icing** [comment]
Thanks jf. Closing this.
