### ISSUE TITLE
trouble with mod_h2 domain.tld to www.domain.tld redirect

### ISSUE THREAD

**Issue by chani** [icing/mod_h2#40]
Hello,

I am looking for a fix or work-around which would solve the problem that due to connection-reusing a "400 Bad Request" is sent to the browser. Is there a fix planned? How do others work around that? I've already took a look at https://github.com/icing/mod_h2/issues/34 and https://github.com/icing/mod_h2/issues/27 

I've applied the patch manually (Apache 2.4.7) but still a 400 is returned. As soon as I redirect from domain.tld to www.domain.tld that happens. If I restart the webserver or close and re-open my browser www.domain.tld works fine. I've tried to add a vhost with H2Engine off for domain.tld which seems to make the initial redirect work, trying to switch back still results in a 400.

P.S: Apart from the above problems, nice work. Seems to work good.

Thanks in advance

**Comment by icing** [comment]
Apache needs the sni_misdirect.patch from the sandbox for such a setup. Although that does not solve the problem very nicely.

httpd, by default, does not - on a TLS connection - allow requests for other hosts than the initial one. Such requests are answered with a 400. That's part of Apache core. The patch changes that to a return code of 421, which the browser interprets as "i need to open a new connection".

However, browsers do not really like this and close the existing connection before opening a new one. If you have lots if mixed resources from both hosts on the same page, the performance might degrade considerably.

**Comment by chani** [comment]
Hello,

the problematic part is, that I do have added the patch and the Server (according to google chrome's developer console and firebug in Firefox) still returns a 400 and not a 421. By chance, any Idea how google does it?

If I visit www.google.com I can see the http2 indicator. If i remove the www I am not getting a 400 but I am redirected properly. According to wget they do send a 302 instead of 301 as I do. I'll check that.

**Comment by chani** [comment]
Does not work with 302 neither. Would be pretty interesting how google does that.

**Comment by icing** [comment]
Hmm. If the 400 is coming from a mismatched SNI/Host-Header pair, mod_ssl logs an error mentioning both names.
If there is some other mistake, there is something else wrong. You should raise the LogLevel, repeat the test and inspect the error log. If you want to attach that here, please make sure that no private data is in it.

**Comment by icing** [comment]
Added as enhancement #57
