### ISSUE TITLE
Cannot load modules/mod_h2.so into server: libnghttp2.so.14: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kdbdallas** [icing/mod_h2#41]
I have installed mod_h2, and nghttp2-1.1.2 and configured everything as the install files say, however when I test my Apache configs with: sudo /usr/local/apache2/bin/apachectl configtest  I get the following error:

httpd: Syntax error on line 158 of /usr/local/apache2/conf/httpd.conf: Cannot load modules/mod_h2.so into server: libnghttp2.so.14: cannot open shared object file: No such file or directory

If I run: locate libnghttp2.so I get the following results:

/usr/local/lib/libnghttp2.so
/usr/local/lib/libnghttp2.so.14
/usr/local/lib/libnghttp2.so.14.0.6
/usr/local/src/nghttp2-1.1.2/lib/.libs/libnghttp2.so
/usr/local/src/nghttp2-1.1.2/lib/.libs/libnghttp2.so.14
/usr/local/src/nghttp2-1.1.2/lib/.libs/libnghttp2.so.14.0.6

So obviously libnghttp2.so.14 does exist.

mod_h2.so/mod_h2.so.0.0.0 is in /usr/local/apache2/modules

Have added: 
LoadModule h2_module modules/mod_h2.so
H2Engine on
In my apache's conf/httpd.conf file

Am I missing something?

Is there a way to specify where libnghttp2.so.14 is so it won't have this problem?

Thanks?

**Comment by covener** [comment]
First, make sure your lib is the same architecture/bits as httpd (/usr/bin/file on mod_h2 and libnghttp2) .  Try specifying LD_LIBRARY_PATH/LIBPATH/??? in apachectl's bin/envvars script to make sure /usr/local/lib is in your shared library search path.

**Comment by kdbdallas** [comment]
setting the envvar worked! Thank you!

**Comment by lanshunfang** [comment]
Or, try to run `sudo ldconfig`

**Comment by tylercb** [comment]
@kdbdallas What envvars did you end up setting? I'm having a similar issue...

**Comment by lanshunfang** [comment]
@tylercb may want to give my sudo ldconfig a shot

**Comment by hoang-tranviet** [comment]
@lanshunfang 
`sudo ldconfig` works. Thanks!
