### ISSUE TITLE
mod_h2 Compile Error

### ISSUE THREAD

**Issue by stopbox** [icing/mod_h2#42]
I'm currently having this issue trying to compile
https://gist.github.com/stopbox/3090ce89d546b4852e31

**Comment by icing** [comment]
The problem is that the apache build finds the old header files in /usr/include. If you remove the installed http*.h, it should make without errors.

**Comment by stopbox** [comment]
Gives me this now

<addr>
  Making all in mod_h2
make[1]: Entering directory `/root/mod_h2/mod_h2'
  CC       mod_h2_la-h2_alt_svc.lo
h2_alt_svc.c:18:23: fatal error: http_core.h: No such file or directory
 #include <http_core.h>
                       ^
compilation terminated.
make[1]: *** [mod_h2_la-h2_alt_svc.lo] Error 1
make[1]: Leaving directory `/root/mod_h2/mod_h2'
make: *** [all-recursive] Error 1
</addr>

**Comment by icing** [comment]
Ok, how is your mod_h2 configured? Have you looked at the README.md to check the new changes and Apache httpd patch?

**Comment by stopbox** [comment]
I just cannot get this to work for now i'm closing the issue

**Comment by EatSalad** [comment]
Hi !
I get the same compilation error, and i didn't understand where to delete http*.h

**Comment by icing** [comment]
People, when analyzing computer problems, one needs the actual output where it fails. And the context of what you are doing. Which version do you try to compile, how have you configured it, etc.

Otherwise, my only answer can be: it works here for me.

**Comment by EatSalad** [comment]
You're right...

Exact same output as stopbox (https://gist.github.com/stopbox/3090ce89d546b4852e31)

I clone and follow your words ( https://github.com/icing/mod_h2 ) 5 minutes ago
Install a fresh `nghttp2`, wasn't installed on Centos 7 by default.

Then tried to compile `mod_h2`, I get those errors.
I read *how to h2 in apache* ( https://icing.github.io/mod_h2/howto.html#build )

Here's some stuff that can probably help us :

```
> apachectl -V
Server version: Apache/2.4.6 (CentOS)
Server built:   Jan 12 2015 13:22:31
Server's Module Magic Number: 20120211:23
Server loaded:  APR 1.4.8, APR-UTIL 1.5.2
Compiled using: APR 1.4.8, APR-UTIL 1.5.2
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/sbin/suexec"
 -D DEFAULT_PIDLOG="/run/httpd/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"

> cat /etc/*release*
CentOS Linux release 7.0.1406 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CentOS Linux release 7.0.1406 (Core) 
CentOS Linux release 7.0.1406 (Core) 
cpe:/o:centos:centos:7

> apachectl -M
Loaded Modules:
 core_module (static)
 so_module (static)
 http_module (static)
 access_compat_module (shared)
 actions_module (shared)
 alias_module (shared)
 allowmethods_module (shared)
 auth_basic_module (shared)
 auth_digest_module (shared)
 authn_anon_module (shared)
 authn_core_module (shared)
 authn_dbd_module (shared)
 authn_dbm_module (shared)
 authn_file_module (shared)
 authn_socache_module (shared)
 authz_core_module (shared)
 authz_dbd_module (shared)
 authz_dbm_module (shared)
 authz_groupfile_module (shared)
 authz_host_module (shared)
 authz_owner_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cache_module (shared)
 cache_disk_module (shared)
 data_module (shared)
 dbd_module (shared)
 deflate_module (shared)
 dir_module (shared)
 dumpio_module (shared)
 echo_module (shared)
 env_module (shared)
 expires_module (shared)
 ext_filter_module (shared)
 filter_module (shared)
 headers_module (shared)
 include_module (shared)
 info_module (shared)
 log_config_module (shared)
 logio_module (shared)
 mime_magic_module (shared)
 mime_module (shared)
 negotiation_module (shared)
 remoteip_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 slotmem_plain_module (shared)
 slotmem_shm_module (shared)
 socache_dbm_module (shared)
 socache_memcache_module (shared)
 socache_shmcb_module (shared)
 status_module (shared)
 substitute_module (shared)
 suexec_module (shared)
 unique_id_module (shared)
 unixd_module (shared)
 userdir_module (shared)
 version_module (shared)
 vhost_alias_module (shared)
 dav_module (shared)
 dav_fs_module (shared)
 dav_lock_module (shared)
 lua_module (shared)
 mpm_prefork_module (shared)
 proxy_module (shared)
 lbmethod_bybusyness_module (shared)
 lbmethod_byrequests_module (shared)
 lbmethod_bytraffic_module (shared)
 lbmethod_heartbeat_module (shared)
 proxy_ajp_module (shared)
 proxy_balancer_module (shared)
 proxy_connect_module (shared)
 proxy_express_module (shared)
 proxy_fcgi_module (shared)
 proxy_fdpass_module (shared)
 proxy_ftp_module (shared)
 proxy_http_module (shared)
 proxy_scgi_module (shared)
 ssl_module (shared)
 systemd_module (shared)
 cgi_module (shared)
 fcgid_module (shared)
 php5_module (shared)
```

**Comment by icing** [comment]
Ok, how did you configure your checkout of mod_h2?

(Also, current mod_h2 is behind to what has been released in Apache 2.4.17. You're aware of that? You will not be able to compile the github version and just put it into your CentOS 2.4.6 server. We can save ourselves some time, if you want to do that...)

**Comment by EatSalad** [comment]
> current mod_h2 is behind to what has been released in Apache 2.4.17. You're aware of that?

No, i wasn't
> You will not be able to compile the github version and just put it into your CentOS 2.4.6 server

Ok
> We can save ourselves some time, if you want to do that...

I wish but :

This server run prod and dev website, so if i do an upgrade of apache (from 2.4.6 to 2.4.17) How can I be 100% sure that everything work fine. And if not, how can I easily go backward on my install :/

This is why I tried to install it on 2.4.6 (... well, you probably think it was dumb ... I can't blame you)

**Comment by icing** [comment]
Nothing dumb about it. But mod_h2 has become part of Apache 2.4.17 (see the README.md) 
and has been renamed to mod_http2. It relies on changes inside Apache itself that ship
with 2.4.17. That is the reason why you cannot put it into an older server.

In your case, and for a production system, I would wait for the CentOS guys to
integrate 2.4.17 into their update line, so you get it via that.

//Stefan

**Comment by EatSalad** [comment]
Well, I suppose you're right ...
Nothing about h2 will be done on servers today but thank you for the answer anyway =)
