### ISSUE TITLE
Feature: implement priority scheduling

### ISSUE THREAD

**Issue by icing** [icing/mod_h2#46]
With nghttp2 exposing the dependency and priority information in its API, implement a priority scheduling in h2_mplx so that the task with the highest priority is assigned to the next available worker.

**Comment by igrigorik** [comment]
@icing for reprioritization, I'm guessing once/if the worker picks up a task it'll run to completion, but it may be possible to reorder tasks that have not (yet) been assigned?

**Comment by icing** [comment]
Ilya, yes, for each http2 session (e.g. connection) there is a queue of open streams that need assignement to a worker thread. When the next worker becomes available, the session would select the stream with the highest priority for processing.

This does not influence streams from different sessions, e.g. the balancing of all connections with work to do stays basically fair.

Once a stream is being processed, it will be done so until it has finished. Priority however will still determine which streams data is written to the client. If a super-high stream gets opened and assigned to a worker, and has data available, it will stall all ongoing responses on that connection.

**Comment by icing** [comment]
Implemented in trunk.

**Comment by icing** [comment]
Available for testing in v1.0.3

**Comment by icing** [comment]
Released.
