### ISSUE TITLE
Feature: mpm modules interworking

### ISSUE THREAD

**Issue by icing** [icing/mod_h2#52]
In Apache httpd 2.4, interworking with the `mpm`modules `worker`, `prefork` and `event` has been verified with `event` being the picky one. There is a special hack for the last one included in `mod_h2` that needs to be integrated with `event` in a better maintainable and performant way.

In Apache httpd 2.5.-DEV there are other multi-processing modules, e.g. `motorz` that need to be checked for interworking with `mod_h2`.

**Comment by icing** [comment]
Interworking with ```worker```, ```prefork``` and especially ```event``` has been improved. ```event``` still has room for further improvements. Key here would be to move part of the IO activity into the connection filters.

```motorz``` seems to be highly experimental for now. Interworking with mod_http2 has not been achieved yet as of now.

**Comment by lkraav** [comment]
Thanks for all the hard work here. How far away is 2.4.18 from release? On my configuration, 2.4.17 + `event` has not performed well, with everyday workloads sooner or later resulting in hanging connections. I see a lot of work has gone in since then, would it make sense to wait until 2.4.18 or is that too far away so the effort of custom-patching 2.4.17 from this repo is worth it?

**Comment by icing** [comment]
Yeah, event still has room for improvement, worker gives currently better results. But event will be better in 2.4.18 together with http2.

2.4.18 will be tagged next week, then some testing internally and hopefully releases soon after that. This repository has not the latest changes. I would advise to checkout the Apache httpd repository ```branches/2.4.x```and build from there if you cannot wait.

**Comment by lkraav** [comment]
With Gentoo ebuilds it makes best sense to apply a specific patchset to a known release tag tree state. So what you have been providing in this repo has worked well. But if current state here is a bit behind and 2.4.18 is close, I'll wait that out.

**Comment by icing** [comment]
Improved scoreboard updates in v1.0.13.

**Comment by icing** [comment]
Interworking improvements have been implemented in trunk and backported to 2.4.x. Will be available here in next release.

**Comment by lkraav** [comment]
Numerous graceful restarts have been going over smoothly on 2.4.23, compared to early days where things just hung up, so this must be working correctly indeed :)

**Comment by icing** [comment]
:-) Thanks for the feedback!
