### ISSUE TITLE
Feature: update request protocol handler

### ISSUE THREAD

**Issue by icing** [icing/mod_h2#56]
The stream requests in mod_h2 are currently made to look like HTTP/1.1 requests. For example `r->protocol` is given that value. This was done to preserve backward compatibility for applications that
may access this value via `$SERVER_PROTOCOL`.

This needs to show the real protocol name (which is what? `HTTP/2`?) and mod_h2 needs a directive to give "old" applications which puke on new values the original settings. Default in 2.4 versions should be backward compatible.

**Comment by lkraav** [comment]
I was always confused to see HTTP/1.1 in all `access_log`s

**Comment by jfcalcerrada** [comment]
Yes, that's breaking my PHP app, as I relay on that to store the request and do test and analysis afterwards.

I have another machine with H2O, they set the value to 'HTTP/2'.

**Comment by icing** [comment]
Not many legacy php apps on H2O... ;-)

**Comment by svarvel** [comment]
I am attempting to set its value based on the results from the NPN/ALPN negotiation. Currently this is set in h2_task.c {h2_task_create_request ; r->protocol = (char*)"HTTP/1.1";}.; Function "h2_task_create_request" was originally called in "h2_task_process_request" and its returned value is of type "request_rec" which is then passed to <<ap_process_request(r);>>. I think this is where this information propagates to Apache, but there I get lost...

I then tried to do such setting within "h2_h2_post_read_req(request_rec *r)" reading the protocol negotiated from ctx {(char*)ctx->protocol;}, where h2_ctx *ctx = h2_ctx_rget(r, 0). Unfortunately this is always NULL, so this probably happens before ALPN/NPN negotiation?  

Unrelated -- I cannot get all output logs which would help understanding when ALPN/NPN negotiation is done. I setup my <<httpd.conf>> as follows:  

ErrorLog "logs/error_log"
LogLevel warn
LogLevel h2:trace1

**Comment by icing** [comment]
Please try v0.9.8 which will show "HTTP/2" as SERVER_PROTOCOL, unless `H2SerializeHeaders` is in effect.

**Comment by svarvel** [comment]
Thanks. Is it gonna report H2 even when H1 is used though?

**Comment by icing** [comment]
Not unless there is a bug not caught by the tests,

**Comment by svarvel** [comment]
ah ok, I will play with it then and let u know. Many thanks!

**Comment by svarvel** [comment]
Apparently we have an ad-hoc setup here, and they are having issues updating. I am so thinking to start a brand new installation using apache2.5. Got the code and I see they are using mod_h2 vrs "0.9.7". Do you know if this issue is solved already in that version?

**Comment by icing** [comment]
I keep the module code identical, just did not bump the version number in httpd/trunk.

**Comment by icing** [comment]
Implemented since 0.9.8
