### ISSUE TITLE
Feature: Allow reusing connection between hosts with same SSL configuration

### ISSUE THREAD

**Issue by CamaroSS** [icing/mod_h2#57]
It would be very useful in case of applying HTTP/2 to the websites that have domain sharding implemented, and all of the subdomains are using the same SSL certificate. Currently the server will return 421 when a browser tries to reuse connection with www.domain.com and static.domain.com. This behavior can introduce a major performance impact.

**Comment by icing** [comment]
Currently in apache httpd/trunk: if hosts have exactly the same SSL configuration in regard to protocol, ciphers, certificates, keys and client verification, the request are processed. If SSL config varies, a 421 is returned.

**Comment by lkraav** [comment]
Is this going to backported to 2.4?

**Comment by icing** [comment]
I plan to have it in the next release.

**Comment by icing** [comment]
Available for testing in v1.0.3

**Comment by icing** [comment]
released in 2.4.18
