### ISSUE TITLE
Documentation: IE11 is not Edge

### ISSUE THREAD

**Issue by evaryont** [icing/mod_h2#60]
In your [howto](https://icing.github.io/mod_h2/howto.html) you have "HTTP/2 is supported in Internet Explorer 11 (Edge) which ships with Windows10.", however Microsoft Edge is a different, independent product (though based on) Internet Explorer. While Edge is indeed shipped with Windows 10, IE11 had shipped with Windows 8.1.

So, IE11 is a different and separate project than Edge. Both support HTTP/2, but only on Windows 10.

**Comment by icing** [comment]
Thanks for the notice. I admin, I am not very educated on microsoft product naming. I update the howto with the, hopefully, proper naming.

**Comment by v998** [comment]
@icing should that be "admit" ?

**Comment by icing** [comment]
...right. that is rect.
