### ISSUE TITLE
1.0.0: connections start infinitely hanging during ongoing parallel POST uploading workflow 

### ISSUE THREAD

**Issue by lkraav** [icing/mod_h2#62]
There seems to be a clear pattern that when on of our subcontractors starts doing an active image uploading session to WordPress media library, pretty soon after all new connections hang. Restarting `apache` helps immediately.

```
<IfDefine HTTP2>
LoadModule h2_module modules/mod_h2.so
Protocols h2 http/1.1
ProtocolsHonorOrder on
</IfDefine>
```
```
# event MPM
#
# MinSpareThreads: Minimum number of idle threads available to handle request spikes
# MaxSpareThreads: Maximum number of idle threads
# ThreadsPerChild: Number of threads created by each child process
<IfModule mpm_event_module>
    # http://mail-archives.apache.org/mod_mbox/httpd-users/201501.mbox/%3CCAHti5NFfMpWwd0LYchR1p4ZBvVSAPPQFVpmCg9ZZSLBQHWMviA@mail.gmail.com%3E
    # https://bz.apache.org/bugzilla/show_bug.cgi?id=53555#c14
    StartServers        1
    ServerLimit         5
    MinSpareThreads     25
    MaxSpareThreads     100
    ThreadsPerChild     200
    ThreadLimit         200
    MaxRequestWorkers   1000
    MaxConnectionsPerChild  100000
</IfModule>
```

**Comment by lkraav** [comment]
Aha, sweet, `apache-2.4.17` is out. Building that tomorrow, and seeing how that goes.

**Comment by lkraav** [comment]
Nope, connections still hang after an unknown period of work.

**Comment by lkraav** [comment]
Yeah, disabling `Protocols H2` fixes it.

**Comment by icing** [comment]
Not sure I understand properly: there is a php? app that accepts uploads. After an upload, all new connections hang.

* Is the upload itself working?
* do also new connection to static files / other vhosts hang?
* do new requests only hang for the client doing the upload or for all other users as well?

**Comment by lkraav** [comment]
Yes, PHP app, called WordPress :)

> Not sure I understand properly: there is a php? app that accepts uploads. After an upload, all new connections hang.
 
I'm not sure if "an upload". The person tried to to 5-10 parallel image upload POST requests, which WP allows doing in its UI. This guarantees a bunch of wildcard subdomains within this single relevant vhost shortly becoming inaccessible for everybody, incl. the uploader.

>    Is the upload itself working?

I think what's happening is that she starts 10 uploads, then somewhere in the middle connectivity to the host breaks.

>    do also new connection to static files / other vhosts hang?

Static file check is a good idea. Dynamic content is served through mod_fcgid and PHP-FPM.

>    do new requests only hang for the client doing the upload or for all other users as well?

Everybody. AFAICS a single vhost that hosts a wildcard subdomain partially locks up. Some subdomains in this same webhost still somehow stay accessible and WordPress continues serving these just fine. I have not tested mass-uploading in these accessible subdomains after the initial lockup has occurred.

====

Probably the thing to do is to increase logging verbosity, and look to reproduce this behavior.

**Comment by heintore** [comment]
@lkraav Did you ever find a workaround here? I'm experiencing the same issue on my WordPress site, and are getting the same errors in my logs. 

I initially thought it happened randomly without any specific cause, but after reading your description of the issue I'm pretty certain that WordPress uploads is causing the connection hangs for my site as well.

I just did a quick test to verify this, and indeed – uploading a bunch of photos to WordPress' media library makes my site unresponsive, for all users. As soon as the upload is done it all goes back to normal.

Here's an extract from my logs (the IP being mine when carrying out the test).

```
[Sat Nov 28 13:52:44.911489 2015] [http2:info] [pid 20613] [client 62.97.196.*:45163] h2_mplx(37): release_join, refs=1, waiting...
[Sat Nov 28 13:52:54.911724 2015] [http2:info] [pid 20613] [client 62.97.196.*:45163] h2_mplx(37): release_join, refs=1, waiting...
[Sat Nov 28 13:53:04.911913 2015] [http2:info] [pid 20613] [client 62.97.196.*:45163] h2_mplx(37): release_join, refs=1, waiting...
[Sat Nov 28 13:53:14.912075 2015] [http2:info] [pid 20613] [client 62.97.196.*:45163] h2_mplx(37): release_join, refs=1, waiting...
[Sat Nov 28 13:53:24.912286 2015] [http2:info] [pid 20613] [client 62.97.196.*:45163] h2_mplx(37): release_join, refs=1, waiting...
[Sat Nov 28 13:53:34.912442 2015] [http2:warn] [pid 20613] [client 62.97.196.*:45163] AH02952: h2_mplx(37): join attempts exhausted, refs=1```

(As a sidenote, I'm also seeing the errors without any files being uploaded, which really confuses me.)

@icing Please let me know if you want me to provide some additional information.

**Comment by lkraav** [comment]
Nope. I'm currently running 2.4.17 with `mod_h2` loaded, but HTTP/2 completely turned off, because it consistently lead to hung connections even outside of the workflow described above. Usually after a week of work or so, but no consistent pattern. Strange thing, restarts have also been needed with HTTP/2 turned off, because whatever `mod_h2` does with connections, something is still going wrong.

A lot of work has gone into 2.4.18, so I'm waiting for that release, will re-enable HTTP/2 and update this ticket with results after a week+ experience.

**Comment by heintore** [comment]
Thanks for the update! I'll disable `mod_h2` for now as well and see if that leads to a more stable environment.

Looking forward to 2.4.18, hopefully bugs like these (if it's _really_ related to `mod_h2` ...) will be squashed in that release :-)

**Comment by heintore** [comment]
@lkraav Now that 2.4.18 is out, have you had a chance to test if the timeout problem is still present? I'm reluctant to upgrade and reenable the mod on my production server, at least during daytime :-)

**Comment by lkraav** [comment]
Yes, my assistant has tested the workflow on 2.4.18 and I think situation has improved, because there were only occasional hangs, but they didn't need a server restart to resolve. We're *not* 100% in the clear yet, for sure. During active work (just general doing whatever on the development sites), sooner or later connections simply start to hang. It seems Ctrl+Shift+R sometimes manages to restore connectivity. After an undetermined amount of time (usually 1+ days minimum), people will start reporting "slow connecting" and "not connecting at all == infinite Waiting for response".

**Comment by lkraav** [comment]
I'd actually like to set up a limited size RAM-based debug logging facility, so I don't fill the FS with crap but we could still immediately jump in and review what state `mod_http2` is in, when any connectivity incident reports come in. Hopefully I'll find time to get to it soon. I'm not entirely sure how I would do this, either. Log file output on tmpfs and frequently logrotate it or is there a better way?

**Comment by icing** [comment]
The errors that heintore reported, the "join attempts exhausted", have been reworked in 2.4.18. It's that phase when a http2 connection closes and shuts down all its processing for that connection. That includes any sub-worker tasks, running in separate threads, which the main connection needs to join.

If worker tasks get blocked, never finish, the worker pool shrinks and shrinks until no http2 connection can make any progress. That is the lockup you have seen. At the time http/1.1 connection should still work.

With 2.4.18, connection shutdown and worker abort has been improved. In 2.4.17, not every time the client did reset a stream did this properly shutdown the worker. And there still seems trouble with it, from what lkraav reports. ;-(

Are you willing to test a alpha release of the module from here that you can drop into a 2.4.18 server without further patches?

**Comment by lkraav** [comment]
I am willing to test, yes. Would love to have that debug logging going as well, get constant monitoring availability.

**Comment by icing** [comment]
Ok, I'll see if I can give you something by tomorrow. Thanks.

**Comment by icing** [comment]
Please give the release 1.0.12 from github a try. You can build that for an Apache 2.4.18 and its apxs. 

New timeout configurations and extra checks for connection/worker cleanup.

**Comment by lkraav** [comment]
Here we go

```
==> error_log <==
[Fri Dec 18 20:20:21.026370 2015] [http2:info] [pid 17094:tid 140578447173504] mod_http2 (v1.0.12, nghttp2 1.3.4), initializing...
[Fri Dec 18 20:20:22.002516 2015] [mpm_event:notice] [pid 17094:tid 140578447173504] AH00489: Apache/2.4.18 (Unix) OpenSSL/1.0.2d mod_wsgi/4.4.9 Python/2.7.10 configured -- resuming normal operations
[Fri Dec 18 20:20:22.002556 2015] [core:notice] [pid 17094:tid 140578447173504] AH00094: Command line: '/usr/sbin/apache2 -D AUTHNZ_LDAP -D DEFAULT_VHOST -D HTTP2 -D INFO -D LDAP -D MACRO -D PHP5 -D PROXY -D SSL -D SSL_DEFAULT_VHOST -D STATUS -D USERDIR -D WSGI -D FOREGROUND'
```

First thing to note is that a ton of visible timeout notifications are constantly output
```
[Fri Dec 18 20:22:58.312070 2015] [http2:info] [pid 17601:tid 140576158480128] (70007)The timeout specified has expired: [client 10.24.0.57:37598] AH02950: h2_session(246): error reading, terminating
[Fri Dec 18 20:22:59.269595 2015] [http2:info] [pid 17112:tid 140576242407168] (70007)The timeout specified has expired: [client 192.168.1.111:35766] AH02950: h2_session(36): error reading, terminating
[Fri Dec 18 20:23:01.822461 2015] [http2:info] [pid 17601:tid 140576150087424] (70007)The timeout specified has expired: [client 62.65.199.210:57742] AH02950: h2_session(247): error reading, terminating
[Fri Dec 18 20:23:04.301451 2015] [http2:info] [pid 17112:tid 140576234014464] (70007)The timeout specified has expired: [client 88.196.189.184:58844] AH02950: h2_session(37): error reading, terminating
[Fri Dec 18 20:23:08.705116 2015] [http2:info] [pid 17112:tid 140576225621760] (70007)The timeout specified has expired: [client 10.24.0.57:37599] AH02950: h2_session(38): error reading, terminating
[Fri Dec 18 20:23:09.521542 2015] [http2:info] [pid 17601:tid 140576141694720] (70007)The timeout specified has expired: [client 192.168.1.111:35770] AH02950: h2_session(248): error reading, terminating
[Fri Dec 18 20:23:11.620131 2015] [http2:info] [pid 17601:tid 140576192050944] (70007)The timeout specified has expired: [client 192.168.1.126:53984] AH02950: h2_session(242): error reading, terminating
[Fri Dec 18 20:23:12.275515 2015] [http2:info] [pid 17112:tid 140576217229056] (70007)The timeout specified has expired: [client 62.65.199.210:57748] AH02950: h2_session(39): error reading, terminating
[Fri Dec 18 20:23:14.753148 2015] [http2:info] [pid 17601:tid 140576133302016] (70007)The timeout specified has expired: [client 88.196.189.184:58846] AH02950: h2_session(249): error reading, terminating
[Fri Dec 18 20:23:18.992736 2015] [http2:info] [pid 17601:tid 140576124909312] (70007)The timeout specified has expired: [client 10.24.0.57:37600] AH02950: h2_session(250): error reading, terminating
[Fri Dec 18 20:23:19.837484 2015] [http2:info] [pid 17112:tid 140576208836352] (70007)The timeout specified has expired: [client 192.168.1.111:35772] AH02950: h2_session(40): error reading, terminating
[Fri Dec 18 20:23:23.547175 2015] [http2:info] [pid 17601:tid 140576116516608] (70007)The timeout specified has expired: [client 62.65.199.210:57754] AH02950: h2_session(251): error reading, terminating
[Fri Dec 18 20:23:25.086784 2015] [http2:info] [pid 17112:tid 140576192050944] (70007)The timeout specified has expired: [client 88.196.189.184:58847] AH02950: h2_session(42): error reading, terminating
```

So I just restarted the server with the new build. Let's see how it holds up.

**Comment by lkraav** [comment]
> So I just restarted the server with the new build. Let's see how it holds up.

Timeouts seem to be too quick for a stable connection of long-polling XMPP client candy-chat. I think I gave @icing an account on my server, you should be able to easily see this.

**Comment by lkraav** [comment]
After some hours of work, connections suddenly got completely stuck for a few minutes. I'm constantly tailing all error + access logs and logging also stopped.

Then suddenly the mysterious blocker got relieved and pages started loading again.

**Comment by lkraav** [comment]
I've made a significant discovery wrt to my `mod_proxy_fcgid`. There's not a particularly obvious comment-like note at https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html

`# UDS does not currently support connection reuse`

In my case, I had configured exactly UDS-only + `<Proxy fcgi://www/ enablereuse=on></Proxy>`

This caused `php-fpm` processes to pile up in stuck `Finishing` state. I learned about the `pm.status_path` live status screen setting today which helped a ton with figuring things out.

Tomorrow, a new `mod_h2` testing period definitely begins, because I cannot be sure if previously I wasn't simply exhausting either Apache or PHP-FPM resources with the above misconfiguration. It's unfortunate Apache had no warning to stop me from executing it.

**Comment by icing** [comment]
1.0.13 should be worth a try for this.

**Comment by marcusds** [comment]
I have had a similar issue with the version included in 2.4.18.
Randomly connections lock up and httpd needs to be restarted to fix it.
We have had to resort to disabling http2 for now.

**Comment by icing** [comment]
According to people testing, this should be resolved in v1.1.0. If you like, you're more than welcome to give this a try.

**Comment by Zwilla** [comment]
Great Work Guys!!!

Now it works, without any issues on timeout!
Before: 2, 3,5 seven klicks within seconds on links you get an time out
Now: clicking like a crazy horse - and all works fine (here!)

on this site you can see it live: 
https://www.zwilla.de/loesungen/apache/mod_h2-compilen-http2

included an guide for compiling with nghttp2

thx!!!!

**Comment by icing** [comment]
Thanks for testing and reporting back!
