### ISSUE TITLE
256 cipher for http2 ?

### ISSUE THREAD

**Issue by JBlond** [icing/mod_h2#63]
is there any chance to have a 256 cipher instead of ECDHE-RSA-AES128-GCM-SHA256 ?

I know it is from https://http2.github.io/http2-spec/#rfc.section.9.2.2 but still not satisfying.

**Comment by icing** [comment]
Not sure why you post this here? mod_http2 will use any cipher that you configure via mod_ssl and that your ssl library supports.

**Comment by v998** [comment]
Actually...
not having ECDHE-RSA-AES128-GCM-SHA256 is a current limitation in the Mozilla NSS...

**Comment by JBlond** [comment]
I thought it as a limitation if the module. Since it isn't I close this.
