### ISSUE TITLE
Errors showing when compiling for OpenSuSE

### ISSUE THREAD

**Issue by jfha73** [icing/mod_h2#66]
Hey guys,

I'm trying to get mod_h2 to compile for OpenSuSE (13.2 & Tumbleweed) and all I'm getting are these errors when I run make:

h2_h2.c:152:20: error: ‘AP_PROTOCOL_HTTP1’ undeclared (first use in this function)
         && !strcmp(AP_PROTOCOL_HTTP1, ap_get_protocol(c))) {
                    ^
h2_h2.c:152:20: note: each undeclared identifier is reported only once for each function it appears in
h2_h2.c:152:39: error: implicit declaration of function ‘ap_get_protocol’ [-Werror=implicit-function-declaration]
         && !strcmp(AP_PROTOCOL_HTTP1, ap_get_protocol(c))) {
                                       ^
h2_h2.c:152:39: error: passing argument 1 of ‘strlen’ makes pointer from integer without a cast [-Werror=int-conversion]
         && !strcmp(AP_PROTOCOL_HTTP1, ap_get_protocol(c))) {
                                       ^
In file included from /usr/include/apr-1/apr_want.h:63:0,
                 from /usr/include/apr-1/apr_pools.h:47,
                 from /usr/include/apr-1/apr_strings.h:50,
                 from h2_h2.c:18:
/usr/include/string.h:394:15: note: expected ‘const char *’ but argument is of type ‘int’
 extern size_t strlen (const char *__s)
               ^
In file included from /usr/include/string.h:630:0,
                 from /usr/include/apr-1/apr_want.h:63,
                 from /usr/include/apr-1/apr_pools.h:47,
                 from /usr/include/apr-1/apr_strings.h:50,
                 from h2_h2.c:18:
h2_h2.c:152:39: error: passing argument 2 of ‘__builtin_strcmp’ makes pointer from integer without a cast [-Werror=int-conversion]
         && !strcmp(AP_PROTOCOL_HTTP1, ap_get_protocol(c))) {
                                       ^
h2_h2.c:152:39: note: expected ‘const char *’ but argument is of type ‘int’
h2_h2.c:152:39: error: passing argument 2 of ‘__builtin_strcmp’ makes pointer from integer without a cast [-Werror=int-conversion]
         && !strcmp(AP_PROTOCOL_HTTP1, ap_get_protocol(c))) {
                                       ^
h2_h2.c:152:39: note: expected ‘const char *’ but argument is of type ‘int’
h2_h2.c:152:39: error: passing argument 1 of ‘strlen’ makes pointer from integer without a cast [-Werror=int-conversion]
         && !strcmp(AP_PROTOCOL_HTTP1, ap_get_protocol(c))) {
                                       ^
In file included from /usr/include/apr-1/apr_want.h:63:0,
                 from /usr/include/apr-1/apr_pools.h:47,
                 from /usr/include/apr-1/apr_strings.h:50,
                 from h2_h2.c:18:
/usr/include/string.h:394:15: note: expected ‘const char *’ but argument is of type ‘int’
 extern size_t strlen (const char *__s)
               ^
In file included from /usr/include/string.h:630:0,
                 from /usr/include/apr-1/apr_want.h:63,
                 from /usr/include/apr-1/apr_pools.h:47,
                 from /usr/include/apr-1/apr_strings.h:50,
                 from h2_h2.c:18:
h2_h2.c:152:39: error: passing argument 2 of ‘__builtin_strcmp’ makes pointer from integer without a cast [-Werror=int-conversion]
         && !strcmp(AP_PROTOCOL_HTTP1, ap_get_protocol(c))) {
                                       ^
h2_h2.c:152:39: note: expected ‘const char *’ but argument is of type ‘int’
h2_h2.c:152:39: error: passing argument 2 of ‘__builtin_strcmp’ makes pointer from integer without a cast [-Werror=int-conversion]
         && !strcmp(AP_PROTOCOL_HTTP1, ap_get_protocol(c))) {
                                       ^
h2_h2.c:152:39: note: expected ‘const char *’ but argument is of type ‘int’
h2_h2.c:161:46: error: passing argument 1 of ‘strlen’ makes pointer from integer without a cast [-Werror=int-conversion]
                 || strcmp(AP_PROTOCOL_HTTP1, ap_get_protocol(c))) {
                                              ^
In file included from /usr/include/apr-1/apr_want.h:63:0,
                 from /usr/include/apr-1/apr_pools.h:47,
                 from /usr/include/apr-1/apr_strings.h:50,
                 from h2_h2.c:18:
/usr/include/string.h:394:15: note: expected ‘const char *’ but argument is of type ‘int’
 extern size_t strlen (const char *__s)
               ^
In file included from /usr/include/string.h:630:0,
                 from /usr/include/apr-1/apr_want.h:63,
                 from /usr/include/apr-1/apr_pools.h:47,
                 from /usr/include/apr-1/apr_strings.h:50,
                 from h2_h2.c:18:
h2_h2.c:161:46: error: passing argument 2 of ‘__builtin_strcmp’ makes pointer from integer without a cast [-Werror=int-conversion]
                 || strcmp(AP_PROTOCOL_HTTP1, ap_get_protocol(c))) {
                                              ^
h2_h2.c:161:46: note: expected ‘const char *’ but argument is of type ‘int’
h2_h2.c:161:46: error: passing argument 2 of ‘__builtin_strcmp’ makes pointer from integer without a cast [-Werror=int-conversion]
                 || strcmp(AP_PROTOCOL_HTTP1, ap_get_protocol(c))) {
                                              ^
h2_h2.c:161:46: note: expected ‘const char *’ but argument is of type ‘int’
h2_h2.c:161:46: error: passing argument 1 of ‘strlen’ makes pointer from integer without a cast [-Werror=int-conversion]
                 || strcmp(AP_PROTOCOL_HTTP1, ap_get_protocol(c))) {
                                              ^
In file included from /usr/include/apr-1/apr_want.h:63:0,
                 from /usr/include/apr-1/apr_pools.h:47,
                 from /usr/include/apr-1/apr_strings.h:50,
                 from h2_h2.c:18:
/usr/include/string.h:394:15: note: expected ‘const char *’ but argument is of type ‘int’
 extern size_t strlen (const char *__s)
               ^
In file included from /usr/include/string.h:630:0,
                 from /usr/include/apr-1/apr_want.h:63,
                 from /usr/include/apr-1/apr_pools.h:47,
                 from /usr/include/apr-1/apr_strings.h:50,
                 from h2_h2.c:18:
h2_h2.c:161:46: error: passing argument 2 of ‘__builtin_strcmp’ makes pointer from integer without a cast [-Werror=int-conversion]
                 || strcmp(AP_PROTOCOL_HTTP1, ap_get_protocol(c))) {
                                              ^
h2_h2.c:161:46: note: expected ‘const char *’ but argument is of type ‘int’
h2_h2.c:161:46: error: passing argument 2 of ‘__builtin_strcmp’ makes pointer from integer without a cast [-Werror=int-conversion]
                 || strcmp(AP_PROTOCOL_HTTP1, ap_get_protocol(c))) {
                                              ^
h2_h2.c:161:46: note: expected ‘const char *’ but argument is of type ‘int’
cc1: all warnings being treated as errors
Makefile:641: recipe for target 'mod_h2_la-h2_h2.lo' failed
make[1]: *** [mod_h2_la-h2_h2.lo] Error 1
make[1]: Leaving directory '/home/user/Downloads/mod_h2-0.9.8/mod_h2'
Makefile:457: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

What can I do so it can be compiled?

Thanks.

**Comment by icing** [comment]
Hi,

mod_h2 needs a patched Apache httpd. As you experienced, without patches important changes re not there. That's the reason this project compiled its own server in ```sandbox``` configuration mode. 

For testing, it is probably best to grab Apache 2.4.17 directly from httpd.apache.org and start from there.
