### ISSUE TITLE
upgrade on requests with body

### ISSUE THREAD

**Issue by icing** [icing/mod_h2#68]
## Status Quo

mod_h[ttp]2 supports HTTP/1 protocol upgrades by default auf h2c, if configured, also for h2 upgrades.

One severe restriction to the upgrade is that the request triggering the Upgrade does not have a body, not even a small one. This forces clients to either continue using HTTP/1 (`curl`for example) or having to prepend an `OPTIONS *` request as first on a new connection. This enforces an additional roundtrip to the server, even though the client may have a good idea that HTTP/2 is supported.

The only alternative at the moment is for the client to use `h2c direct` mode. However, unless support for that is really certain, it lacks a graceful degradation/fallback and will lead to failures and re-attempts.

Additionally, the Apache Serf client, used for Subversion, already sends an OPTIONS request on a new connection. However the subversion protocol requires that request to have a body, forcing it to stay on HTTP/1.1 with the current mod_http2.
## Proposal

Implement support for Upgrades with a request body, ideally for bodies of arbitrary length. This would allow clients to Upgrade with certainty on any HTTP/1.1 request, if the servers configuration supports HTTP/2.

If the implementation of arbitrary length Upgrades hits road blocks, such as limitations of existing `nghttp2` implementation (unlikely) or exposes the server to unacceptable DOS threats, provide a configurable maximum length setting, up to which upgrade request bodies are accepted.

**Comment by tatsuhiro-t** [comment]
libnghttp2 does not have any limitation to support HTTP upgrade with POST.
Actually, nghttpx already supports HTTP Upgrade to h2 with POST in any size of body (with some minor limitation, but this is a limitation of nghttpx and not libnghttp2).

**Comment by icing** [comment]
Good to know! With limitations I was more concerned about some internal timeouts that maybe would bite me. But am looking forward to implement this...

**Comment by icing** [comment]
Abandoned. There is really no one using `h2c`.
