### ISSUE TITLE
add 2 timeout configs to mod_http2

### ISSUE THREAD

**Issue by icing** [icing/mod_h2#69]
The timeout configuration of ```mod_reqtimeout```, with its separate configurations of request line, header and body reads, does not really fit to the HTTP/2 processing model with multiple ongoing requests per connection.

Add two configuration parameter to mod_http2 that control socket timeout. One for a busy connection with ongoing streams and one for an idle connection that waits on the next stream to arrive.

**Comment by icing** [comment]
Implemented first in 1.0.12, improved and corrected keepalive handling in 1.0.13.

**Comment by icing** [comment]
Now working satisfactory (for me, I hope for others too) in v1.1.0

**Comment by arminabf** [comment]
Can you give some details how you solved that?

**Comment by icing** [comment]
@arminabf mod_http2 now uses the values from the `Timeout` and `KeepAliveTimeout` directives that also apply to HTTP/1.1 connections.

**Comment by arminabf** [comment]
Sorry for the questions, but it the timeout handling is not really obvious and I can't find some documentation about that topic.

So I use v1.8.3, and (as far as I understand) the TimeOut setting controls the timeout on idle sessions without any ongoing streams whereas KeepAliveTimeout is used for idle sessions where already streams have been sent... is this correct?

If so, is there a possibility to protect against delayed data during ongoing streams, e.g. delayed body data? Analogously as mod_reqtimeout provides for h1?

**Comment by icing** [comment]
`Timeout` applies when requests are ongoing. So if you want requests to fail due to the client not sending, this is it.
`KeepAliveTimeout` applies when no streams are ongoing and the server listens for new requests on the connection. So, this is basically how long the server should keep a connection open on which nothing is happening.

**Comment by arminabf** [comment]
thanks, I've tested following use cases:

- open session, do not send request -> TimeOut (shouldn't it be KeepAliveTimeout?)
- open session, delay data of first request -> TimeOut (ok!)
- open session, send first request, delay second request -> TimeOut (ok!)
- open session, send first request, idle connection -> KeepAliveTimeout (ok!)

however, very interesting is following
- open session, send request with all data but do not send NGHTTP2_DATA_FLAG_EOF on last data frame -> no timeout at all

btw I've tested with latest version v1.8.9 (and nghttp2 version 1.18.1)

**Comment by icing** [comment]
The first request is handled special on purpose here, but it can be argued that the keepalive should apply.

No timeout on the missing EOF flag is interesting. Do you get a response for that request?

**Comment by arminabf** [comment]
> No timeout on the missing EOF flag is interesting. Do you get a response for that request?

yes
