### ISSUE TITLE
Environment Variable

### ISSUE THREAD

**Issue by jeffkaufman** [icing/mod_h2#70]
It would be great if mod_h2 could define an environment variable so people could write configuration that's specific to http2 connections.

(I work on mod_pagespeed, we'd like to let people use different configuration for http2 connections, and environment variables would be a nice way to communicate this.)

**Comment by icing** [comment]
Good idea. Anything particular besides "on" you would be interested in?

**Comment by igrigorik** [comment]
Would it make sense to export negotiated session settings?

**Comment by jeffkaufman** [comment]
Great!

It would be nice to have a way to tell programmatically whether mod_h2 supports server push.

But on/off is the main part of the integration we've been missing out on currently.

**Comment by icing** [comment]
Ok, will start working on it. Current idea is to add

HTTP2=on|off
H2_PUSH=on|off

to the request environment. H2_PUSH would only be "on", if the client supports it and it is not disabled by the module config. 

If you want anything else, window sizes, max streams, priority, raise your voice. ;-)

**Comment by icing** [comment]
If you'd like, give 1.0.13 a try. It defines HTTP2 and H2Push in the environment. Both with "on" as value if the connection uses HTTP/2 and if both server and client support Server Pushes.

**Comment by covener** [comment]
I think e.g. H2_PUSHED (not in love with name) to differentiate pushed resources from naturally requested ones in logs (or who knows what else) would be a handy addition.

**Comment by icing** [comment]
```H2_PUSHED``` and several others implemented in Apache trunk. Will apear here after next 2.4.x release.

**Comment by icing** [comment]
Implemented in 1.4.7.
