### ISSUE TITLE
Connections did not always close.  

### ISSUE THREAD

**Issue by BenediktS** [icing/mod_h2#72]
Hello, 

i think there is something wrong  with closing the connections.
After 3 days  all my connections are in the write state.
  
All connections say the last request was between 30094 and  272327 seconds ago. 
And they say the request only needed between 200 and 900ms.
So i think they should be closed a long time ago. .... i mean there are request that are still open since i startet the server 3 days ago. 

I recompiled the apache server with the worker mpm.  
After 20 Minutes there is already a connection saying that it is open since 1127 seconds.
So i think it hase nothing to do with the event mpm. 

Do i miss something? something like a ConnectionTimeout that i forgot to set? 

best regards
Benedikt 

---------

Server Version: Apache/2.4.18 (Unix) OpenSSL/1.0.2d-fips
Server MPM: event
Server Built: Dec 13 2015 06:43:13

Current Time: Wednesday, 16-Dec-2015 12:41:58 EST
Restart Time: Sunday, 13-Dec-2015 06:47:33 EST
Parent Server Config. Generation: 1
Parent Server MPM Generation: 0
Server uptime: 3 days 5 hours 54 minutes 25 seconds
Server load: 0.00 0.01 0.05
Total accesses: 221079 - Total Traffic: 9.8 GB
CPU Usage: u2281.22 s555.97 cu0 cs0 - 1.01% CPU load
.788 requests/sec - 36.6 kB/second - 46.4 kB/request
250 requests currently being processed, 0 idle workers

PID	Connections 	Threads	Async connections
total	accepting	busy	idle	writing	keep-alive	closing
28534	25	yes	25	0	0	0	0
28535	25	yes	25	0	0	0	0
28536	26	yes	25	0	0	0	1
28549	25	yes	25	0	0	0	0
28568	25	yes	25	0	0	0	0
13798	24	yes	25	0	0	0	0
15245	25	yes	25	0	0	0	0
16925	25	yes	25	0	0	0	0
18395	25	yes	25	0	0	0	0
19610	25	yes	25	0	0	0	0
Sum	250	 	250	0	0	0	1

WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWCWWWWWWWWWWWWWWWW
WWWWWWCWWCWWWWWWWWWWWWWWWWCWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKWWW
WWCKWWWWWWWWWWWWWWWWWWWWRWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW

**Comment by icing** [comment]
If you like, you can try release 1.0.12 from github, which includes extra new goodness for connection timeouts and cleanups. If you have a compiled 2.4.18 Apache, you can just build it from here and drop it into your server.

**Comment by BenediktS** [comment]
It looks like the mpm:worker is ok now. 
But the mpm:event is still not closing all connections.

**Comment by BenediktS** [comment]
I was wrong. .... the connections did close with mpm:worker. But now there are many log entries like:

[http2:info] [pid 8285:tid 140514082912000] (70007)The timeout specified has expired: [client 182.73.140.109:52619] AH02950: h2_session(266): error reading, terminating

These entries didn't show up with  httpd 2.4.17 .  And i have reports that the connection to our server shows errors if we load many files. i deactivated mod_h2 for now.   Also the message is not clear about which timeout was reached.

**Comment by mnot** [comment]
Seeing the same.

**Comment by icing** [comment]
The info logging: sorry about that. Should have been a lower level. It shows normal timeouts while reading on idle connections, which will cause the close.
```
And i have reports that the connection to our server shows errors if we load many files.
```
This is something else entirely, it seems. And I have no other report on that. Do you have more data of what went wrong?

I hope to release a version here that improves management of keepalive connections significantly and also shows better on the scoreboard/server-status what state the http2 connections are in.

Thanks for testing.

**Comment by icing** [comment]
Please give 1.0.13 a try, if you find the time. Connection keep-alive handling is 5 seconds by default now. Async MPMs, such as event, now allow longer times without blocking threads.

**Comment by icing** [comment]
People report back that v1.1.0 fixes this problem for them. Can you verify?

**Comment by BenediktS** [comment]
I will trie it later this week. .
One of my servers crashed, but i hope i could go back to testing on thursday.

**Comment by mnot** [comment]
So far, so good with 1.1.0...

**Comment by icing** [comment]
Good to hear. State machines ftw!

**Comment by mnot** [comment]
Been up for two days with no hint of the previous behaviour; think it's fixed. Thanks!

**Comment by icing** [comment]
Thanks for testing and reporting.
