### ISSUE TITLE
undefined symbol: nghttp2_session_change_stream_priority

### ISSUE THREAD

**Issue by tylercb** [icing/mod_h2#74]
Any ideas to fix this? Just upgraded to Apache 2.4.18 from 2.4.17 using ppa:ondrej/apache2.

apache2: Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/http2.load: Cannot load /usr/lib/apache2/modules/mod_http2.so into server: /usr/lib/apache2/modules/mod_http2.so: undefined symbol: nghttp2_session_change_stream_priority

Server version: Apache/2.4.18 (Ubuntu)
Server built:   2015-12-16T00:00:00

/etc/apache2/mods-enabled/http2.load
LoadModule http2_module /usr/lib/apache2/modules/mod_http2.so

**Comment by lkraav** [comment]
What version is your nghttp2 library?

**Comment by tylercb** [comment]
I have nghttp2-1.4.0. Just noticed "mod_http2: required minimum version of libnghttp2 is 1.2.1" in Changes...

$ locate libnghttp2
/usr/lib/x86_64-linux-gnu/libnghttp2.so.14
/usr/lib/x86_64-linux-gnu/libnghttp2.so.14.3.0
/usr/local/lib/libnghttp2.a
/usr/local/lib/libnghttp2.la
/usr/local/lib/libnghttp2.so
/usr/local/lib/libnghttp2.so.14
/usr/local/lib/libnghttp2.so.14.2.0

**Comment by lkraav** [comment]
Hmmkay. I am running successfully with 1.3.1. Perhaps your version is... too new?

**Comment by tylercb** [comment]
Are you explicitly loading the libnghttp2 module in your http2.load?

**Comment by icing** [comment]
Don't know how you compiled it, but the moduke you have seems to require nghttp2 1.5.0.

**Comment by tylercb** [comment]
Thank you @icing, upgrading to 1.5.0 fixed it.

**Comment by Dome-Net** [comment]
I'm having the very same problem, except that my nghttp version is: nghttp2/1.5.0

Could you please help me?

**Comment by icing** [comment]
Then your Apache process, that loads the module, is using another nghttp2 version. It's using shared libraries, so compiling the module against a local nghttp2 does not help when loading it into the server-

**Comment by Dome-Net** [comment]
Rebuilding the module from GIT would help?
I'm actually using the default apache2 module.

**Comment by icing** [comment]
Please talk to the people who built your 2.4.18 httpd + mod_http2. Something is mixed up there.

If you built it yourself, describe how you configured it, please.

**Comment by Dome-Net** [comment]
I used this ppa: Ubuntu: ppa by ondrej for Ubuntu 14.04 and others (from the Readme)

**Comment by icing** [comment]
Then you should check with him how about this. It seems you have an older nghttp2 installed from somewhere else which is not updated/overwritten by his ppa.

**Comment by Dome-Net** [comment]
Yes you must be right, I just made a fresh install from that ppa, and it works perfectly. Sorry about that, it is actually my fault...
I'll try to clean the packages, and reinstall it again.
Do you still think I should report it to the PPA manager?

**Comment by icing** [comment]
No, if it works after you cleaned up your install. All is well.

**Comment by dsjgeek** [comment]
hi@icing, my version is httpd-2.4.18 and openssl-1.0.2.e and nghttp2-1.5.0 ,I config them but when i restart httpd :httpd:Syntax error on line 105 of /usr/local/apache2/conf/httd.conf:cannot load modules/mod_http2.so into server :libnghttp2.so.14:cannot open sahred object file:No such file or directory.iconfig

**Comment by dsjgeek** [comment]
i config it with the website https://www.tunetheweb.com/performance/http2/,thank you!

**Comment by icing** [comment]
The question is where the libnghttp2.so landed in your system and if it can be found in LD_LIBRARY_PATH, I assume. The library could be found during build time, but not when you now start the server.

**Comment by bazzadp** [comment]
Are you starting apache using the apachectl command rather than httpd? This is necessary to pick up the LD_LIBRARY_PATH changes you set in the envvars script, which is necessary to pick up the libnghttp2.so library you built earlier.
