### ISSUE TITLE
Compilation errors on CentOS 6.7 x64

### ISSUE THREAD

**Issue by rpharrison** [icing/mod_h2#77]
I am currently using the previous release, when I try to compile this one I get the following output:

root@madrd [~/mod_http2-1.2.0]# make
Making all in mod_http2
make[1]: Entering directory `/root/mod_http2-1.2.0/mod_http2'
  CC     mod_http2_la-h2_push.lo
cc1: warnings being treated as errors
h2_push.c:682: error: conflicting types for built-in function ‘log2’
make[1]: *** [mod_http2_la-h2_push.lo] Error 1
make[1]: Leaving directory `/root/mod_http2-1.2.0/mod_http2'
make: *** [all-recursive] Error 1

I managed to make it proceed further with CPPFLAGS:

root@madrd [~/mod_http2-1.2.0]# make CPPFLAGS=-fno-builtin-log
Making all in mod_http2
make[1]: Entering directory `/root/mod_http2-1.2.0/mod_http2'
  CC     mod_http2_la-h2_push.lo
h2_push.c:19:21: error: apr_lib.h: No such file or directory
h2_push.c:20:25: error: apr_strings.h: No such file or directory
h2_push.c:21:22: error: apr_hash.h: No such file or directory
h2_push.c:22:22: error: apr_time.h: No such file or directory
h2_push.c:28:19: error: httpd.h: No such file or directory
h2_push.c:29:23: error: http_core.h: No such file or directory
h2_push.c:30:22: error: http_log.h: No such file or directory
In file included from h2_push.c:32:
h2_private.h:21: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘AP_MODULE_DECLARE_DATA’
cc1: warnings being treated as errors
h2_private.h:23: error: data definition has no type or storage class
h2_private.h:23: error: type defaults to ‘int’ in declaration of ‘APLOG_USE_MODULE’
h2_private.h:23: error: parameter names (without types) in function declaration
In file included from h2_push.c:33:
h2_h2.h:82: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_h2_init’
h2_h2.h:86: error: expected ‘)’ before ‘*’ token
h2_h2.h:100: error: expected ‘)’ before ‘*’ token
h2_h2.h:108: error: expected ‘)’ before ‘*’ token
h2_h2.h:116: error: expected ‘)’ before ‘*’ token
In file included from h2_push.c:34:
h2_util.h:33: error: expected ‘)’ before ‘*’ token
h2_util.h:40: error: expected ‘)’ before ‘*’ token
h2_util.h:42: error: expected ‘)’ before ‘*’ token
h2_util.h:49: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_util_base64url_decode’
h2_util.h:53: error: expected declaration specifiers or ‘...’ before ‘apr_size_t’
h2_util.h:53: error: expected declaration specifiers or ‘...’ before ‘apr_pool_t’
h2_util.h:80: error: expected specifier-qualifier-list before ‘apr_size_t’
h2_util.h:83: error: expected ‘)’ before ‘*’ token
h2_util.h:84: error: expected ‘)’ before ‘*’ token
h2_util.h:87: error: expected ‘)’ before ‘*’ token
h2_util.h:101: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_util_move’
h2_util.h:114: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_util_copy’
h2_util.h:122: error: expected ‘)’ before ‘*’ token
h2_util.h:123: error: expected ‘)’ before ‘*’ token
h2_util.h:124: error: expected ‘)’ before ‘*’ token
h2_util.h:125: error: expected ‘)’ before ‘*’ token
h2_util.h:134: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_util_bb_avail’
h2_util.h:137: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_util_pass_cb’
h2_util.h:152: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_util_bb_readx’
h2_util.h:165: error: expected ‘)’ before ‘*’ token
h2_util.h:177: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_transfer_brigade’
In file included from h2_push.c:35:
h2_push.h:42: error: expected declaration specifiers or ‘...’ before ‘apr_uint64_t’
h2_push.h:45: error: expected specifier-qualifier-list before ‘apr_array_header_t’
h2_push.h:62: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
h2_push.h:75: error: expected declaration specifiers or ‘...’ before ‘apr_pool_t’
h2_push.h:84: error: expected ‘)’ before ‘*’ token
h2_push.h:90: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
h2_push.h:96: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
h2_push.h:109: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_push_diary_digest_get’
h2_push.h:122: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_push_diary_digest_set’
h2_push.h:125: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_push_diary_digest64_set’
In file included from h2_push.c:36:
h2_request.h:38: error: expected specifier-qualifier-list before ‘apr_table_t’
h2_request.h:51: error: expected declaration specifiers or ‘...’ before ‘apr_pool_t’
h2_request.h:54: error: expected declaration specifiers or ‘...’ before ‘apr_pool_t’
h2_request.h:58: error: expected declaration specifiers or ‘...’ before ‘apr_table_t’
h2_request.h:62: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_request_rwrite’
h2_request.h:64: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_request_add_header’
h2_request.h:68: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_request_add_trailer’
h2_request.h:72: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_request_end_headers’
h2_request.h:75: error: expected ‘)’ before ‘*’ token
h2_request.h:85: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
In file included from h2_push.c:37:
h2_response.h:26: error: expected specifier-qualifier-list before ‘apr_off_t’
h2_response.h:43: error: expected declaration specifiers or ‘...’ before ‘apr_array_header_t’
h2_response.h:44: error: expected declaration specifiers or ‘...’ before ‘apr_table_t’
h2_response.h:45: error: expected declaration specifiers or ‘...’ before ‘apr_pool_t’
h2_response.h:54: error: expected declaration specifiers or ‘...’ before ‘request_rec’
h2_response.h:55: error: expected declaration specifiers or ‘...’ before ‘apr_table_t’
h2_response.h:55: error: expected declaration specifiers or ‘...’ before ‘apr_pool_t’
h2_response.h:64: error: expected declaration specifiers or ‘...’ before ‘apr_status_t’
h2_response.h:65: error: expected declaration specifiers or ‘...’ before ‘apr_pool_t’
h2_response.h:73: error: expected ‘)’ before ‘*’ token
h2_response.h:82: error: expected declaration specifiers or ‘...’ before ‘apr_table_t’
In file included from h2_session.h:19,
                 from h2_push.c:38:
h2_conn_io.h:29: error: expected specifier-qualifier-list before ‘conn_rec’
h2_conn_io.h:48: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_conn_io_init’
h2_conn_io.h:54: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_conn_io_write’
h2_conn_io.h:58: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_conn_io_writeb’
h2_conn_io.h:60: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_conn_io_consider_flush’
h2_conn_io.h:62: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_conn_io_pass’
h2_conn_io.h:63: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_conn_io_flush’
h2_conn_io.h:64: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_conn_io_write_eoc’
In file included from h2_push.c:38:
h2_session.h:84: error: expected specifier-qualifier-list before ‘conn_rec’
h2_session.h:146: error: expected ‘)’ before ‘*’ token
h2_session.h:157: error: expected ‘)’ before ‘*’ token
h2_session.h:166: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_session_process’
h2_session.h:181: error: expected declaration specifiers or ‘...’ before ‘apr_status_t’
h2_session.h:190: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_session_handle_response’
h2_session.h:216: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_session_stream_destroy’
h2_session.h:231: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_session_set_prio’
In file included from h2_stream.h:31,
                 from h2_push.c:39:
h2_io.h:25: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_io_data_cb’
h2_io.h:40: error: expected specifier-qualifier-list before ‘apr_pool_t’
h2_io.h:75: error: expected declaration specifiers or ‘...’ before ‘apr_pool_t’
h2_io.h:106: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_io_signal_wait’
h2_io.h:117: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_io_in_read’
h2_io.h:123: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_io_in_write’
h2_io.h:129: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_io_in_close’
h2_io.h:135: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_io_in_shutdown’
h2_io.h:151: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_io_out_readx’
h2_io.h:155: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_io_out_read_to’
h2_io.h:159: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_io_out_write’
h2_io.h:167: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_io_out_close’
h2_io.h:173: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_io_out_length’
In file included from h2_push.c:39:
h2_stream.h:58: error: expected specifier-qualifier-list before ‘apr_pool_t’
h2_stream.h:84: error: expected declaration specifiers or ‘...’ before ‘apr_pool_t’
h2_stream.h:93: error: expected declaration specifiers or ‘...’ before ‘apr_pool_t’
h2_stream.h:101: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_stream_destroy’
h2_stream.h:117: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
h2_stream.h:126: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_stream_set_request’
h2_stream.h:147: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_stream_add_header’
h2_stream.h:156: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_stream_close_input’
h2_stream.h:165: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_stream_write_data’
h2_stream.h:186: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_stream_schedule’
h2_stream.h:207: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_stream_set_response’
h2_stream.h:224: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_stream_prep_read’
h2_stream.h:241: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_stream_readx’
h2_stream.h:256: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_stream_read_to’
h2_stream.h:267: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
h2_stream.h:303: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_stream_submit_pushes’
h2_push.c:61: error: expected specifier-qualifier-list before ‘apr_pool_t’
h2_push.c: In function ‘attr_char’:
h2_push.c:89: error: implicit declaration of function ‘apr_isalnum’
h2_push.c: In function ‘skip_ws’:
h2_push.c:132: error: ‘link_ctx’ has no member named ‘i’
h2_push.c:132: error: ‘link_ctx’ has no member named ‘slen’
h2_push.c:133: error: ‘link_ctx’ has no member named ‘s’
h2_push.c:133: error: ‘link_ctx’ has no member named ‘i’
h2_push.c:134: error: ‘link_ctx’ has no member named ‘i’
h2_push.c:136: error: ‘link_ctx’ has no member named ‘i’
h2_push.c:136: error: ‘link_ctx’ has no member named ‘slen’
h2_push.c: In function ‘find_chr’:
h2_push.c:142: error: ‘link_ctx’ has no member named ‘i’
h2_push.c:142: error: ‘link_ctx’ has no member named ‘slen’
h2_push.c:143: error: ‘link_ctx’ has no member named ‘s’
h2_push.c: In function ‘read_chr’:
h2_push.c:153: error: ‘link_ctx’ has no member named ‘i’
h2_push.c:153: error: ‘link_ctx’ has no member named ‘slen’
h2_push.c:153: error: ‘link_ctx’ has no member named ‘s’
h2_push.c:153: error: ‘link_ctx’ has no member named ‘i’
h2_push.c:154: error: ‘link_ctx’ has no member named ‘i’
h2_push.c: In function ‘mk_str’:
h2_push.c:162: error: ‘link_ctx’ has no member named ‘i’
h2_push.c:163: error: implicit declaration of function ‘apr_pstrndup’
h2_push.c:163: error: ‘link_ctx’ has no member named ‘pool’
h2_push.c:163: error: ‘link_ctx’ has no member named ‘s’
h2_push.c:163: error: ‘link_ctx’ has no member named ‘i’
h2_push.c:163: error: ‘link_ctx’ has no member named ‘i’
h2_push.c: In function ‘read_qstring’:
h2_push.c:174: error: ‘link_ctx’ has no member named ‘i’
h2_push.c: In function ‘read_ptoken’:
h2_push.c:185: error: ‘link_ctx’ has no member named ‘i’
h2_push.c:185: error: ‘link_ctx’ has no member named ‘slen’
h2_push.c:185: error: ‘link_ctx’ has no member named ‘s’
h2_push.c:188: error: ‘link_ctx’ has no member named ‘i’
h2_push.c:190: error: ‘link_ctx’ has no member named ‘i’
h2_push.c: In function ‘read_link’:
h2_push.c:203: error: ‘link_ctx’ has no member named ‘link’
h2_push.c:204: error: ‘link_ctx’ has no member named ‘i’
h2_push.c: In function ‘read_pname’:
h2_push.c:215: error: ‘link_ctx’ has no member named ‘i’
h2_push.c:215: error: ‘link_ctx’ has no member named ‘slen’
h2_push.c:215: error: ‘link_ctx’ has no member named ‘s’
h2_push.c:218: error: ‘link_ctx’ has no member named ‘i’
h2_push.c:220: error: ‘link_ctx’ has no member named ‘i’
h2_push.c: In function ‘read_param’:
h2_push.c:243: error: implicit declaration of function ‘apr_table_setn’
h2_push.c:243: error: ‘link_ctx’ has no member named ‘params’
h2_push.c: In function ‘init_params’:
h2_push.c:260: error: ‘link_ctx’ has no member named ‘params’
h2_push.c:261: error: ‘link_ctx’ has no member named ‘params’
h2_push.c:261: error: implicit declaration of function ‘apr_table_make’
h2_push.c:261: error: ‘link_ctx’ has no member named ‘pool’
h2_push.c:264: error: implicit declaration of function ‘apr_table_clear’
h2_push.c:264: error: ‘link_ctx’ has no member named ‘params’
h2_push.c: At top level:
h2_push.c:268: error: type defaults to ‘int’ in declaration of ‘apr_uri_t’
h2_push.c:268: error: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
h2_push.c: In function ‘add_push’:
h2_push.c:291: error: implicit declaration of function ‘apr_table_get’
h2_push.c:291: error: ‘link_ctx’ has no member named ‘params’
h2_push.c:292: error: implicit declaration of function ‘strcmp’
h2_push.c:293: error: ‘apr_uri_t’ undeclared (first use in this function)
h2_push.c:293: error: (Each undeclared identifier is reported only once
h2_push.c:293: error: for each function it appears in.)
h2_push.c:293: error: expected ‘;’ before ‘uri’
h2_push.c:294: error: implicit declaration of function ‘apr_uri_parse’
h2_push.c:294: error: ‘link_ctx’ has no member named ‘pool’
h2_push.c:294: error: ‘link_ctx’ has no member named ‘link’
h2_push.c:294: error: ‘uri’ undeclared (first use in this function)
h2_push.c:294: error: ‘APR_SUCCESS’ undeclared (first use in this function)
h2_push.c:295: error: implicit declaration of function ‘same_authority’
h2_push.c:298: error: ‘apr_table_t’ undeclared (first use in this function)
h2_push.c:298: error: ‘headers’ undeclared (first use in this function)
h2_push.c:308: error: implicit declaration of function ‘apr_uri_unparse’
h2_push.c:308: error: ‘link_ctx’ has no member named ‘pool’
h2_push.c:308: error: ‘APR_URI_UNP_OMITSITEPART’ undeclared (first use in this function)
h2_push.c:310: error: implicit declaration of function ‘apr_pcalloc’
h2_push.c:310: error: ‘link_ctx’ has no member named ‘pool’
h2_push.c:312: error: ‘h2_request’ has no member named ‘push_policy’
h2_push.c:320: error: ‘link_ctx’ has no member named ‘pool’
h2_push.c:321: error: implicit declaration of function ‘apr_table_do’
h2_push.c:321: error: ‘h2_request’ has no member named ‘headers’
h2_push.c:326: error: ‘link_ctx’ has no member named ‘pool’
h2_push.c:326: error: ‘h2_request’ has no member named ‘config’
h2_push.c:329: error: too many arguments to function ‘h2_request_createn’
h2_push.c:331: error: implicit declaration of function ‘h2_request_end_headers’
h2_push.c:331: error: ‘link_ctx’ has no member named ‘pool’
h2_push.c:334: error: ‘link_ctx’ has no member named ‘pushes’
h2_push.c:335: error: ‘link_ctx’ has no member named ‘pushes’
h2_push.c:335: error: implicit declaration of function ‘apr_array_make’
h2_push.c:335: error: ‘link_ctx’ has no member named ‘pool’
h2_push.c:337: error: implicit declaration of function ‘APR_ARRAY_PUSH’
h2_push.c:337: error: ‘link_ctx’ has no member named ‘pushes’
h2_push.c:337: error: expected expression before ‘h2_push’
h2_push.c: In function ‘inspect_link’:
h2_push.c:384: error: ‘link_ctx’ has no member named ‘s’
h2_push.c:385: error: ‘link_ctx’ has no member named ‘slen’
h2_push.c:386: error: ‘link_ctx’ has no member named ‘i’
h2_push.c: In function ‘head_iter’:
h2_push.c:402: error: implicit declaration of function ‘apr_strnatcasecmp’
h2_push.c:403: error: implicit declaration of function ‘strlen’
h2_push.c:403: error: incompatible implicit declaration of built-in function ‘strlen’
h2_push.c: At top level:
h2_push.c:408: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
h2_push.c:437: error: expected declaration specifiers or ‘...’ before ‘apr_pool_t’
h2_push.c: In function ‘h2_push_policy_determine’:
h2_push.c:441: error: ‘struct h2_request’ has no member named ‘headers’
h2_push.c:443: error: implicit declaration of function ‘ap_find_token’
h2_push.c:443: error: ‘p’ undeclared (first use in this function)
h2_push.c:464: error: ‘struct h2_request’ has no member named ‘push_policy’
h2_push.c: At top level:
h2_push.c:472: error: expected specifier-qualifier-list before ‘apr_uint64_t’
h2_push.c: In function ‘val_apr_hash’:
h2_push.c:503: error: ‘apr_ssize_t’ undeclared (first use in this function)
h2_push.c:503: error: expected ‘;’ before ‘len’
h2_push.c:504: error: implicit declaration of function ‘apr_hashfunc_default’
h2_push.c:504: error: ‘len’ undeclared (first use in this function)
h2_push.c: At top level:
h2_push.c:507: error: expected declaration specifiers or ‘...’ before ‘apr_uint64_t’
h2_push.c: In function ‘calc_apr_hash’:
h2_push.c:509: error: ‘apr_uint64_t’ undeclared (first use in this function)
h2_push.c:509: error: expected ‘;’ before ‘val’
h2_push.c:515: error: ‘val’ undeclared (first use in this function)
h2_push.c:519: error: ‘phash’ undeclared (first use in this function)
h2_push.c: At top level:
h2_push.c:522: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘ceil_power_of_2’
h2_push.c:533: error: expected ‘)’ before ‘*’ token
h2_push.c:569: error: expected ‘)’ before ‘*’ token
h2_push.c:574: error: expected declaration specifiers or ‘...’ before ‘apr_uint64_t’
h2_push.c: In function ‘h2_push_diary_find’:
h2_push.c:581: error: ‘hash’ undeclared (first use in this function)
h2_push.c:581: error: ‘h2_push_diary’ has no member named ‘mask’
h2_push.c:582: error: ‘h2_push_diary’ has no member named ‘entries’
h2_push.c:583: error: implicit declaration of function ‘APR_ARRAY_IDX’
h2_push.c:583: error: ‘h2_push_diary’ has no member named ‘entries’
h2_push.c:583: error: expected expression before ‘h2_push_diary_entry’
h2_push.c:584: error: ‘h2_push_diary_entry’ has no member named ‘hash’
h2_push.c: At top level:
h2_push.c:592: error: expected declaration specifiers or ‘...’ before ‘apr_size_t’
h2_push.c: In function ‘move_to_last’:
h2_push.c:594: error: ‘h2_push_diary’ has no member named ‘entries’
h2_push.c:596: error: ‘apr_size_t’ undeclared (first use in this function)
h2_push.c:596: error: expected ‘;’ before ‘lastidx’
h2_push.c:599: error: ‘idx’ undeclared (first use in this function)
h2_push.c:599: error: ‘lastidx’ undeclared (first use in this function)
h2_push.c:601: error: implicit declaration of function ‘memmove’
h2_push.c:601: error: incompatible implicit declaration of built-in function ‘memmove’
h2_push.c: In function ‘h2_push_diary_append’:
h2_push.c:611: error: ‘h2_push_diary’ has no member named ‘entries’
h2_push.c:611: error: ‘h2_push_diary’ has no member named ‘N’
h2_push.c:613: error: ‘h2_push_diary’ has no member named ‘entries’
h2_push.c:613: error: expected expression before ‘h2_push_diary_entry’
h2_push.c:614: error: ‘h2_push_diary’ has no member named ‘entries’
h2_push.c:614: error: ‘h2_push_diary’ has no member named ‘entries’
h2_push.c:614: error: expected expression before ‘h2_push_diary_entry’
h2_push.c:618: error: too many arguments to function ‘move_to_last’
h2_push.c:621: error: implicit declaration of function ‘ap_log_perror’
h2_push.c:621: error: ‘APLOG_MARK’ undeclared (first use in this function)
h2_push.c:621: error: ‘APLOG_TRACE1’ undeclared (first use in this function)
h2_push.c:621: error: ‘h2_push_diary’ has no member named ‘entries’
h2_push.c:622: error: ‘h2_push_diary_entry’ has no member named ‘hash’
h2_push.c:623: error: ‘h2_push_diary_entry’ has no member named ‘hash’
h2_push.c:623: error: ‘h2_push_diary’ has no member named ‘mask’
h2_push.c: At top level:
h2_push.c:626: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
h2_push.c:660: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
h2_push.c:682: error: expected ‘)’ before ‘n’
h2_push.c:712: error: expected ‘)’ before ‘n’
h2_push.c:721: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘log2inv’
h2_push.c:730: error: expected specifier-qualifier-list before ‘apr_uint32_t’
h2_push.c: In function ‘cmp_puint64’:
h2_push.c:744: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
h2_push.c:744: error: ‘pu1’ undeclared (first use in this function)
h2_push.c:744: error: ‘pu2’ undeclared (first use in this function)
h2_push.c: At top level:
h2_push.c:763: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘gset_encode_bit’
h2_push.c:785: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘gset_encode_next’
h2_push.c:828: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_push_diary_digest_get’
h2_push.c:909: error: expected specifier-qualifier-list before ‘apr_pool_t’
h2_push.c: In function ‘gset_decode_next_bit’:
h2_push.c:920: error: ‘gset_decoder’ has no member named ‘bit’
h2_push.c:921: error: ‘gset_decoder’ has no member named ‘offset’
h2_push.c:921: error: ‘gset_decoder’ has no member named ‘datalen’
h2_push.c:924: error: ‘gset_decoder’ has no member named ‘bit’
h2_push.c:926: error: ‘gset_decoder’ has no member named ‘data’
h2_push.c:926: error: ‘gset_decoder’ has no member named ‘offset’
h2_push.c:926: error: ‘gset_decoder’ has no member named ‘bit’
h2_push.c: At top level:
h2_push.c:929: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘gset_decode_next’
h2_push.c:977: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_push_diary_digest_set’
h2_push.c:1059: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘h2_push_diary_digest64_set’
make[1]: *** [mod_http2_la-h2_push.lo] Error 1
make[1]: Leaving directory `/root/mod_http2-1.2.0/mod_http2'
make: *** [all-recursive] Error 1

Now I don't know how to proceed, especially with the missing files.

**Comment by rpharrison** [comment]
Working thanks to compile hints in issue #78

**Comment by icing** [comment]
Should be fixed in v1.2.2. Sorry for the confusion.

**Comment by rpharrison** [comment]
1.2.2 Compiles as normal without flags, seems to work fine.
