### ISSUE TITLE
Compilation error on gentoo, gcc 4.9.3: h2_push.c:682:22: error: conflicting types for built-in function ‘log2’ [-Werror]

### ISSUE THREAD

**Issue by d3xt3r01** [icing/mod_h2#78]
```
rm -f stamp-h1
touch config.h.in
cd .. && /bin/sh ./config.status mod_http2/config.h
config.status: creating mod_http2/config.h
config.status: mod_http2/config.h is unchanged
  CC       mod_http2_la-h2_alt_svc.lo
  CC       mod_http2_la-h2_bucket_eoc.lo
  CC       mod_http2_la-h2_bucket_eos.lo
  CC       mod_http2_la-h2_config.lo
  CC       mod_http2_la-h2_conn.lo
  CC       mod_http2_la-h2_conn_io.lo
  CC       mod_http2_la-h2_ctx.lo
  CC       mod_http2_la-h2_filter.lo
  CC       mod_http2_la-h2_from_h1.lo
  CC       mod_http2_la-h2_h2.lo
  CC       mod_http2_la-h2_io.lo
  CC       mod_http2_la-h2_io_set.lo
  CC       mod_http2_la-h2_mplx.lo
  CC       mod_http2_la-h2_push.lo
h2_push.c:682:22: error: conflicting types for built-in function ‘log2’ [-Werror]
 static unsigned char log2(apr_uint32_t n)
                      ^
cc1: all warnings being treated as errors
Makefile:703: recipe for target 'mod_http2_la-h2_push.lo' failed
make[1]: *** [mod_http2_la-h2_push.lo] Error 1
```

**Comment by lkraav** [comment]
@icing knows about this, I ran into the same thing and commented on the commit.

**Comment by d3xt3r01** [comment]
@lkraav thanks !

**Comment by rpharrison** [comment]
You can try: make CPPFLAGS=-fno-builtin-log

**Comment by d3xt3r01** [comment]
@rpharrison that would yell

```
h2_alt_svc.c:16:25: fatal error: apr_strings.h: No such file or directory
```

Tried to append to the CPPFLAGS=... got from configure. Same thing, no dice.

I think it was related to log2 because this made it work!

```
make  CPPFLAGS="-fno-builtin-log2 -I/usr/include/apache2 -I/usr/include/apr-1 -DH2_NG2_STREAM_API -DH2_NG2_CHANGE_PRIO -DH2_OPENSSL"
```

**Comment by d3xt3r01** [comment]
So .. this works ! As in, the upload doesn't fail anymore .. 
The thing is that I don't see a "progress bar" in chrome anymore ( I used to see "uploading X%" before without http2 ) ..

**Comment by rpharrison** [comment]
Thanks! Your make line was very helpful, I modified it for CentOS 6.7 x64, i.e.:

make  CPPFLAGS="-fno-builtin-log2 -I/usr/local/apache/include -I/usr/local/apache/include -DH2_NG2_STREAM_API -DH2_NG2_CHANGE_PRIO -DH2_OPENSSL"

The build passed, but when I tried to restart Apache gave:

Cannot load modules/mod_http2.so into server: /usr/local/apache/modules/mod_http2.so: undefined symbol: nghttp2_session_find_stream

Updating my libnghttp2 library to 1.6.0 and using make without flags, results in usable http2.

**Comment by icing** [comment]
Sorry about this. Did not test on my Linux image before release and clang is more forgiving here.

Please grab v1.2.2 which should work without tweaks and has also a fix for the new cache-digest calculation.

**Comment by d3xt3r01** [comment]
@icing no worries. All is good when it ends well !
Awesome work ! Thanks. 

Last version compiles just fine without any tricks !

Now the only thing that remains is the "Upload progress" bar in chrome ..

**Comment by rpharrison** [comment]
I can also confirm what @d3xt3r01 says, compiles & runs fine. 

@d3xt3r01 What do you mean regarding upload progess bar? Do you have a screenshot?

**Comment by d3xt3r01** [comment]
@rpharrison sorry for the late reply. Chrome shows a "progress status" bar in the bottom left corner when uploading a file. I don't mind missing it...
