### ISSUE TITLE
hanging processes

### ISSUE THREAD

**Issue by frankstolle** [icing/mod_h2#79]
I've got the problem that sometimes the connections "hang". Then I have to restart either the server or the browser to solve the problem. In status-site of the apache the connection is in WRITE mode for many seconds (> 1000). In the official apache release 2.4.17 this problem didn't occur.

**Comment by icing** [comment]
Which version do you see this in? The 2.4.18 release or a more current one from here?

**Comment by frankstolle** [comment]
I am using 2.4.18 with the current 1.2.2 from here.

**Comment by icing** [comment]
Could you share your configuration? os, mpm, timeouts, worker, maxconnections etc? Thanks.

**Comment by frankstolle** [comment]
Yes of course. 
os: linux debian 32bit
mpm: worker
apacheconfig:
```
Protocols h2 h2c http/1.1
H2Direct on

TimeOut 25
KeepAliveTimeout 25
ProxyTimeout 1800

ServerLimit 30
StartServers 2
MaxClients 1500
MinSpareThreads 50
MaxSpareThreads 150
ThreadsPerChild 50
MaxRequestsPerChild 0
```

**Comment by rpharrison** [comment]
Not seeing this issue personally. Is that your full apache configuration? What is your server spec? How much traffic is apache handling?

**Comment by frankstolle** [comment]
These are the additions to the default Apache-Config:
```
BufferedLogs on

Protocols h2 h2c http/1.1
H2Direct on

TimeOut 25
KeepAliveTimeout 25
ProxyTimeout 1800

ServerLimit 30
StartServers 2
MaxClients 1500
MinSpareThreads 50
MaxSpareThreads 150
ThreadsPerChild 50
MaxRequestsPerChild 0

TraceEnable off

AddHandler cgi-script .cgi .sh .pl .ry .rb .py

AddType text/html .shtml
AddHandler server-parsed .shtml

DirectoryIndex index.htm index.html index.php index.php3 index.shtml index.cgi default.htm default.html default.php

<Directory />
Order deny,allow
</Directory>

<Location /fcgiwrapperdir/>
ProxyPass fcgi://127.0.0.1:9000/ retry=0
fcgiphp on
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
</Location>

ExtendedStatus on

<VirtualHost *:80>
    ServerName default
    DocumentRoot /var/www/unknown
    Options -Indexes
</VirtualHost>

<VirtualHost *:80>
        ServerName status.xxxx
        DocumentRoot /var/www/status
        <Location />
               SetHandler server-status
        </Location>
</VirtualHost>

Action application/x-httpd-php56 /fcgiwrapperdir/php56
AddType application/x-httpd-php56 .php

SSLProtocol ALL -SSLv2 -SSLv3
SSLHonorCipherOrder on
SSLCompression off
SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128:AES256:AES:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK
```

I have PHP connected via mod_proxy_fcgi. The server is a Intel(R) Xeon(R) CPU E3-1271 v3 @ 3.60GHz with 32 GB memory. It serves around 200.000 requests / day. about 90 % is SSL-traffic.

**Comment by icing** [comment]
Hmm, seeing nothing unusual in the configuration. A connection hanging in ```W``` for much longer that Timeout/Keepalive and the browser not being able to make use of it, looks like a bug in flow control.

I will add timeout handling to this connection state and produce some INFO level logging should that trigger. Will make a release in the coming days here...

**Comment by frankstolle** [comment]
Thank you very much! Looking forward the release :)

**Comment by icing** [comment]
Please give 1.2.3 a try. With this one, connection may also time out when requests are not producing data.

**Comment by lkraav** [comment]
`1.2.x` series has been behaving very stable in production for me. I think I've heard a single complaint of a connecting hang without the ability to instantly reconnect - the 75 sec timeout probably restored connectivity there, I certainly never restarted the server.

**Comment by frankstolle** [comment]
Thank you for your release. Unfortunately I have still the same situation.

The following process is shown in Apache-status:
`0-0	8543	20/23/23	W	0.90	159	9	0.0	0.00	0.00	112.198.YYY.YYY	www.xxxx.xxx:443	GET /bestellen/resources/extern/slider/startpage//2_Product-Slid`

In the accesslog I have 20 successful requests from this ip including the last:
`112.198.YYY.YYY - "-" [28/Jan/2016:11:05:23 +0100] "GET /bestellen/resources/extern/slider/startpage//2_Product-Slider.jpg HTTP/2" 200 0 "https://www.xxxx.xxx/" "Mozilla/5.0 (Linux; Android 5.1.1; D5803 Build/23.4.A.1.264) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36" www.xxxx.xxx 0 8543
`

lsof shows the following state
`httpd     8543    www-data   73u  IPv4 194428524      0t0  TCP 178.63.YYY.YYY:443->112.198.YYY.YYY:41290 (CLOSE_WAIT)`

I hope this informations help you a bit. If you need more informations, feel free to ask for.

**Comment by rpharrison** [comment]
Have you checked the output of: cat /path/to/apache/logs/error_log |grep http2:info

**Comment by frankstolle** [comment]
I had LogLevel on warn, so I tested today again. After 10 Minutes I had again one slot, which is waiting and have Socket-State CLOSE_WAIT.

But, I have only one line from http2 in log:
`[Fri Jan 29 08:51:05.443225 2016] [http2:info] [pid 12974:tid 4142421760] mod_http2 (v1.2.3, nghttp2 1.6.0), initializing...
`

Do I need to switch to LogLevel debug?

**Comment by icing** [comment]
LogLevel debug would help, but will produce a lot of output and since it is not predictable when the bug will strike. If you do it, you can grep on "h2_session(<connection-id>)" to just see the traffic for the blocked one.

The thing I do not understand is why this keeps happening, since you have a timeout of 25 seconds, any hanging connection should close after that. Need to read my code again...

**Comment by icing** [comment]
Wait. Doesn't that mean
```
lsof shows the following state
httpd 8543 www-data 73u IPv4 194428524 0t0 TCP 178.63.YYY.YYY:443->112.198.YYY.YYY:41290 (CLOSE_WAIT)
```
that the server running on 178.63.xxx:443 has closed its side and the socket is waiting for the close on the client? I might be wrong...

Which browser are you running?

**Comment by frankstolle** [comment]
I think CLOSE_WAIT means the other side has sended FIN-Package, but the server did not closed the socket yet.
I use chrome and have the problem also sometimes. The example here is an other user. I will try it with debug logging on beginning next week.

**Comment by covener** [comment]
yes, it should mean the client closed, and httpd A) hasn't subsequently read and B) from mod_status is still occupying a thread.

**Comment by icing** [comment]
Thanks Frank & Eric! I keep on hunting here from my end...

**Comment by frankstolle** [comment]
So I have a debug-log. Because it is very long I've published it via pastebin.

http://pastebin.com/2y2u10Qv

**Comment by icing** [comment]
I only see ~50KB which look normal and show no lockup. Did I miss anything?

**Comment by frankstolle** [comment]
This is all I found about the connection which was again hanging in CLOSE_WAIT-state.

**Comment by icing** [comment]
Thanks for the clarification. Do you see any CPU usage in such a case? (busy loop?)

I see 6 open streams before logging stops. None of these are suspended due to lack of data. All have produced data, but not given EOF. The last log line is about passing out 130KB. Either this blocked indefinitely (should not, I think) or the session went into a busy loop without every achieving any progress (which I also do not see, but I am wrong somewhere...).

**Comment by frankstolle** [comment]
I don't see any high CPU usage, so I don't think there is an infinite loop. Can I do something more to find the reason?

**Comment by DavidBruchmann** [comment]
> CLOSE_WAIT means pretty much exactly what it says -- the kernel is waiting for the local process to close it's file descriptor before removing the entry. The TCP connection has been completely torn down and the far end may be under the impression that the connection is finito, but your end is holding onto things.
> 
> The only concern is that a lot of CLOSE_WAIT entries consumes kernel memory and file descriptor table entries, which can be a problem if there's great piles of them. If the entries you're looking at are transient, then it's probably just that you're cycling through a lot of TCP connections, and you're seeing a small fraction of them in the small amount of time between when the connection is closed and the process gets around to closing the file descriptor. On the other hand, if they're permanent (the ports and IP addresses don't change over time) then something is leaking descriptors and it needs to be fixed so that it always closes it's fds when it's finished with them.

http://serverfault.com/questions/65944/running-lsof-i-shows-a-lot-of-connections-in-close-wait-should-i-worry

**Comment by icing** [comment]
Frank, thanks for your patience. I have just released a 1.2.4 which enforces the timeouts of the selected virtual host and also adds a DEBUG logging for tracing down the hanging connections of yours. 

If you could let that run at debug level and catch another hanger that'd be awesome!

**Comment by frankstolle** [comment]
I have tested again and have two logs. Seem to be that the server want to write data, but the socket is closed by the client?

http://pastebin.com/np6efSdM
http://pastebin.com/FC1S7gYh

**Comment by icing** [comment]
Thanks, Frank. I see in both cases that the write does not return. Our SSL people are currently investigating a report of connections lock ups in 2.4.18, related to HTTP/1.1 requests, but that may be also visible here. Let's see what they come up with.

Would you be able to apply a patch to a 2.4.18 httpd and have that running for verification purposes - once a patch is available?

**Comment by frankstolle** [comment]
Thank you for your help. Yes, I can patch the httpd without any problems. It is currently also self compiled.

**Comment by icing** [comment]
Ah, great. Can you also ```gdb```and ```-g``` it to see what exactly the backtrace of the blocking connection is? That would be very helpful!

**Comment by frankstolle** [comment]
I can try it, but I didn't work with gdb yet. Do you have a quick tutorial / howto? What do I need to modify on the configure script and how to use gdb later to get the informations?

**Comment by icing** [comment]
If you configure apache with ``` --enable-debugger-mode``` you should get the debug symbols in and optimizations are switched off. If you see a hanging connection in ```server-status```you also see the process id it belongs to. You can then attach to the process with gdb and get a backtrace.

See here https://httpd.apache.org/dev/debugging.html#backtrace for instructions.

**Comment by frankstolle** [comment]
Thank you for your hints. Because of mod_worker is it not so easy to fetch the stacktrace of the relevant thread, but I think I have it.

I posted it again on pastebin, because the layout here is not so good. http://pastebin.com/bCAnD6UJ

**Comment by icing** [comment]
Thanks! That is indeed helpful. Working on a fix...

**Comment by icing** [comment]
Frank, can you check v1.2.5? I wrote that it fixes your issue, hope it was not premature...

**Comment by frankstolle** [comment]
It seems to solve the problem :) The server is running now for over 4 hours without any hanging slots. I will watch over weekend and give feedback on monday.

**Comment by icing** [comment]
Thanks! Keeping fingers crossed, of course...

**Comment by frankstolle** [comment]
After running the whole weekend without problems, I think the problem is solved. Thanks @icing  for your help!

**Comment by icing** [comment]
Glad to hear it! Thanks for the testing and the data!
