### ISSUE TITLE
Support Nghttp2 v0.6.4

### ISSUE THREAD

**Issue by devurandom** [icing/mod_h2#8]
Debian 8 "Jessie" currently ships Nghttp2 v0.6.4. Thus it would be great if you could support it.

Primary issues seems to be:
```
h2_session.c: In function 'h2_session_goaway':
h2_session.c:627:9: warning: implicit declaration of function 'nghttp2_submit_shutdown_notice' [-Wimplicit-function-declaration]
         rv = nghttp2_submit_shutdown_notice(session->ngh2);
         ^
h2_session.c:631:9: warning: implicit declaration of function 'nghttp2_session_get_last_proc_stream_id' [-Wimplicit-function-declaration]
         int last_id = nghttp2_session_get_last_proc_stream_id(session->ngh2);
         ^
```

It appears [these functions both arrived in v0.7.3](http://nghttp2.org/blog/2015/01/25/nghttp2-v0-7-3/).

**Comment by icing** [comment]
I started with v0.7.3. That would explain it. Unfortunately, I do not have the resources to support multiple nghttp2 versions. Pull requests are welcome, though... ;-)

**Comment by devurandom** [comment]
`nghttp2_submit_shutdown_notice` seems simple: Just do not submit such notice for older versions of nghttp2.

I will have a look at the other function, to see how it can be replaced.

**Comment by icing** [comment]
Closing this. I see no point in supporting old nghttp2 releases, until nghttp2 reaches v1.0.
