### ISSUE TITLE
Consecutive files take long time to load

### ISSUE THREAD

**Issue by milansimek** [icing/mod_h2#81]
Hi,

I'm experiencing the following error:

Whenever I enable mod_h2 for a virtual host, the initial page load seems fine but the consecutive asset files take over one minute to load.
- During loading the page stays completely blank. After one minute or so the page finally appears.
- The issue doesn't appear when opening a blank html document.
- The website is TLS encrypted

Please see the following screenshot for details:

![image](https://cloud.githubusercontent.com/assets/10584134/12527647/90c656d4-c17f-11e5-976a-d908fc5bfddc.png)

(please note I disabled h2 on the domain visible in the screenshot temporarily)

Any ideas what might be the cause?

Thanks!

**Comment by milansimek** [comment]
By the way, I'm using the default mpm_prefork, should I switch this to mpm_worker maybe?

**Comment by icing** [comment]
By default, http/2 uses only a single worker in prefork. This is because prefork is intended for things that do not like multi-threading.

Please try, if worker/event mitigates this problem. If that is so, and your apps can live with it, I recommend sticking to it. You *could* give prefork more than one worker, but that sort of defeats the purpose of prefork.

**Comment by icing** [comment]
Any results from trying my suggestions? Otherwise, I'd close this issue.

**Comment by milansimek** [comment]
Yes, I switched to mpm_worker and to php-fpm.

Works like a charm now, thanks!

**Comment by GreenReaper** [comment]
I suggest that this restriction, albeit sensible, be documented. I spent a day trying to work this out.

It seems that it was at one point, but that it was removed and did not make it to the official documentation.

**Comment by icing** [comment]
Good point. I'll reopen and write something in the Apache mod_http2 documentation.

**Comment by icing** [comment]
Documentation of this issue added in the official [howto documenation](http://httpd.apache.org/docs/trunk/en/howto/http2.html) for setting up HTTP/2 in Apache.
