### ISSUE TITLE
let a chance for SIGPIPE for cgi scripts to terminate before using SIGTERM or even SIGKILL

### ISSUE THREAD

**Issue by optyfr** [icing/mod_h2#84]
Hello,

When client aborts a request on a CGI script (mod_cgi) with h2 protocol activated, it seems that the script process is killed so that shutdown function are never called. As far as I know Apache will send a SIGPIPE with HTTP/1.1 to let scripts detect end of stream then gracefully finish

exemple script to try (yes, this is "php cli as cgi") :

> test.cgi

```
#!/usr/bin/php
<?php
error_log('script started');
$done=false;
register_shutdown_function('abort');

echo "Content-type: text/html\n\n";
echo "\n\n";
flush();

for($i = 1; $i <= 60; $i++)
{
	sleep(1);
	echo "$i<br>\n";
	error_log("$i");
}
$done = true;

function abort()
{
	global $done;
	if(!$done) error_log("aborted");
}
error_log('script ended');
?>
```

without H2 protocol, when I cancel request before 60s I get "aborted" in log
with H2 protocol, when I cancel before 60s I don't get "aborted" in log

**Comment by icing** [comment]
Hmm, testing with ```mod_cgi```on OS X I do not see an ```aborted``` in my logs, neither http/1.1 nor http/2. Both behave the same and stop logging the number a second or two later.

Do you have any more data to reproduce this? Also, I do not see the mentioned kill() invocation in the code, but I am not expert in these modules...

**Comment by optyfr** [comment]
maybe that osx version of PHP does not support register_function_shutdown() in cli mode?
It is PHP 5.6.14 and it must not be an interactive shell (php -a)

Since the request is aborted I can't print out on the screen the content of the shutdown function excepted via error_log

will try to get some debug from mod_cgi

**Comment by icing** [comment]
Which version of mod_http2 are you using, btw.?

**Comment by optyfr** [comment]
1.2.5

**Comment by optyfr** [comment]
no debug from mod_cgi

the only configuration manipulation between apache restarts is commenting/un-commenting Protocols directive

for cgi config, I have only
AddHandler cgi-script .cgi
Options +ExecCGI

not using suexec
chmod 755 test.cgi
chown apache:apache test.cgi

**Comment by optyfr** [comment]
to be sure of OS X capabilities, can you reduce to 10 instead of 60 and add
`echo "shutdown called\n";`
inside `function abort()` ?
then you should see 'shutdown called' when *not* aborting connection? same should happen when calling script directly from shell (and let it go to the end)

**Comment by icing** [comment]
Not sure what you are seeing. When I start the script:
```
#!/usr/bin/env php
<?php
error_log('script started');
$done=false;

function mewasaborted()
{
    global $done;
    if(!$done) error_log("aborted");
    error_log("shutdown");
}

register_shutdown_function('mewasaborted');

echo "Content-type: text/html\n\n";
echo "\n\n";
flush();

for($i = 1; $i <= 10; $i++)
{
    sleep(1);
    echo "$i<br>\n";
    error_log("$i");
}
$done = true;

error_log('script ended');
?>
```
from the command line, I get as output:
```
script started
Content-type: text/html



1<br>
1
2<br>
2
3<br>
3
4<br>
4
5<br>
5
6<br>
6
7<br>
7
8<br>
8
9<br>
9
10<br>
10
script ended
shutdown
```
If I hit ^C while running, I do not get any message, because no one reads stderr of that process anymore.

Same with ```mod_cgi```  in Apache. On timeout or connection close, the cgi just aborts the process and does not read stderr any longer. So, one does not see anything in the logs.

Sorry, but I am unable to reproduce and unable to come up with an explanation of what you seem to notice.

**Comment by optyfr** [comment]
I can now see why you can't reproduce : to log after connection abort from shutdown function, your php.ini (the one for cli version) has to be configured to log in a file and not print errors otherwise you won't see the "aborted" message...
From that, you will have to see the result in the log file, and you should notice the abort when in http/1.1 and not when using http/2

**Comment by icing** [comment]
You mean I spent some hours reproducing an error with your script that you yourself never tested?

**Comment by optyfr** [comment]
Of course I tested it, and it currently can show the problem using the first version of the script at the top of this issue as described, I just supposed too much about your default php configuration : you are using a "test/dev configuration" while I'm using a "prod configuration", the noticeable difference between the two php.ini is where error_log is writing out... that's why you could not reproduce on your OS X computer, but if you adjust your php.ini, you will start too see the problem as described
so just set in your php.ini :
display_errors = Off
log_errors = On
error_log=/var/log/apache2/php.log (or another place writeable for php)
at this point, you will notice that abort is printed in php.log only for http/1.1 case

**Comment by icing** [comment]
Ok, leaning php a bit. My script now looks like this, independent of any global ini settings:
```
#!/usr/bin/env php
<?php
ini_set('date.timezone', 'MET');
ini_set('error_log', '/tmp/php.log');
error_log('script started');
$done=false;

function mewasaborted()
{
    global $done;
    if(!$done) error_log("aborted");
    error_log("shutdown");
}

register_shutdown_function('mewasaborted');

echo "Content-type: text/html\n\n";
echo "\n\n";
flush();

for($i = 1; $i <= 10; $i++)
{
    sleep(1);
    echo "$i<br>\n";
    error_log("$i");
}
$done = true;

error_log('script ended');
?>
```
I start the server and run:
```
m -f /tmp/php.log; /opt/apache-trunk/bin/curl -k https://test.example.org:12346/abort_test.cgi; cat /tmp/php.log 
```
What I see on OS X:
```
1<br>
2<br>
^C
[11-Feb-2016 14:45:49 MET] script started
[11-Feb-2016 14:45:50 MET] 1
[11-Feb-2016 14:45:51 MET] 2
```
letting it run:
```
1<br>
2<br>
3<br>
4<br>
5<br>
6<br>
7<br>
8<br>
9<br>
10<br>
[11-Feb-2016 14:45:56 MET] script started
[11-Feb-2016 14:45:57 MET] 1
[11-Feb-2016 14:45:58 MET] 2
[11-Feb-2016 14:45:59 MET] 3
[11-Feb-2016 14:46:00 MET] 4
[11-Feb-2016 14:46:01 MET] 5
[11-Feb-2016 14:46:02 MET] 6
[11-Feb-2016 14:46:03 MET] 7
[11-Feb-2016 14:46:04 MET] 8
[11-Feb-2016 14:46:05 MET] 9
[11-Feb-2016 14:46:06 MET] 10
[11-Feb-2016 14:46:06 MET] script ended
[11-Feb-2016 14:46:06 MET] shutdown
```
On my Ubuntu machine, I see in 1 out of 10 cases where I interrupt the curl something like:
```
[11-Feb-2016 14:51:26 MET] script started
[11-Feb-2016 14:51:26 MET] aborted
[11-Feb-2016 14:51:26 MET] shutdown
[11-Feb-2016 14:51:27 MET] 1
```

So, this whole behaviour - so far having nothing to do with HTTP/2, is highly irregular. It seems that php sometimes invokes this function when the output goes, sometimes not. Given the fact, that ```mod_cgi``` never seems to send any signal, this seem to have nothing to do with HTTP/2 per se.

**Comment by optyfr** [comment]
OK, so it seems that php will call shutdown if it sees end of stream sometimes before getting killed but not always, this seems to be highly irregular and may even depend from many local things (server speed, net speed, os, ...). btw I think that the way http2 is working will increase this irregularity (let's say it is by design), so I will note that relying on clean shutdown on abort while using cgi is very unreliable
Thanks you for your patience

**Comment by icing** [comment]
You're welcome!
