### ISSUE TITLE
Does output is consumed till the end when connection is closed?

### ISSUE THREAD

**Issue by optyfr** [icing/mod_h2#85]
Hello,

More a question on a behavior for the moment than an issue, when sending a file thru php to the browser, if user cancel download, does mod_h2 silently consume output data up to the end?

I ask you this question because on the php side, the out stream is not closed and the data is send entirely as if the user never stopped the download and the output still available. It is not the same with HTTP/1.1
It happens with FireFox and Chrome, but maybe it is due to actual browser http/2 implementation?
Currently, I can't detect file download aborted by user on the server side when using h2
Apache is configured to call php-fpm with fastcgi via unix socket

**Comment by icing** [comment]
mod_http2 should detect the connection close by the client and abort the processing if any ongoing requests. So the question is more how this is interacting with your php-fpm setup. 

Can you make a http2:trace2 and proxy:debug log of such a case? Thanks.

**Comment by optyfr** [comment]
[ssl_error_log.gz](https://github.com/icing/mod_h2/files/138178/ssl_error_log.gz)

**Comment by icing** [comment]
@optyfr sorry this took me so long.

What I see in the log is the server sending out 47.236.043 bytes of response before the RST_STREAM from the client arrives and mod_http2 closes the request. Afterwards, the log does not show much.

How much of the response is still missing. If all that's left is sitting in some buffers already, your php will not have seen any error in writing.

**Comment by optyfr** [comment]
Hello,
there was still more than 30 MegaBytes to send to client, furthermore when the client connection is closed, the php fwrite loop is becoming suddenly accelerated (while still returning successfully on each fwrite) as if the rest of the output was send locally to /dev/null instead of receiving the EOF
But if there is still more than, let's say, 100Mo to send then, yes, it will be really aborted also on server side...
So if there is some buffers somewhere in-between php and mod_h2, then it is big enough to contain many MB of data;¨PHP output_buffering is 4096 bytes; don't know for apache proxy/fgci part for buffering but that behavior does not happen without h2 activated via protocols directive (but client does not behave the same too)

**Comment by icing** [comment]
FWIW: the new v1.5.5 sets the ```conn_rec->aborted``` for ongonig, request processing connections. While I do not think this is visible to PHP, it might be of interest to you.

**Comment by optyfr** [comment]
Ok I'll give it a try asap

Thanks

--
Stéphane BARBARAY

**Comment by optyfr** [comment]
Hello

Unfortunately, it does not compile here with gcc 4.9.3 :

h2_h2.c: In function ‘h2_h2_register_hooks’:
h2_h2.c:562:5: erreur: implicit declaration of function 
‘ap_hook_pre_close_connection’ [-Werror=implicit-function-declaration]
      ap_hook_pre_close_connection(h2_h2_pre_close_conn, NULL, mod_ssl, 
APR_HOOK_LAST);
      ^
cc1: all warnings being treated as errors
make[3]: *** [mod_http2_la-h2_h2.lo] Erreur 1





Le 18/05/2016 à 17:32, Stefan Eissing a écrit :
>
> FWIW: the new v1.5.5 sets the |conn_rec->aborted| for ongonig, request 
> processing connections. While I do not think this is visible to PHP, 
> it might be of interest to you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/icing/mod_h2/issues/85#issuecomment-220064924>
>


-- 
Stéphane BARBARAY

CompoData / IGE+XAO
Immeuble Vecteur Sud, Bâtiment C
72, Avenue de la république
92320 CHATILLON

www.compodata.com

Tel : (33) 1 55 48 17 87

"Turn your e-Catalog into a Business Strategy"

**Comment by optyfr** [comment]
Hello,

Same error with 1.5.6 today

Le 20/05/2016 à 15:07, Stephane BARBARAY a écrit :
> Hello
>
> Unfortunately, it does not compile here with gcc 4.9.3 :
>
> h2_h2.c: In function ‘h2_h2_register_hooks’:
> h2_h2.c:562:5: erreur: implicit declaration of function 
> ‘ap_hook_pre_close_connection’ [-Werror=implicit-function-declaration]
>      ap_hook_pre_close_connection(h2_h2_pre_close_conn, NULL, mod_ssl, 
> APR_HOOK_LAST);
>      ^
> cc1: all warnings being treated as errors
> make[3]: *** [mod_http2_la-h2_h2.lo] Erreur 1
>
>
>
>
>
> Le 18/05/2016 à 17:32, Stefan Eissing a écrit :
>>
>> FWIW: the new v1.5.5 sets the |conn_rec->aborted| for ongonig, 
>> request processing connections. While I do not think this is visible 
>> to PHP, it might be of interest to you.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/icing/mod_h2/issues/85#issuecomment-220064924>
>>
>
>
> -- 
> Stéphane BARBARAY
>
> CompoData / IGE+XAO
> Immeuble Vecteur Sud, Bâtiment C
> 72, Avenue de la république
> 92320 CHATILLON
>
> www.compodata.com
>
> Tel : (33) 1 55 48 17 87
>
> "Turn your e-Catalog into a Business Strategy"


-- 
Stéphane BARBARAY

CompoData / IGE+XAO
Immeuble Vecteur Sud, Bâtiment C
72, Avenue de la république
92320 CHATILLON

www.compodata.com

Tel : (33) 1 55 48 17 87

"Turn your e-Catalog into a Business Strategy"

**Comment by optyfr** [comment]
OK, realized that Apache 2.4.20 is needed now...

So, now with mod_h2 version 1.5.6 and apache 2.4.20, when a client click abort before the end of a download, the stream is correctly aborted server side up to the PHP code

**Comment by icing** [comment]
Thanks, optyfr! Good to know that this works now.
