### ISSUE TITLE
Server Push and Content Negotiation for encoding

### ISSUE THREAD

**Issue by mnot** [icing/mod_h2#86]
When push is configured (using the `preload` hint) for a resource that uses content negotiation, mod_h2 seems to push the "vanilla" representation.

E.g., in Chrome:

~~~
HTTP2_SESSION_RECV_PUSH_PROMISE
                      --> :scheme: https
                          :authority: www.mnot.net
                          :path: /style
                          :method: GET
                          user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
                          accept-language: en-US,en;q=0.8
                          host: www.mnot.net
                      --> id = 1
                      --> promised_stream_id = 2
~~~

[...]

~~~
HTTP2_SESSION_RECV_HEADERS
                      --> fin = false
                      --> :status: 200
                          date: Fri, 26 Feb 2016 01:45:07 GMT
                          server: Apache
                          content-location: style.css
                          vary: negotiate,accept-encoding
                          tcn: choice
                          last-modified: Fri, 26 Feb 2016 01:39:50 GMT
                          etag: "3bc4-52ca260059a20;52ca249153f28"
                          content-length: 15300
                          cache-control: max-age=604800
                          strict-transport-security: max-age=15552000
                          public-key-pins-report-only: max-age=604800; pin-sha256="ZitlqPmA9FDAxkwOW/c7ehlNFk8qJ9FmZLXG6GzdjNM="; pin-sha256="XRXP98inz4rd1/gS9fJSNVfyrZbqY00T7PeRXUPd15w="; pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="; report-uri="https://report-uri.io/report/01858f738ec81b54f9d077b025bf00de"
                          content-type: text/css
                          content-language: en
                      --> stream_id = 2
~~~

What's interesting is that the `PUSH_PROMISE` copied `Accept-Language` from stream 1, but not `Accept-Encoding`. So the pushed response is not gzipped, wasting a good amount of bandwidth.

This seems to be at <https://github.com/icing/mod_h2/blob/master/mod_http2/h2_push.c#L321>. Any reason why `Accept-Encoding` isn't in there?

It appears that conneg is running on that synthetic request, because `TCN`, `Vary` and `Content-Location` are there.

**Comment by icing** [comment]
You are correct, ```Accept-Encoding```should be there as well, as probably some others. I started very conservatively, it seems. Let's make up a complete list, shall we?:
  * ```Accept```
  * ```Accept-*``` (any header starting with)
  * ```Authorization``` ??? (if it is basic, will not work for digest, i think)
  * client hints? header names do not seem to follow a pattern in https://tools.ietf.org/html/draft-grigorik-http-client-hints-03, @igrigorik something to consider in case you ever extend this?

**Comment by mnot** [comment]
You're in the wonderful situation of knowing exactly what request headers the resource thinks is important, thanks to `Vary`. Why not just copy the request wholesale (changing the URL), make the subrequest and then prune the headers that aren't in `Vary` plus a whitelist (`Server`, etc.)?

**Comment by icing** [comment]
It's almost like that, except I send the promise before I have the response. And if I change that, either the initiating stream response would have to wait. Or the promises would be sent after that response, possibly meeting incoming preload streams on their way to the client. 

But apart from that, vary-pruning is a nice way of determining the minimal request header set. Thx.

We cleary need time travel. I'm a bit disappointed that google did not make it part of spdy.

**Comment by mnot** [comment]
Ah. That makes sense. 

I wonder if a blacklist-based approach might be better than a whitelist-based one.

**Comment by icing** [comment]
Sounds good. Care to make a suggestion? ;-)
